
/*IMPLEMENTATION FOR ADAPTERS PROGRESS API: 
 *
 *THIS CODE WAS GENERATED BY
 *  -Datasul Finance Adapters Generator - v0.09
 *  -16/9/2009 - 09:35
 *
 *DO NOT MODIFY THIS SOURCE CODE. IT IS MAINTAINED BY THE ADAPTERS MODEL
 *
 **/





{include/i_dbinst.i}
{include/i_dbtype.i}

/* DEFINICAO DE PRE-PROCESSADORES - BEGIN */
&GLOBAL-DEFINE XmlApp            FI5
&GLOBAL-DEFINE XmlMod            ACR
&GLOBAL-DEFINE XmlProdName       EMS5
&GLOBAL-DEFINE XmlProdVersion    506
&GLOBAL-DEFINE XmlTranName       CardAccountReceivable
&GLOBAL-DEFINE XmlMinTranVersion 001
&GLOBAL-DEFINE XmlMaxTranVersion 999
&GLOBAL-DEFINE XmlListOfAction   add,upd,del

/* DEFINICAO DE PRE-PROCESSADORES - END */

/*LOCAL VARIABLES - BEGIN*/
DEFINE VAR cReturnValue AS CHARACTER INITIAL ? NO-UNDO.
DEFINE VAR cTranAction AS CHARACTER INITIAL ? NO-UNDO.
DEFINE VAR cTranEvent AS CHARACTER INITIAL ? NO-UNDO.
DEFINE VAR cTranVersion AS CHARACTER INITIAL ? NO-UNDO.
DEFINE VAR hBusinessContent AS HANDLE NO-UNDO.
DEFINE VAR hGenXml AS HANDLE NO-UNDO.
DEFINE VAR hMessageHandler AS HANDLE NO-UNDO.
DEFINE VAR lSuccessProcess AS LOGICAL INITIAL ? NO-UNDO.

DEFINE TEMP-TABLE tt_log_erro NO-UNDO
     FIELD ttv_num_cod_erro AS integer INITIAL ?
     FIELD ttv_des_msg_ajuda AS character format "x(70)" INITIAL ?
     FIELD ttv_des_msg_erro AS character format "x(200)" INITIAL ?
.


DEFINE TEMP-TABLE ttAccountReceivableInform_00 NO-UNDO
     FIELD BranchCode AS CHARACTER INITIAL ?  /*C¢digo da estabelecimento (cod_estab)*/
     FIELD CardAuthorize AS CHARACTER INITIAL ?  /*C¢digo de autorizaá∆o do cart∆o (cod_autoriz_cartao_cr)*/
     FIELD CardSequence AS integer INITIAL ?  /*Sequencia (num_seq)*/
     FIELD CompanyCode AS CHARACTER INITIAL ?  /*C¢digo da empresa (cod_empresa)*/
     FIELD DateCredit AS date INITIAL ?  /*Data de CrÇdito (dat_cred_cartao_cr )*/
     FIELD DateSell AS date INITIAL ?  /*Data de Venda (dat_vda_cartao_cr)*/
     FIELD DocumentClassCode AS CHARACTER INITIAL ?  /*C¢digo da espÇcie de documento (cod_espec_docto)*/
     FIELD DocumentNumber AS CHARACTER INITIAL ?  /*N£mero do Documento (cod_tit_acr)*/
     FIELD DocumentParcelNumber AS CHARACTER INITIAL ?  /*Parcela (cod_parcela)*/
     FIELD DocumentSerieCode AS CHARACTER INITIAL ?  /*SÇrie do Documento (cod_ser_docto)*/
     FIELD ManagerNumber AS CHARACTER INITIAL ?  /*C¢digo da Administradora (cod_admdra)*/
     FIELD ParcelTotal AS CHARACTER INITIAL ?  /*N£mero total de parcelas (num_tot_parcela)*/
     FIELD ProofSell AS CHARACTER INITIAL ?  /*C¢digo de comprovante de venda (cod_comprov_vda)*/
     FIELD ReferCode AS CHARACTER INITIAL ?  /*C¢digo da referància*/
     FIELD RestoreCard AS LOGICAL INITIAL ?  /*Realizar AVA maior: yes or no*/
     FIELD SellResume AS CHARACTER INITIAL ?  /*C¢digo Resumo Venda (cod_res_vda)*/
     FIELD SituationAccount AS CHARACTER INITIAL ?  /*Indicador da Situaá∆o do T°tulo (ind_sit_tit_acr)*/
     FIELD ttAccountReceivableInform_00ID AS INTEGER INITIAL ?
     FIELD ValueManagerCard AS decimal INITIAL ?  /*Valor da Administradora do cart∆o (val_des_admdra)*/
     FIELD ValueSellProof AS decimal INITIAL ?  /*Valor do Comprovante de Venda (val_comprov_vda)*/
     INDEX ixttAccountReceivableInform_00ID IS PRIMARY UNIQUE ttAccountReceivableInform_00ID ASCENDING
.


DEFINE TEMP-TABLE ttCardAccountReceivableIn_00 NO-UNDO
     FIELD BranchCode AS CHARACTER INITIAL ?  /*C¢digo da estabelecimento (cod_estab)*/
     FIELD CardAuthorize AS CHARACTER INITIAL ?  /*C¢digo de autorizaá∆o do cart∆o (cod_autoriz_cartao_cr)*/
     FIELD CardSequence AS integer INITIAL ?  /*Sequencia (num_seq)*/
     FIELD CompanyCode AS CHARACTER INITIAL ?  /*C¢digo da empresa (cod_empresa)*/
     FIELD DateCredit AS date INITIAL ?  /*Data de CrÇdito (dat_cred_cartao_cr )*/
     FIELD DateSell AS date INITIAL ?  /*Data de Venda (dat_vda_cartao_cr)*/
     FIELD DocumentClassCode AS CHARACTER INITIAL ?  /*C¢digo da espÇcie de documento (cod_espec_docto)*/
     FIELD DocumentNumber AS CHARACTER INITIAL ?  /*N£mero do Documento (cod_tit_acr)*/
     FIELD DocumentParcelNumber AS CHARACTER INITIAL ?  /*Parcela (cod_parcela)*/
     FIELD DocumentSerieCode AS CHARACTER INITIAL ?  /*SÇrie do Documento (cod_ser_docto)*/
     FIELD ManagerNumber AS CHARACTER INITIAL ?  /*C¢digo da Administradora (cod_admdra)*/
     FIELD ParcelTotal AS CHARACTER INITIAL ?  /*N£mero total de parcelas (num_tot_parcela)*/
     FIELD ProofSell AS CHARACTER INITIAL ?  /*C¢digo de comprovante de venda (cod_comprov_vda)*/
     FIELD ReferCode AS CHARACTER INITIAL ?  /*C¢digo da referància*/
     FIELD RestoreCard AS LOGICAL INITIAL ?  /*Realizar AVA maior: yes or no*/
     FIELD SellResume AS CHARACTER INITIAL ?  /*C¢digo Resumo Venda (cod_res_vda)*/
     FIELD SituationAccount AS CHARACTER INITIAL ?  /*Indicador da Situaá∆o do T°tulo (ind_sit_tit_acr)*/
     FIELD ttCardAccountReceivableIn_00ID AS INTEGER INITIAL ?
     FIELD ValueManagerCard AS decimal INITIAL ?  /*Valor da Administradora do cart∆o (val_des_admdra)*/
     FIELD ValueSellProof AS decimal INITIAL ?  /*Valor do Comprovante de Venda (val_comprov_vda)*/
     INDEX ixttCardAccountReceivableIn_00ID IS PRIMARY UNIQUE ttCardAccountReceivableIn_00ID ASCENDING
.


DEFINE TEMP-TABLE ttCardAccountReceivableIn_01 NO-UNDO
     FIELD BranchCode AS CHARACTER INITIAL ?  /*C¢digo da estabelecimento (cod_estab)*/
     FIELD CardSequence AS integer INITIAL ?  /*N£mero da Sequencia (num_seq)*/
     FIELD DocumentClassCode AS CHARACTER INITIAL ?  /*C¢digo da espÇcie de documento (cod_espec_docto)*/
     FIELD DocumentNumber AS CHARACTER INITIAL ?  /*N£mero do Documento (cod_tit_acr)*/
     FIELD DocumentParcelNumber AS CHARACTER INITIAL ?  /*Parcela (cod_parcela)*/
     FIELD DocumentSerieCode AS CHARACTER INITIAL ?  /*SÇrie do Documento (cod_ser_docto)*/
     FIELD ttCardAccountReceivableIn_01ID AS INTEGER INITIAL ?
     INDEX ixttCardAccountReceivableIn_01ID IS PRIMARY UNIQUE ttCardAccountReceivableIn_01ID ASCENDING
.

/*LOCAL VARIABLES - END*/

/*PARAMETERS - BEGIN*/
/*PARAMETERS - END*/




{adapters\xml\fi5\axrfi010ExtraDeclarations.i}




/* DEF. VARIµVEIS USADAS EM xmlLoadMessageHandlerRec.i */
{xmlinc/xmlLoadMessageHandlerRecDef.i}

/* DEFINE AS VARAIVEIS PARA USO DO xmlLoadGenXmlRec.i */
{xmlinc/xmlLoadGenXmlRecDef.i}


/* DEFINE AS VARIAVEIS PARA USO DO xmlgettranssubsinfo */
{xmlinc/xmlgettranssubsinfo.i}

DEFINE TEMP-TABLE ttStack NO-UNDO
     FIELD ttID AS INTEGER
     FIELD ttPos AS INTEGER
     INDEX tt_id IS PRIMARY UNIQUE
           ttID  ASCENDING.


FUNCTION addStack RETURN INTEGER (INPUT val AS INTEGER).
     DEFINE VAR id AS INTEGER INITIAL 1 NO-UNDO.
     FIND LAST ttStack NO-ERROR.
     IF AVAIL(ttStack) THEN
          id = ttStack.ttID + 1.

     CREATE ttStack.
     ASSIGN ttStack.ttID = id.
     ASSIGN ttStack.ttPos = val.
END FUNCTION.


FUNCTION delStack RETURN INTEGER.
     FIND LAST ttStack NO-ERROR.
     IF AVAIL(ttStack) THEN
          DELETE ttStack.

     FIND LAST ttStack NO-ERROR.
END FUNCTION.


FUNCTION getStack RETURN INTEGER.
     IF AVAIL(ttStack) THEN
          RETURN ttStack.ttPos.
     ELSE
          RETURN 0.
END FUNCTION.




/* Begin_Include: i_version_extract */
def new global shared var v_cod_arq as char format 'x(60)' no-undo.
def new global shared var v_cod_tip_prog as character format 'x(8)' no-undo.
def stream s-arq.

if  v_cod_arq <> '' and v_cod_arq <> ?
then do:
     run pi_version_extract ('CardAccountReceivableReceiver', 'adapters\xml\fi5\axrfi010.p', '001', 'pro').
end /* if */.
/* End_Include: i_version_extract */


/****** INTERNAL PROCEDURES - BEGIN*/
/*****************************************************************************
** Procedure Interna.....: pi_retorna_sugestao_referencia
** Descricao.............: pi_retorna_sugestao_referencia
** Criado por............: Barth
** Criado em.............: 21/10/1998 09:14:30
** Alterado por..........: Souza
** Alterado em...........: 18/05/1999 10:12:58
*****************************************************************************/
PROCEDURE pi_retorna_sugestao_referencia:

    /************************ Parameter Definition Begin ************************/

    def Input param p_ind_tip_atualiz
        as character
        format "X(08)"
        no-undo.
    def Input param p_dat_refer
        as date
        format "99/99/9999"
        no-undo.
    def output param p_cod_refer
        as character
        format "x(10)"
        no-undo.


    /************************* Parameter Definition End *************************/

    /************************* Variable Definition Begin ************************/

    def var v_des_dat                        as character       no-undo. /*local*/
    def var v_num_aux                        as integer         no-undo. /*local*/
    def var v_num_aux_2                      as integer         no-undo. /*local*/
    def var v_num_cont                       as integer         no-undo. /*local*/


    /************************** Variable Definition End *************************/

    assign v_des_dat   = string(p_dat_refer,"99999999")
           p_cod_refer = substring(v_des_dat,7,2)
                       + substring(v_des_dat,3,2)
                       + substring(v_des_dat,1,2)
                       + substring(p_ind_tip_atualiz,1,1)
           v_num_aux_2 = integer(this-procedure:handle).

    do  v_num_cont = 1 to 3:
        assign v_num_aux   = (random(0,v_num_aux_2) mod 26) + 97
               p_cod_refer = p_cod_refer + chr(v_num_aux).
    end.
END PROCEDURE. /* pi_retorna_sugestao_referencia */

PROCEDURE pi_verifica_refer_unica_acr:

    /************************ Parameter Definition Begin ************************/

    def Input param p_cod_estab
        as character
        format "x(3)"
        no-undo.
    def Input param p_cod_refer
        as character
        format "x(10)"
        no-undo.
    def Input param p_cod_table
        as character
        format "x(8)"
        no-undo.
    def Input param p_rec_tabela
        as recid
        format ">>>>>>9"
        no-undo.
    def output param p_log_refer_uni
        as logical
        format "Sim/N∆o"
        no-undo.


    /************************* Parameter Definition End *************************/

    /************************** Buffer Definition Begin *************************/

    def buffer b_cobr_especial_acr
        for cobr_especial_acr.
    def buffer b_lote_impl_tit_acr
        for lote_impl_tit_acr.
    def buffer b_lote_liquidac_acr
        for lote_liquidac_acr.
    def buffer b_movto_tit_acr
        for movto_tit_acr.
    def buffer b_operac_financ_acr
        for operac_financ_acr.
    def buffer b_renegoc_acr
        for renegoc_acr.


    /*************************** Buffer Definition End **************************/

    /************************* Variable Definition Begin ************************/

    def var v_cod_return
        as character
        format "x(40)":U
        no-undo.


    /************************** Variable Definition End *************************/

    assign p_log_refer_uni = yes.

    if  p_cod_table <> "lote_impl_tit_acr" /*l_lote_impl_tit_acr*/  then do:
        find first b_lote_impl_tit_acr no-lock
             where b_lote_impl_tit_acr.cod_estab = p_cod_estab
               and b_lote_impl_tit_acr.cod_refer = p_cod_refer
               and recid( b_lote_impl_tit_acr ) <> p_rec_tabela
             use-index ltmplttc_id no-error.
        if  avail b_lote_impl_tit_acr then
            assign p_log_refer_uni = no.
    end.

    if  p_cod_table <> "lote_liquidac_acr" /*l_lote_liquidac_acr*/  then do:
        find first b_lote_liquidac_acr no-lock
             where b_lote_liquidac_acr.cod_estab_refer = p_cod_estab
               and b_lote_liquidac_acr.cod_refer       = p_cod_refer
               and recid( b_lote_liquidac_acr )       <> p_rec_tabela
             use-index ltlqdccr_id no-error.
        if  avail b_lote_liquidac_acr then
            assign p_log_refer_uni = no.
    end.

    if  p_cod_table <> "Operaá∆o financeira" /*l_operacao_financ*/  then do:
        find first b_operac_financ_acr no-lock
             where b_operac_financ_acr.cod_estab               = p_cod_estab
               and b_operac_financ_acr.cod_movto_operac_financ = p_cod_refer
               and recid( b_operac_financ_acr )               <> p_rec_tabela
             use-index oprcfnna_id no-error.
        if  avail b_operac_financ_acr then
            assign p_log_refer_uni = no.
    end.

    if  p_cod_table = 'cobr_especial_acr' then do:
        find first b_cobr_especial_acr no-lock
             where b_cobr_especial_acr.cod_estab = p_cod_estab
               and b_cobr_especial_acr.cod_refer = p_cod_refer
               and recid( b_cobr_especial_acr ) <> p_rec_tabela
             use-index cbrspclc_id no-error.
        if  avail b_cobr_especial_acr then
            assign p_log_refer_uni = no.
    end.


    IF CAN-FIND (FIRST tt_alter_tit_acr_base_5 NO-LOCK 
       where tt_alter_tit_acr_base_5.tta_cod_estab = p_cod_estab
         and tt_alter_tit_acr_base_5.tta_cod_refer = p_cod_refer) THEN 
       assign p_log_refer_uni = no.


    if  p_log_refer_uni = yes then do:
        find first b_renegoc_acr no-lock
            where b_renegoc_acr.cod_estab = p_cod_estab
            and   b_renegoc_acr.cod_refer = p_cod_refer
            and   recid(b_renegoc_acr)   <> p_rec_tabela
            no-error.
        if  avail b_renegoc_acr then
            assign p_log_refer_uni = no.
        else do:
            find first b_movto_tit_acr no-lock
                 where b_movto_tit_acr.cod_estab = p_cod_estab
                   and b_movto_tit_acr.cod_refer = p_cod_refer
                   and recid(b_movto_tit_acr)   <> p_rec_tabela
                 use-index mvtttcr_refer
                 no-error.
            if  avail b_movto_tit_acr then
                assign p_log_refer_uni = no.
        end.
    end.
END PROCEDURE. /* pi_verifica_refer_unica_acr */


PROCEDURE pi_version_extract:

/*PARAMETERS - BEGIN*/
/*PARAMETERS - END*/


/*LOCAL VARIABLES - BEGIN*/
/*LOCAL VARIABLES - END*/


/* ******************************************* */
/* *************** BODY - BEGIN ************** */
/* ******************************************* */

/************************ Parameter Definition Begin ************************/
def Input param p_cod_program as character format "x(8)" no-undo.
def Input param p_cod_program_ext as character format "x(8)" no-undo.
def Input param p_cod_version as character format "x(8)" no-undo.
def Input param p_cod_program_type as character format "x(8)" no-undo.
/************************* Parameter Definition End *************************/
if  can-do(v_cod_tip_prog, p_cod_program_type)
then do:
if p_cod_program_type = 'dic' then 
     assign p_cod_program_ext = replace(p_cod_program_ext, 'database/', '').
     output stream s-arq to value(v_cod_arq) append.

     put stream s-arq unformatted
          p_cod_program            at 1
          p_cod_program_ext        at 43
          p_cod_version            at 69
          today                    at 84
          string(time, 'HH:MM:SS') at 94 skip.

     if  p_cod_program_type = 'pro' then do:
          find prog_dtsul 
               where prog_dtsul.cod_prog_dtsul = p_cod_program 
               no-lock no-error.

          if  avail prog_dtsul
          then do:
                    if  prog_dtsul.nom_prog_dpc <> '' then
                         put stream s-arq 'DPC : ' at 5 prog_dtsul.nom_prog_dpc  at 15 skip.

               if  prog_dtsul.nom_prog_appc <> '' then
                    put stream s-arq 'APPC: ' at 5 prog_dtsul.nom_prog_appc at 15 skip.
               if  prog_dtsul.nom_prog_upc <> '' then
                    put stream s-arq 'UPC : ' at 5 prog_dtsul.nom_prog_upc  at 15 skip.
          end /* if */.
     end.



     output stream s-arq close.

end /* if */.

/* ******************************************* */
/* *************** BODY - END   ************** */
/* ******************************************* */

END PROCEDURE.


PROCEDURE PIDelete:

/*PARAMETERS - BEGIN*/
/*PARAMETERS - END*/


/*LOCAL VARIABLES - BEGIN*/
DEFINE VAR iId AS INTEGER INITIAL ? NO-UNDO.
/*LOCAL VARIABLES - END*/


/* ******************************************* */
/* *************** BODY - BEGIN ************** */
/* ******************************************* */


     /* OBTEM A PARTE DA MENSAGEM QUE ESTÊ ABAIXO DO ELEMENTO BusinessContent */
     RUN getBusinessContent IN hMessageHandler (OUTPUT hBusinessContent).

     /* LIMPA AS TEMP-TABLES INTERNAS DA API XML */
     RUN reset IN hGenXml.

     /* CARREGA A ESTRUTURA FILHA DE BusinessContent */
     RUN loadXml IN hGenXml (hBusinessContent).

     /* ELIMINA A MENSAGEM OBTIDA NO MêTODO getBusinessContent */
     DELETE OBJECT hBusinessContent NO-ERROR.

     /* ********* LEITURA DA MENSAGEM - BEGIN ********* */
     addStack(1).
          RUN searchTag IN hGenXml (INPUT "ListOfCardAccountReceivableInformation", INPUT getStack(), OUTPUT iId).
          if (iId <> ?) THEN DO:
               addStack(iId).

                    RUN getFirstSonId IN hGenXml (INPUT getStack(), OUTPUT iId).

                    DO WHILE iId <> ?:
                    addStack(iId).

                         /*Criacao de valores para manter as relacoes*/
                         CREATE ttCardAccountReceivableIn_01.
                         ASSIGN ttCardAccountReceivableIn_01.ttCardAccountReceivableIn_01ID = iId.

                         RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "BranchCode", OUTPUT ttCardAccountReceivableIn_01.BranchCode).
                         RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "DocumentClassCode", OUTPUT ttCardAccountReceivableIn_01.DocumentClassCode).
                         RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "DocumentSerieCode", OUTPUT ttCardAccountReceivableIn_01.DocumentSerieCode).
                         RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "DocumentNumber", OUTPUT ttCardAccountReceivableIn_01.DocumentNumber).
                         RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "DocumentParcelNumber", OUTPUT ttCardAccountReceivableIn_01.DocumentParcelNumber).
                         RUN getSonDec IN hGenXml (INPUT getStack(), INPUT "CardSequence", OUTPUT ttCardAccountReceivableIn_01.CardSequence).
                         ASSIGN iId = getStack().
                         delStack().
                         RUN getNextSonId IN hGenXml (INPUT getStack(), INPUT iId, OUTPUT iId).
                    END.

               delStack().
          END.

     delStack().
     /* ********* LEITURA DA MENSAGEM - END   ********* */


     /* ********* EFETIVAÄ«O - BEGIN ********* */



{adapters\xml\fi5\axrfi010Delete.i}


     /* ********* EFETIVAÄ«O - END   ********* */

/* ******************************************* */
/* *************** BODY - END   ************** */
/* ******************************************* */

END PROCEDURE.


PROCEDURE PIRecordInformation:

/*PARAMETERS - BEGIN*/
/*PARAMETERS - END*/


/*LOCAL VARIABLES - BEGIN*/
DEFINE VAR iId AS INTEGER INITIAL ? NO-UNDO.
/*LOCAL VARIABLES - END*/


/* ******************************************* */
/* *************** BODY - BEGIN ************** */
/* ******************************************* */

          RUN searchTag IN hGenXml (INPUT "RecordInformation", INPUT getStack(), OUTPUT iId).
          if (iId <> ?) THEN DO:
               addStack(iId).

                    RUN searchTag IN hGenXml (INPUT "ListOfCardAccountReceivable", INPUT getStack(), OUTPUT iId).
                    if (iId <> ?) THEN DO:
                         addStack(iId).

                              RUN getFirstSonId IN hGenXml (INPUT getStack(), OUTPUT iId).

                              DO WHILE iId <> ?:
                              addStack(iId).

                                   /*Criacao de valores para manter as relacoes*/
                                   CREATE ttCardAccountReceivableIn_00.
                                   ASSIGN ttCardAccountReceivableIn_00.ttCardAccountReceivableIn_00ID = iId.

                                   RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "CompanyCode", OUTPUT ttCardAccountReceivableIn_00.CompanyCode).
                                   RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "BranchCode", OUTPUT ttCardAccountReceivableIn_00.BranchCode).
                                   RUN getSonLog IN hGenXml (INPUT getStack(), INPUT "RestoreCard", OUTPUT ttCardAccountReceivableIn_00.RestoreCard).
                                   RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "DocumentClassCode", OUTPUT ttCardAccountReceivableIn_00.DocumentClassCode).
                                   RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "DocumentSerieCode", OUTPUT ttCardAccountReceivableIn_00.DocumentSerieCode).
                                   RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "DocumentNumber", OUTPUT ttCardAccountReceivableIn_00.DocumentNumber).
                                   RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "DocumentParcelNumber", OUTPUT ttCardAccountReceivableIn_00.DocumentParcelNumber).
                                   RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "ManagerNumber", OUTPUT ttCardAccountReceivableIn_00.ManagerNumber).
                                   RUN getSonDec IN hGenXml (INPUT getStack(), INPUT "CardSequence", OUTPUT ttCardAccountReceivableIn_00.CardSequence).
                                   RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "ParcelTotal", OUTPUT ttCardAccountReceivableIn_00.ParcelTotal).
                                   RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "ProofSell", OUTPUT ttCardAccountReceivableIn_00.ProofSell).
                                   RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "CardAuthorize", OUTPUT ttCardAccountReceivableIn_00.CardAuthorize).
                                   RUN getSonDate IN hGenXml (INPUT getStack(), INPUT "DateSell", OUTPUT ttCardAccountReceivableIn_00.DateSell).
                                   RUN getSonDate IN hGenXml (INPUT getStack(), INPUT "DateCredit", OUTPUT ttCardAccountReceivableIn_00.DateCredit).
                                   RUN getSonDec IN hGenXml (INPUT getStack(), INPUT "ValueSellProof", OUTPUT ttCardAccountReceivableIn_00.ValueSellProof).
                                   RUN getSonDec IN hGenXml (INPUT getStack(), INPUT "ValueManagerCard", OUTPUT ttCardAccountReceivableIn_00.ValueManagerCard).
                                   RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "SituationAccount", OUTPUT ttCardAccountReceivableIn_00.SituationAccount).
                                   RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "SellResume", OUTPUT ttCardAccountReceivableIn_00.SellResume).
                                   RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "ReferCode", OUTPUT ttCardAccountReceivableIn_00.ReferCode).
                                   ASSIGN iId = getStack().
                                   delStack().
                                   RUN getNextSonId IN hGenXml (INPUT getStack(), INPUT iId, OUTPUT iId).
                              END.

                         delStack().
                    END.

               delStack().
          END.

/* ******************************************* */
/* *************** BODY - END   ************** */
/* ******************************************* */

END PROCEDURE.


PROCEDURE PIUpdateInformation:

/*PARAMETERS - BEGIN*/
/*PARAMETERS - END*/


/*LOCAL VARIABLES - BEGIN*/
DEFINE VAR iId AS INTEGER INITIAL ? NO-UNDO.
/*LOCAL VARIABLES - END*/


/* ******************************************* */
/* *************** BODY - BEGIN ************** */
/* ******************************************* */

          RUN searchTag IN hGenXml (INPUT "UpdateInformation", INPUT getStack(), OUTPUT iId).
          if (iId <> ?) THEN DO:
               addStack(iId).

                    RUN searchTag IN hGenXml (INPUT "ListOfAccountReceivableDocument", INPUT getStack(), OUTPUT iId).
                    if (iId <> ?) THEN DO:
                         addStack(iId).

                              RUN getFirstSonId IN hGenXml (INPUT getStack(), OUTPUT iId).

                              DO WHILE iId <> ?:
                              addStack(iId).

                                   /*Criacao de valores para manter as relacoes*/
                                   CREATE ttAccountReceivableInform_00.
                                   ASSIGN ttAccountReceivableInform_00.ttAccountReceivableInform_00ID = iId.

                                   RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "CompanyCode", OUTPUT ttAccountReceivableInform_00.CompanyCode).
                                   RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "BranchCode", OUTPUT ttAccountReceivableInform_00.BranchCode).
                                   RUN getSonLog IN hGenXml (INPUT getStack(), INPUT "RestoreCard", OUTPUT ttAccountReceivableInform_00.RestoreCard).
                                   RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "DocumentClassCode", OUTPUT ttAccountReceivableInform_00.DocumentClassCode).
                                   RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "DocumentSerieCode", OUTPUT ttAccountReceivableInform_00.DocumentSerieCode).
                                   RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "DocumentNumber", OUTPUT ttAccountReceivableInform_00.DocumentNumber).
                                   RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "DocumentParcelNumber", OUTPUT ttAccountReceivableInform_00.DocumentParcelNumber).
                                   RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "ManagerNumber", OUTPUT ttAccountReceivableInform_00.ManagerNumber).
                                   RUN getSonDec IN hGenXml (INPUT getStack(), INPUT "CardSequence", OUTPUT ttAccountReceivableInform_00.CardSequence).
                                   RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "ParcelTotal", OUTPUT ttAccountReceivableInform_00.ParcelTotal).
                                   RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "ProofSell", OUTPUT ttAccountReceivableInform_00.ProofSell).
                                   RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "CardAuthorize", OUTPUT ttAccountReceivableInform_00.CardAuthorize).
                                   RUN getSonDate IN hGenXml (INPUT getStack(), INPUT "DateSell", OUTPUT ttAccountReceivableInform_00.DateSell).
                                   RUN getSonDate IN hGenXml (INPUT getStack(), INPUT "DateCredit", OUTPUT ttAccountReceivableInform_00.DateCredit).
                                   RUN getSonDec IN hGenXml (INPUT getStack(), INPUT "ValueSellProof", OUTPUT ttAccountReceivableInform_00.ValueSellProof).
                                   RUN getSonDec IN hGenXml (INPUT getStack(), INPUT "ValueManagerCard", OUTPUT ttAccountReceivableInform_00.ValueManagerCard).
                                   RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "SituationAccount", OUTPUT ttAccountReceivableInform_00.SituationAccount).
                                   RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "SellResume", OUTPUT ttAccountReceivableInform_00.SellResume).
                                   RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "ReferCode", OUTPUT ttAccountReceivableInform_00.ReferCode).
                                   ASSIGN iId = getStack().
                                   delStack().
                                   RUN getNextSonId IN hGenXml (INPUT getStack(), INPUT iId, OUTPUT iId).
                              END.

                         delStack().
                    END.

               delStack().
          END.

/* ******************************************* */
/* *************** BODY - END   ************** */
/* ******************************************* */

END PROCEDURE.


PROCEDURE PIUpsert:

/*PARAMETERS - BEGIN*/
/*PARAMETERS - END*/


/*LOCAL VARIABLES - BEGIN*/
DEFINE VAR iId AS INTEGER INITIAL ? NO-UNDO.
/*LOCAL VARIABLES - END*/


/* ******************************************* */
/* *************** BODY - BEGIN ************** */
/* ******************************************* */


     /* OBTEM A PARTE DA MENSAGEM QUE ESTÊ ABAIXO DO ELEMENTO BusinessContent */
     RUN getBusinessContent IN hMessageHandler (OUTPUT hBusinessContent).

     /* LIMPA AS TEMP-TABLES INTERNAS DA API XML */
     RUN reset IN hGenXml.

     /* CARREGA A ESTRUTURA FILHA DE BusinessContent */
     RUN loadXml IN hGenXml (hBusinessContent).

     /* ELIMINA A MENSAGEM OBTIDA NO MêTODO getBusinessContent */
     DELETE OBJECT hBusinessContent NO-ERROR.

     /* ********* LEITURA DA MENSAGEM - BEGIN ********* */
     addStack(1).
          RUN PIRecordInformation
          .

          RUN PIUpdateInformation
          .

     delStack().
     /* ********* LEITURA DA MENSAGEM - END   ********* */


     /* ********* EFETIVAÄ«O - BEGIN ********* */



{adapters\xml\fi5\axrfi010Upsert.i}


     /* ********* EFETIVAÄ«O - END   ********* */

/* ******************************************* */
/* *************** BODY - END   ************** */
/* ******************************************* */

END PROCEDURE.


PROCEDURE receiveMessage:

/*PARAMETERS - BEGIN*/
DEFINE INPUT PARAM hInputXML AS HANDLE NO-UNDO.
DEFINE OUTPUT PARAM hOutputXML AS HANDLE NO-UNDO.
/*PARAMETERS - END*/


/*LOCAL VARIABLES - BEGIN*/
/*LOCAL VARIABLES - END*/


/* ******************************************* */
/* *************** BODY - BEGIN ************** */
/* ******************************************* */

     /* VERIFICA SE MessageHandler.p ESTA NA MEMORIA */
     {xmlinc/xmlLoadMessageHandlerRec.i &MessageHandler="hMessageHandler" &MHReturnValue="cReturnValue" &MHReturnError="hOutputXML"}

     IF cReturnValue <> "OK" THEN DO:
          RETURN cReturnValue.
     END.

     /* INTERPRETA, ARMAZENA E VALIDA A MENSAGEM QUE RECEBE */
     RUN parseMessage IN hMessageHandler (
          INPUT  hInputXml, INPUT "{&XmlTranName}", 
          INPUT "{&XmlMaxTranVersion}", 
          INPUT "{&XmlMinTranVersion}", 
          INPUT "{&XmlListOfEvents}",
          OUTPUT lSuccessProcess,
          OUTPUT cTranAction, 
          OUTPUT cTranEvent,
          OUTPUT cTranVersion,
          OUTPUT hOutputXML ).

     /* SE N«O PROCESSOU CORRETAMENTE RETORNA ERRO */
     IF NOT lSuccessProcess OR RETURN-VALUE <> "OK" THEN 
     /* DAR TRATAMENTO CONVENIENTE ANTES DE RETORNAR */
          RETURN RETURN-VALUE.

     /* VERIFICA SE APIXML ESTA NA MEMORIA */
     {xmlinc/xmlloadgenxmlrec.i &GenXml="hGenXml" &GXReturnValue="cReturnValue" &GXReturnError="hOutputXML"}

     /* VERIFICA SE O ut-genxml FOI INICIADO CORRETAMENTE */
     IF cReturnValue <> "OK"
     THEN DO:
          /* ELIMINA A MENSAGEM OBTIDA NO M?TODO getBusinessContent */
          DELETE OBJECT hBusinessContent NO-ERROR.

          RETURN cReturnValue.
     END.



{adapters\xml\fi5\axrfi010VersionControl.i}



/* ******************************************* */
/* *************** BODY - END   ************** */
/* ******************************************* */

END PROCEDURE.

/*****************************************************************************
** Procedure Interna.....: pi_retornar_finalid_indic_econ
*****************************************************************************/
PROCEDURE pi_retornar_finalid_indic_econ:
    /************************ Parameter Definition Begin ************************/
    def Input param p_cod_indic_econ    as CHAR format "x(8)" no-undo.
    def Input param p_dat_transacao     as DATE format "99/99/9999" no-undo.
    def output param p_cod_finalid_econ as CHAR format "x(10)" no-undo.

    /************************* Parameter Definition End *************************/
    for first histor_finalid_econ fields (cod_finalid_econ) no-lock
        where histor_finalid_econ.cod_indic_econ          = p_cod_indic_econ
        and   histor_finalid_econ.dat_inic_valid_finalid <= p_dat_transacao
        and   histor_finalid_econ.dat_fim_valid_finalid  > p_dat_transacao.

        if avail histor_finalid_econ then
           assign p_cod_finalid_econ = histor_finalid_econ.cod_finalid_econ.
    end.
END PROCEDURE. /* pi_retornar_finalid_indic_econ */

procedure pi_grava_erros_api:

    /*****************************************************************************************/
    /** Imprime os erros retornados pela API                                            **/
    /*****************************************************************************************/
    for each tt_log_erros_alter_tit_acr no-lock:

        find first tit_acr where tit_acr.cod_estab = tt_log_erros_alter_tit_acr.tta_cod_estab
                             and tit_acr.num_id_tit_acr = tt_log_erros_alter_tit_acr.tta_num_id_tit_acr
            no-lock no-error.

        assign v_log_control = no.

        create tt_log_erro.
        assign tt_log_erro.ttv_num_cod_erro = tt_log_erros_alter_tit_acr.ttv_num_mensagem
               tt_log_erro.ttv_des_msg_erro = tt_log_erros_alter_tit_acr.ttv_des_msg_erro.

        if  tt_log_erros_alter_tit_acr.ttv_des_msg_ajuda <> "" then
            assign tt_log_erro.ttv_des_msg_erro = tt_log_erro.ttv_des_msg_erro + chr(10) + chr(10) +
                                                  tt_log_erros_alter_tit_acr.ttv_des_msg_ajuda.
        
        find first tit_acr where tit_acr.cod_estab      = tt_log_erros_alter_tit_acr.tta_cod_estab
                             and tit_acr.num_id_tit_acr = tt_log_erros_alter_tit_acr.tta_num_id_tit_acr no-lock no-error.

        if avail tit_acr then do:

            assign v_erro_codigo = tt_log_erros_alter_tit_acr.ttv_num_mensagem
                   v_erro_descri = tt_log_erros_alter_tit_acr.ttv_des_msg_erro
                   v_ajuda       = tt_log_erros_alter_tit_acr.ttv_des_msg_ajuda.

            create tt_erro_implanta.
            assign tt_erro_implanta.tta_cod_erro   = v_erro_codigo
                   tt_erro_implanta.tta_informacao = tit_acr.cod_estab       + "," +
                                                     tit_acr.cod_espec_docto + "," +
                                                     tit_acr.cod_ser_docto   + "," +
                                                     tit_acr.cod_tit_acr     + "," +
                                                     ""                      + "," +
                                                     ""                      + "," +
                                                     ""                      + "," +
                                                     ""                      + "," +
                                                     ""                      + "," +
                                                     ""                      + "," +
                                                     ""                      + "," +
                                                     tit_acr.cod_parcela
                   tt_erro_implanta.tta_des_erro   = v_erro_descri
                   tt_erro_implanta.tta_ajuda      = v_ajuda.

            
        end.
        else do:

            assign v_erro_codigo = tt_log_erros_alter_tit_acr.ttv_num_mensagem
                   v_erro_descri = tt_log_erros_alter_tit_acr.ttv_des_msg_erro
                   v_ajuda       = tt_log_erros_alter_tit_acr.ttv_des_msg_ajuda.

            create tt_erro_implanta.
            assign tt_erro_implanta.tta_cod_erro   = v_erro_codigo
                   tt_erro_implanta.tta_informacao = tt_log_erros_alter_tit_acr.tta_cod_estab               + "," +
                                                     ""                                                     + "," +
                                                     ""                                                     + "," +
                                                     ""                                                     + "," +
                                                     ""                                                     + "," +
                                                     ""                                                     + "," +
                                                     ""                                                     + "," +
                                                     ""                                                     + "," +
                                                     ""                                                     + "," +
                                                     ""                                                     + "," +
                                                     string(tt_log_erros_alter_tit_acr.tta_num_id_tit_acr)  + "," +
                                                     ""
                   tt_erro_implanta.tta_des_erro   = v_erro_descri
                   tt_erro_implanta.tta_ajuda      = v_ajuda.
            

        end.
    end.
end.



/****** INTERNAL PROCEDURES - END*/


