PROCEDURE pi-calc:


    DEFINE INPUT PARAMETER pOperador AS CHAR NO-UNDO.
    DEFINE INPUT PARAMETER pnum1 AS DECIMAL NO-UNDO.
    DEFINE INPUT PARAMETER pnum2 AS DECIMAL NO-UNDO.
    DEFINE INPUT PARAMETER pResult AS DECIMAL NO-UNDO.

    ASSIGN pResult = pNum1 + pNum2.

END PROCEDURE.
