DEFINE VARIABLE hSocket AS HANDLE NO-UNDO. 
DEFINE VARIABLE cPort AS CHARACTER NO-UNDO INITIAL "443". 
DEFINE VARIABLE lStatus AS LOGICAL NO-UNDO. 
DEFINE VARIABLE cSocketString AS CHARACTER NO-UNDO. 
DEFINE VARIABLE cHost AS CHARACTER NO-UNDO INITIAL "nfenisseihl.e-datacenter.nddigital.com.br". 
DEFINE VARIABLE cProtocols AS CHARACTER NO-UNDO INITIAL "TLSv1".
DEFINE VARIABLE cCiphers AS CHARACTER NO-UNDO INITIAL "AES128-SHA,RC4-SHA,DES-CBC3-SHA,DES-CBC-SHA,EXP-DES-CBC-SHA,EXP-RC4-MD5".

ASSIGN cSocketString = "-H " + cHost + " -S " + cPort + " -ssl -sslprotocols " + cProtocols + " -sslciphers " + cCiphers. 

CREATE SOCKET hSocket. 
ASSIGN lStatus = hSocket:CONNECT(cSocketString) NO-ERROR. 

IF lStatus THEN 
MESSAGE "Socket connection OK!" VIEW-AS ALERT-BOX. 
ELSE 
MESSAGE "Socket connection FAILED!" SKIP ERROR-STATUS:GET-MESSAGE(1) VIEW-AS ALERT-BOX. 

hSocket:DISCONNECT() NO-ERROR. 

DELETE OBJECT hSocket.