/* Rela‡Æo das filiais migradas para a nuvem - NDD */               
                                  
            /*   IF estabelec.cod-estabel = "000000" THEN  */
                                  
				IF estabelec.cod-estabel = "001"
				OR estabelec.cod-estabel = "002"
				OR estabelec.cod-estabel = "005" 
				OR estabelec.cod-estabel = "008" 
				OR estabelec.cod-estabel = "010" 
				OR estabelec.cod-estabel = "014" 
				OR estabelec.cod-estabel = "015" 
				OR estabelec.cod-estabel = "030" 
				OR estabelec.cod-estabel = "036"
				OR estabelec.cod-estabel = "044" 
				OR estabelec.cod-estabel = "087" 
				OR estabelec.cod-estabel = "099"
				OR estabelec.cod-estabel = "106"
				OR estabelec.cod-estabel = "111" 
				OR estabelec.cod-estabel = "132"
				OR estabelec.cod-estabel = "134"
				OR estabelec.cod-estabel = "157"
				OR estabelec.cod-estabel = "167"
				OR estabelec.cod-estabel = "170"
				OR estabelec.cod-estabel = "194"
				OR estabelec.cod-estabel = "259"
				OR estabelec.cod-estabel = "271"
				OR estabelec.cod-estabel = "283"
				OR estabelec.cod-estabel = "310"
				OR estabelec.cod-estabel = "311"
				OR estabelec.cod-estabel = "004"
				OR estabelec.cod-estabel = "011" 
				OR estabelec.cod-estabel = "018" 
				OR estabelec.cod-estabel = "031"
				OR estabelec.cod-estabel = "040"  
				OR estabelec.cod-estabel = "061"
				OR estabelec.cod-estabel = "062"
				OR estabelec.cod-estabel = "074"
				OR estabelec.cod-estabel = "105"
				OR estabelec.cod-estabel = "109"
				OR estabelec.cod-estabel = "112" 
				OR estabelec.cod-estabel = "126"
				OR estabelec.cod-estabel = "127"
				OR estabelec.cod-estabel = "140"
				OR estabelec.cod-estabel = "213"
				OR estabelec.cod-estabel = "279"
				OR estabelec.cod-estabel = "284"
				OR estabelec.cod-estabel = "292"
				OR estabelec.cod-estabel = "313"  

                /* Bloco 2 - 19/03/2018 */
  		       OR estabelec.cod-estabel = "006" 
               OR estabelec.cod-estabel = "020" 
               OR estabelec.cod-estabel = "021" 
               OR estabelec.cod-estabel = "022" 
               OR estabelec.cod-estabel = "026" 
               OR estabelec.cod-estabel = "032" 
               OR estabelec.cod-estabel = "051" 
               OR estabelec.cod-estabel = "052" 
               OR estabelec.cod-estabel = "058"                
               OR estabelec.cod-estabel = "066" 
               OR estabelec.cod-estabel = "100"                 
               OR estabelec.cod-estabel = "115"                 
               OR estabelec.cod-estabel = "181" 
               OR estabelec.cod-estabel = "215"                
               OR estabelec.cod-estabel = "234" 
               OR estabelec.cod-estabel = "239"
               OR estabelec.cod-estabel = "269"          
               OR estabelec.cod-estabel = "275" 
               OR estabelec.cod-estabel = "294"
               OR estabelec.cod-estabel = "300"
               OR estabelec.cod-estabel = "042"
               OR estabelec.cod-estabel = "104"
               OR estabelec.cod-estabel = "117"
               OR estabelec.cod-estabel = "138"
               OR estabelec.cod-estabel = "142"
               OR estabelec.cod-estabel = "145"
               OR estabelec.cod-estabel = "151"
               OR estabelec.cod-estabel = "154"
               OR estabelec.cod-estabel = "156"                    
               OR estabelec.cod-estabel = "163"
               OR estabelec.cod-estabel = "198"
               OR estabelec.cod-estabel = "200"
               OR estabelec.cod-estabel = "201" 
               OR estabelec.cod-estabel = "208" 
               OR estabelec.cod-estabel = "211" 
               OR estabelec.cod-estabel = "217" 
               OR estabelec.cod-estabel = "218" 
               OR estabelec.cod-estabel = "241" 
               OR estabelec.cod-estabel = "244" 
               OR estabelec.cod-estabel = "252" 
               OR estabelec.cod-estabel = "286" 
               OR estabelec.cod-estabel = "296" 
               OR estabelec.cod-estabel = "308" 
               OR estabelec.cod-estabel = "320" 

                /*Entrada em 09/04 */

              OR estabelec.cod-estabel = "003" 
              OR estabelec.cod-estabel = "035" 
              OR estabelec.cod-estabel = "037" 
              OR estabelec.cod-estabel = "039" 
              OR estabelec.cod-estabel = "053" 
              OR estabelec.cod-estabel = "054" 
              OR estabelec.cod-estabel = "055" 
              OR estabelec.cod-estabel = "069" 
              OR estabelec.cod-estabel = "073" 
              OR estabelec.cod-estabel = "075" 
              OR estabelec.cod-estabel = "088" 
              OR estabelec.cod-estabel = "096" 
              OR estabelec.cod-estabel = "116" 
              OR estabelec.cod-estabel = "118" 
              OR estabelec.cod-estabel = "125" 
              OR estabelec.cod-estabel = "128" 
              OR estabelec.cod-estabel = "133" 
              OR estabelec.cod-estabel = "143" 
              OR estabelec.cod-estabel = "186" 
              OR estabelec.cod-estabel = "219" 
              OR estabelec.cod-estabel = "258" 
              OR estabelec.cod-estabel = "278" 
              OR estabelec.cod-estabel = "285" 
              OR estabelec.cod-estabel = "293" 
              OR estabelec.cod-estabel = "017" 
              OR estabelec.cod-estabel = "023" 
              OR estabelec.cod-estabel = "027" 
              OR estabelec.cod-estabel = "033" 
              OR estabelec.cod-estabel = "045" 
              OR estabelec.cod-estabel = "047" 
              OR estabelec.cod-estabel = "063" 
              OR estabelec.cod-estabel = "089" 
              OR estabelec.cod-estabel = "092" 
              OR estabelec.cod-estabel = "108" 
              OR estabelec.cod-estabel = "113" 
              OR estabelec.cod-estabel = "123" 
              OR estabelec.cod-estabel = "139" 
              OR estabelec.cod-estabel = "141" 
              OR estabelec.cod-estabel = "168" 
              OR estabelec.cod-estabel = "176" 
              OR estabelec.cod-estabel = "177" 
              OR estabelec.cod-estabel = "184" 
              OR estabelec.cod-estabel = "190" 
              OR estabelec.cod-estabel = "191" 
              OR estabelec.cod-estabel = "216" 
              OR estabelec.cod-estabel = "272" 
              OR estabelec.cod-estabel = "297" 


            /* Lojas com entrada em 16/04*/

            OR estabelec.cod-estabel = "68"
            OR estabelec.cod-estabel = "70"
            OR estabelec.cod-estabel = "71"
            OR estabelec.cod-estabel = "72"
            OR estabelec.cod-estabel = "77"
            OR estabelec.cod-estabel = "84"
            OR estabelec.cod-estabel = "85"
            OR estabelec.cod-estabel = "97"
            OR estabelec.cod-estabel = "101"
            OR estabelec.cod-estabel = "144"
            OR estabelec.cod-estabel = "152"
            OR estabelec.cod-estabel = "179"
            OR estabelec.cod-estabel = "220"
            OR estabelec.cod-estabel = "280"
            OR estabelec.cod-estabel = "281"
            OR estabelec.cod-estabel = "301"
            OR estabelec.cod-estabel = "302"
            OR estabelec.cod-estabel = "306"
            OR estabelec.cod-estabel = "307"
            OR estabelec.cod-estabel = "309"
            OR estabelec.cod-estabel = "316"
            OR estabelec.cod-estabel = "322"
            OR estabelec.cod-estabel = "79"
            OR estabelec.cod-estabel = "80"
            OR estabelec.cod-estabel = "82"
            OR estabelec.cod-estabel = "86"
            OR estabelec.cod-estabel = "90"
            OR estabelec.cod-estabel = "98"
            OR estabelec.cod-estabel = "119"
            OR estabelec.cod-estabel = "149"
            OR estabelec.cod-estabel = "197"
            OR estabelec.cod-estabel = "212"
            OR estabelec.cod-estabel = "221"
            OR estabelec.cod-estabel = "236"
            OR estabelec.cod-estabel = "237"
            OR estabelec.cod-estabel = "238"
            OR estabelec.cod-estabel = "248"
            OR estabelec.cod-estabel = "263"
            OR estabelec.cod-estabel = "282"
            OR estabelec.cod-estabel = "290"
            OR estabelec.cod-estabel = "295"
            OR estabelec.cod-estabel = "299"
            OR estabelec.cod-estabel = "303"
            OR estabelec.cod-estabel = "305"
            OR estabelec.cod-estabel = "314"
            OR estabelec.cod-estabel = "317"
            OR estabelec.cod-estabel = "319"

            /* Lojas com entrada em 23/04*/

            OR estabelec.cod-estabel = "25"
            OR estabelec.cod-estabel = "29"
            OR estabelec.cod-estabel = "34"
            OR estabelec.cod-estabel = "59"
            OR estabelec.cod-estabel = "67"
            OR estabelec.cod-estabel = "121"
            OR estabelec.cod-estabel = "161"
            OR estabelec.cod-estabel = "274"
            OR estabelec.cod-estabel = "276"
            OR estabelec.cod-estabel = "64"
            OR estabelec.cod-estabel = "165"
            OR estabelec.cod-estabel = "185"
            OR estabelec.cod-estabel = "187"
            OR estabelec.cod-estabel = "206"
            OR estabelec.cod-estabel = "222"
            OR estabelec.cod-estabel = "223"
            OR estabelec.cod-estabel = "228"
            OR estabelec.cod-estabel = "229"
            OR estabelec.cod-estabel = "242"
            OR estabelec.cod-estabel = "245"
            OR estabelec.cod-estabel = "246"
            OR estabelec.cod-estabel = "249"
            OR estabelec.cod-estabel = "260"
            OR estabelec.cod-estabel = "261"
            OR estabelec.cod-estabel = "262"
            OR estabelec.cod-estabel = "267"
            OR estabelec.cod-estabel = "76"
            OR estabelec.cod-estabel = "150"
            OR estabelec.cod-estabel = "155"
            OR estabelec.cod-estabel = "180"
            OR estabelec.cod-estabel = "192"
            OR estabelec.cod-estabel = "193"
            OR estabelec.cod-estabel = "204"
            OR estabelec.cod-estabel = "207"
            OR estabelec.cod-estabel = "209"
            OR estabelec.cod-estabel = "210"
            OR estabelec.cod-estabel = "224"
            OR estabelec.cod-estabel = "225"
            OR estabelec.cod-estabel = "254"

             /* Lojas com entrada em 07/05 */

            OR estabelec.cod-estabel = "7"
            OR estabelec.cod-estabel = "28"
            OR estabelec.cod-estabel = "46"
            OR estabelec.cod-estabel = "93"
            OR estabelec.cod-estabel = "103"
            OR estabelec.cod-estabel = "110"
            OR estabelec.cod-estabel = "129"
            OR estabelec.cod-estabel = "130"
            OR estabelec.cod-estabel = "182"
            OR estabelec.cod-estabel = "188"
            OR estabelec.cod-estabel = "120"
            OR estabelec.cod-estabel = "195"
            OR estabelec.cod-estabel = "232"
            OR estabelec.cod-estabel = "235"
            OR estabelec.cod-estabel = "91"
            OR estabelec.cod-estabel = "173"
            OR estabelec.cod-estabel = "298"
            OR estabelec.cod-estabel = "318"
            OR estabelec.cod-estabel = "13"
            OR estabelec.cod-estabel = "24"
            OR estabelec.cod-estabel = "148"
            OR estabelec.cod-estabel = "169"
            OR estabelec.cod-estabel = "172"
            OR estabelec.cod-estabel = "233"
            OR estabelec.cod-estabel = "48"
            OR estabelec.cod-estabel = "49"
            OR estabelec.cod-estabel = "50"
            OR estabelec.cod-estabel = "56"
            OR estabelec.cod-estabel = "65"
            OR estabelec.cod-estabel = "160"
            OR estabelec.cod-estabel = "270"


			   THEN

































