/*recompila‡Æo*/
DEF STREAM sLog.

DEFINE VARIABLE ldebug AS LOGICAL     NO-UNDO INIT NO.

DEFINE VARIABLE cArqLog AS CHARACTER   NO-UNDO.

lDebug = YES.

PROCEDURE abrirLog:
DEFINE INPUT  PARAMETER pcArqLog    AS CHARACTER   NO-UNDO.

    IF NOT lDebug THEN 
        RETURN.

    OUTPUT STREAM sLog TO VALUE(pcArqLog).
    OUTPUT STREAM sLog CLOSE.

    cArqLog = pcArqLog.

END PROCEDURE.

PROCEDURE gerarLog:
DEFINE INPUT  PARAMETER pcLog AS CHARACTER   NO-UNDO.

    IF NOT lDebug THEN 
        RETURN.

    RUN gerarLogArquivo(cArqLog, pcLog).

END PROCEDURE.


PROCEDURE gerarLogArquivo:
DEFINE INPUT  PARAMETER pcArqLog    AS CHARACTER   NO-UNDO.
DEFINE INPUT  PARAMETER pcLog AS CHARACTER   NO-UNDO.

    OUTPUT STREAM sLog TO VALUE(pcArqLog) APPEND.
    PUT STREAM sLog UNFORMAT "[" STRING(TODAY, "99/99/9999") "-" STRING(TIME, "HH:MM:SS") "] " pcLog SKIP.
    OUTPUT STREAM sLog CLOSE.

END PROCEDURE.

PROCEDURE gerarDebug:
DEFINE INPUT  PARAMETER pcArqLog    AS CHARACTER   NO-UNDO.
DEFINE INPUT  PARAMETER pcLog AS CHARACTER   NO-UNDO.

    IF NOT lDebug THEN RETURN.

    OUTPUT STREAM sLog TO VALUE(pcArqLog) APPEND.
    PUT STREAM sLog UNFORMAT "[" STRING(TODAY, "99/99/9999") "-" STRING(TIME, "HH:MM:SS") "] " pcLog SKIP.
    OUTPUT STREAM sLog CLOSE.

END PROCEDURE.

