/*IMPLEMENTATION FOR ADAPTERS PROGRESS API: 
 *
 *THIS CODE WAS GENERATED BY
 *  -Datasul Finance Adapters Generator - v0.09
 *  -5/12/2008 - 15:56
 *
 *DO NOT MODIFY THIS SOURCE CODE. IT IS MAINTAINED BY THE ADAPTERS MODEL
 *
 **/


{include/i_dbinst.i}
{include/i_dbtype.i}

/* DEFINICAO DE PRE-PROCESSADORES - BEGIN */
&GLOBAL-DEFINE XmlApp            CT5
&GLOBAL-DEFINE XmlMod            FGL
&GLOBAL-DEFINE XmlProdName       EMS5
&GLOBAL-DEFINE XmlProdVersion    506
&GLOBAL-DEFINE XmlTranName       FGLTransactionEMS5
&GLOBAL-DEFINE XmlMinTranVersion 506.001
&GLOBAL-DEFINE XmlMaxTranVersion 506.999
&GLOBAL-DEFINE XmlListOfAction   add,upd,del

/* DEFINICAO DE PRE-PROCESSADORES - END */

/*LOCAL VARIABLES - BEGIN*/
DEFINE VAR cReturnValue AS CHARACTER INITIAL ? NO-UNDO.
DEFINE VAR cTranAction AS CHARACTER INITIAL ? NO-UNDO.
DEFINE VAR cTranEvent AS CHARACTER INITIAL ? NO-UNDO.
DEFINE VAR cTranVersion AS CHARACTER INITIAL ? NO-UNDO.
DEFINE VAR hBusinessContent AS HANDLE NO-UNDO.
DEFINE VAR hGenXml AS HANDLE NO-UNDO.
DEFINE VAR hMessageHandler AS HANDLE NO-UNDO.
DEFINE VAR lSuccessProcess AS LOGICAL INITIAL ? NO-UNDO.

DEFINE TEMP-TABLE tt_log_erro NO-UNDO
     FIELD ttv_num_cod_erro AS integer INITIAL ?
     FIELD ttv_des_msg_ajuda AS character INITIAL ?
     FIELD ttv_des_msg_erro AS character INITIAL ?
.


DEFINE TEMP-TABLE ttBranchRestrictionInform_00 NO-UNDO
     FIELD BranchCode AS CHARACTER INITIAL ?  /*C¢digo dao estabelecimento (Uso interno: cod_estabel ou cdn-estabe)*/
     FIELD BranchDescription AS CHARACTER INITIAL ?  /*Raz∆o Social do estabelecimento (Uso interno: des_empresa)*/
     FIELD ttBranchRestrictionInform_00ID AS INTEGER INITIAL ?
     FIELD ttPostingItemID AS INTEGER INITIAL ?
.


DEFINE TEMP-TABLE ttBusinessUnitUseInformation NO-UNDO
     FIELD BusinessUnitCode AS CHARACTER INITIAL ?  /*C¢digo da unidade de neg¢cio (Uso interno: campo = emsuni.unid_negoc.cod_unid_negoc)*/
     FIELD BusinessUnitDescription AS CHARACTER INITIAL ?  /*Descriá∆o da unidade de neg¢cio (Uso interno: campo = emsuni.unid_negoc.des_unid_negoc)*/
     FIELD BusinessUnitId AS integer INITIAL ?  /*Identificador do n°vel da unidade organizacional.*/
     FIELD ttBusinessUnitUseInformationID AS INTEGER INITIAL ?
     FIELD ttPostingItemID AS INTEGER INITIAL ?
.


DEFINE TEMP-TABLE ttGLBatchInformation NO-UNDO
     FIELD BatchComplementaryDescription AS CHARACTER INITIAL ?  /*Descriá∆o Complemntar do lote (des-compl-seq-tab)*/
     FIELD BatchExchangeDate AS date INITIAL ?  /*Data da cotaá∆o do indicador econìmico (dat-cotac-moeda)*/
     FIELD BatchValue AS DECIMAL INITIAL ?  /*Valor do lote cont†bil (val-movto)*/
     FIELD CancelledDate AS date INITIAL ?  /*Data do cancelamento ou estorno (dat-estorn-ctbl)*/
     FIELD CompanyCode AS CHARACTER INITIAL ?  /*C¢digo da empresa (Uso interno: cod_empresa ou ep-codigo)*/
     FIELD CompanyDescription AS CHARACTER INITIAL ?  /*Raz∆o Social da Empresa (Uso interno: des_empresa ou razao-social)*/
     FIELD CompanyID AS CHARACTER INITIAL ?  /*Identificaá∆o de Empresa*/
     FIELD Domain AS CHARACTER INITIAL ?  /*Descriá∆o do tipo de identificaá∆o da empresa*/
     FIELD GLBatchDate AS date INITIAL ?  /*Data do lote cont†bil (dat_lote_ctbl )*/
     FIELD GLBatchDescription AS CHARACTER INITIAL ?  /*Descriá∆o do lote cont†bil (des_lote_ctbl)*/
     FIELD GLBatchNumber AS integer INITIAL ?  /*N£mero do lote cont†bil (num_lote_ctbl)*/
     FIELD GLBatchStatus AS CHARACTER INITIAL ?  /*Situaá∆o do lote cont†bil (ind_sit_lote_ctbl)*/
     FIELD IsCancelled AS LOGICAL INITIAL ?  /*Identifica se o lote foi estornado ou n∆o (log_estorn_lote_ctbl ou log-gera-estorn)*/
     FIELD IsOnlineAccounting AS LOGICAL INITIAL ?  /*Identifica se o lote Ç intregado online ou n∆o (log_integr_ctbl_online)*/
     FIELD LastUpdateDate AS date INITIAL ?  /*Data da £ltima atualizaá∆o (dat_ult_atualiz)*/
     FIELD LastUpdateTime AS CHARACTER INITIAL ?  /*Hora da £ltima atualizaá∆o (hra_ult_atualiz)*/
     FIELD ModuleCode AS CHARACTER INITIAL ?  /*C¢digo do M¢dulo */
     FIELD ModuleDescription AS CHARACTER INITIAL ?  /*Descriá∆o do m¢dulo*/
     FIELD Reference AS CHARACTER INITIAL ?  /*C¢digo da referància (cod-refer)*/
     FIELD StandardHistoryCode AS CHARACTER INITIAL ?  /*C¢digo do historico padr∆o (cod_histor_padr ou cnd-histor-padr)*/
     FIELD StandardHistoryDescription AS CHARACTER INITIAL ?  /*Descriá∆o do hist¢rico padr∆o (des_histor_padr ou des-descr-gener)*/
     FIELD Translation AS CHARACTER INITIAL ?  /*Matriz de Traduá∆o da Unidade organizacional.*/
     FIELD ttGLBatchInformationID AS INTEGER INITIAL ?
     FIELD UserCode AS CHARACTER INITIAL ?  /*C¢digo do usu†rio (Uso interno: campo = cod_user)*/
     FIELD UserName AS CHARACTER INITIAL ?  /*Nome do usu†rio (Uso interno: campo = nom_user)*/
     INDEX ixttGLBatchInformationID IS PRIMARY UNIQUE ttGLBatchInformationID ASCENDING
.


DEFINE TEMP-TABLE ttGLBatchInformation_00 NO-UNDO
     FIELD GLBatchDate AS date INITIAL ?  /*Data do lote cont†bil (dat_lote_ctbl )*/
     FIELD GLBatchDescription AS CHARACTER INITIAL ?  /*Descriá∆o do lote cont†bil (des_lote_ctbl)*/
     FIELD GLBatchNumber AS integer INITIAL ?  /*N£mero do lote cont†bil (num_lote_ctbl)*/
     FIELD ModuleCode AS CHARACTER INITIAL ?  /*C¢digo do M¢dulo */
     FIELD ModuleDescription AS CHARACTER INITIAL ?  /*Descriá∆o do m¢dulo*/
     FIELD ttGLBatchInformation_00ID AS INTEGER INITIAL ?
     INDEX ixttGLBatchInformation_00ID IS PRIMARY UNIQUE ttGLBatchInformation_00ID ASCENDING
.


DEFINE TEMP-TABLE ttPosting NO-UNDO
     FIELD CancelledBatchNumber AS integer INITIAL ?  /*Numero o lote de estorno (num_lote_estordo)*/
     FIELD CancelledPostingNumber AS integer INITIAL ?  /*N£mero do lanáamento de estorno (num_lancto_estordo)*/
     FIELD IsConversionPosting AS LOGICAL INITIAL ?  /*Identifica se o lancamento Ç de convers∆o ou n∆o (log_lancto_conver)*/
     FIELD IsResultVariancePosting AS LOGICAL INITIAL ?  /*Identifica se o lanáamento  Ç de apuraá∆o de variaá∆o de resultado (log_lancto_apurac_variac)*/
     FIELD IsUpdatedBalanceBatch AS LOGICAL INITIAL ?  /*Identifica se o saldo Ç atualizado de forma batch ou on-line (log_sdo_batch_atlzdo)*/
     FIELD OriginBatchNumber AS integer INITIAL ?  /*N£mero do lote original, esta informaá∆o existira caso tenha ocorrido c¢pia do lote (num_lote_ctbl_orig_cop)*/
     FIELD OriginPostingNumber AS integer INITIAL ?  /*N£mero do lanáamento cont†bil original, esta informaá∆o existir† caso tenha ocorrido c¢pia do lanáamento (num_lancto_ctbl_orig_cop)*/
     FIELD PostingDate AS date INITIAL ?  /*Data do lanáamento cont†bil (dat_lancto_ctbl ou dat-movto)*/
     FIELD PostingNumber AS integer INITIAL ?  /*Identificador do lanáamento cont†bil (num_lancto_ctb ou num-seql)*/
     FIELD PostingType AS CHARACTER INITIAL ?  /*Tipo do lanáamento cont†bil (ind_tip_lancto)*/
     FIELD ProRataCode AS CHARACTER INITIAL ?  /*C¢digo do rateio cont†bil*/
     FIELD ProRataDescription AS CHARACTER INITIAL ?  /*Descriá∆o do rateio cont†bil*/
     FIELD ScenarioCode AS CHARACTER INITIAL ?  /*C¢digo do Cen†rio Cont†bil (cod_cenar_ctbl)*/
     FIELD ScenarioDescription AS CHARACTER INITIAL ?  /*Descriá∆o do Cen†rio cont†bil (des_cenar_ctbl)*/
     FIELD StandardHistoryCode AS CHARACTER INITIAL ?  /*C¢digo do historico padr∆o (cod_histor_padr ou cnd-histor-padr)*/
     FIELD StandardHistoryDescription AS CHARACTER INITIAL ?  /*Descriá∆o do hist¢rico padr∆o (des_histor_padr ou des-descr-gener)*/
     FIELD StandardPostingCode AS CHARACTER INITIAL ?  /*C¢digo do Lanáamento padr∆o (cod_lancto_ctbl_padr ou cdn-lancto-padr)*/
     FIELD StandardPostingDescription AS CHARACTER INITIAL ?  /*Descriá∆o do lanáamento padr∆o (des_lancto_ctbl_padr ou des-descr-gener)*/
     FIELD ttGLBatchInformationID AS INTEGER INITIAL ?
     FIELD ttPostingID AS INTEGER INITIAL ?
     INDEX ixttPostingID IS PRIMARY UNIQUE ttPostingID ASCENDING
.


DEFINE TEMP-TABLE ttPosting_00 NO-UNDO
     FIELD PostingDate AS date INITIAL ?  /*Data do lanáamento cont†bil (dat_lancto_ctbl ou dat-movto)*/
     FIELD PostingNumber AS integer INITIAL ?  /*Identificador do lanáamento cont†bil (num_lancto_ctb ou num-seql)*/
     FIELD ttGLBatchInformation_00ID AS INTEGER INITIAL ?
     FIELD ttPosting_00ID AS INTEGER INITIAL ?
     INDEX ixttPosting_00ID IS PRIMARY UNIQUE ttPosting_00ID ASCENDING
.


DEFINE TEMP-TABLE ttPostingAppropriation NO-UNDO
     FIELD CurrencyCode AS CHARACTER INITIAL ?  /*C¢digo do indicador econìmido ou moeda (Uso interno: campo = mguni.moeda.mo-codigo ou emsuni.indic_econ.cod_indic_econ)*/
     FIELD CurrencyDescription AS CHARACTER INITIAL ?  /*Descriá∆o do indicador econìmico ou moeda (Uso interno: campo = mguni.moeda.descricao ou emsuni.indic_econ.des_indic_econ)*/
     FIELD ExchangeDate AS date INITIAL ?  /*Data da cotaá∆o do indicador econìmico (dat_cotac_indic_econ)*/
     FIELD ExchangeValue AS decimal INITIAL ?  /*Valor da cotaá∆o do indicador econìmico (val_cotac_indic_econ)*/
     FIELD OriginValuePosting AS CHARACTER INITIAL ?  /*Identifica como o valor do lanáamento cont†bil foi originado (ind_orig_val_lancto_ctbl)*/
     FIELD PostingAppropriationSequence AS integer INITIAL ?  /*Sequencial da apropriaá‰es do lanáamento cont†bil (num_id_aprop_lancto_ctbl)*/
     FIELD PostingAppropriationValue AS decimal INITIAL ?  /*valor da apropriaá∆o cont†bil (val_lancto_ctbl)*/
     FIELD ttPostingAppropriationID AS INTEGER INITIAL ?
     FIELD ttPostingItemID AS INTEGER INITIAL ?
.


DEFINE TEMP-TABLE ttPostingAppropriation_00 NO-UNDO
     FIELD PostingAppropriationSequence AS integer INITIAL ?  /*Sequencial da apropriaá‰es do lanáamento cont†bil (num_id_aprop_lancto_ctbl)*/
     FIELD ttPostingAppropriation_00ID AS INTEGER INITIAL ?
     FIELD ttPostingItem_00ID AS INTEGER INITIAL ?
.


DEFINE TEMP-TABLE ttPostingItem NO-UNDO
     FIELD AccountCode AS CHARACTER INITIAL ?  /*C¢digo da conta cont†bil (Uso interno: campo = cod_cta_ctbl ou ct-codigo)*/
     FIELD AccountCode_00 AS CHARACTER INITIAL ?  /*C¢digo da conta cont†bil (Uso interno: campo = cod_cta_ctbl ou ct-codigo)*/
     FIELD AccountDescription AS CHARACTER INITIAL ?  /*Descriá∆o da conta cont†bil (Uso interno: campo = emsuni.cta_ctbl.des_tit_ctbl ou mgadm.conta.titulo)*/
     FIELD AccountDescription_00 AS CHARACTER INITIAL ?  /*Descriá∆o da conta cont†bil (Uso interno: campo = emsuni.cta_ctbl.des_tit_ctbl ou mgadm.conta.titulo)*/
     FIELD AccountPlanCode AS CHARACTER INITIAL ?  /*C¢digo do Plano de Conta cont†bil (Uso interno: campo = cod_plan_cta_ctbl)*/
     FIELD AccountPlanCode_00 AS CHARACTER INITIAL ?  /*C¢digo do Plano de Conta cont†bil (Uso interno: campo = cod_plan_cta_ctbl)*/
     FIELD AccountPlanDescription AS CHARACTER INITIAL ?  /*Descriá∆o do plano de contas cont†bil (Uso interno: campo =des_plan_cta_ctbl)*/
     FIELD AccountPlanDescription_00 AS CHARACTER INITIAL ?  /*Descriá∆o do plano de contas cont†bil (Uso interno: campo =des_plan_cta_ctbl)*/
     FIELD AlternateAccountCode AS CHARACTER INITIAL ?  /*C¢digo da conta alternativa*/
     FIELD AlternateAccountCode_00 AS CHARACTER INITIAL ?  /*C¢digo da conta alternativa*/
     FIELD BranchCode AS CHARACTER INITIAL ?  /*C¢digo dao estabelecimento (Uso interno: cod_estabel ou cdn-estabe)*/
     FIELD BranchDescription AS CHARACTER INITIAL ?  /*Raz∆o Social do estabelecimento (Uso interno: des_empresa)*/
     FIELD BusinessUnitCode AS CHARACTER INITIAL ?  /*C¢digo da unidade de neg¢cio (Uso interno: campo = emsuni.unid_negoc.cod_unid_negoc)*/
     FIELD BusinessUnitDescription AS CHARACTER INITIAL ?  /*Descriá∆o da unidade de neg¢cio (Uso interno: campo = emsuni.unid_negoc.des_unid_negoc)*/
     FIELD BusinessUnitId AS integer INITIAL ?  /*Identificador do n°vel da unidade organizacional.*/
     FIELD ContraparterPostingSequenceNu_00 AS integer INITIAL ?  /*N£mero do lanáamento de contra partida (num_seq_lancto_ctbl_cpart)*/
     FIELD CostCenterCode AS CHARACTER INITIAL ?  /*C¢digo do Centro de Custo (Uso interno: campo=emsuni.ccusto.cod_ccusto ou mgadm.sub-conta.sc-codigo)*/
     FIELD CostCenterDescription AS CHARACTER INITIAL ?  /*Desriá∆o do Centro de Custo (Uso interno: campo=emsuni.ccusto.des_tit_ctbl ou mgadm.sub-conta.descricao)*/
     FIELD CostCenterPlanCode AS CHARACTER INITIAL ?  /*C¢digo do Plano de Centro de Custo (Uso interno: campo=emsuni.ccusto.cod_plano_ccusto)*/
     FIELD CostCenterPlanDescription AS CHARACTER INITIAL ?  /*Descriá∆o do Plano de Centro de Custo (Uso interno: campo=emsuni.plano_ccusto.des_tit_ctbl)*/
     FIELD CurrencyCode AS CHARACTER INITIAL ?  /*C¢digo do indicador econìmido ou moeda (Uso interno: campo = mguni.moeda.mo-codigo ou emsuni.indic_econ.cod_indic_econ)*/
     FIELD CurrencyDescription AS CHARACTER INITIAL ?  /*Descriá∆o do indicador econìmico ou moeda (Uso interno: campo = mguni.moeda.descricao ou emsuni.indic_econ.des_indic_econ)*/
     FIELD DocumentClassCode AS CHARACTER INITIAL ?  /*C¢digo da espÇcie de documento*/
     FIELD DocumentClassDescription AS CHARACTER INITIAL ?  /*Descriá∆o da espÇcie do documento*/
     FIELD DocumentDate AS date INITIAL ?  /*Data do documento (dat_docto)*/
     FIELD DocumentNumber AS CHARACTER INITIAL ?  /*N£mero do documento (des_docto)*/
     FIELD EntryNumber AS CHARACTER INITIAL ?  /*N£mero do documetno de entrada (val_seq_entry_number)*/
     FIELD FinancialProjectCode AS CHARACTER INITIAL ?  /*C¢digo do projeto financeiro*/
     FIELD FinancialProjectDescription AS CHARACTER INITIAL ?  /*Descriá∆o do projeto financeiro*/
     FIELD FinancialProjectExternalCode AS CHARACTER INITIAL ?  /*C¢digo externo do projeto financeiro.*/
     FIELD ImageCode AS CHARACTER INITIAL ?  /*C¢digo da Imagem*/
     FIELD ImageDescription AS CHARACTER INITIAL ?  /*Descriá∆o da imagem*/
     FIELD InternationalStandardAccountC_00 AS CHARACTER INITIAL ?  /*C¢digo Internacional da conta cont†bil*/
     FIELD InternationalStandardAccountCode AS CHARACTER INITIAL ?  /*C¢digo Internacional da conta cont†bil*/
     FIELD IsResultRaisePosting AS LOGICAL INITIAL ?  /*Identifica se o item Ç referente a apuraá∆o de resultados. (log_lancto_apurac_restdo)*/
     FIELD PostingDetail AS CHARACTER INITIAL ?  /*Detalhe da geraá∆o do lanáamento cont†bil (des_descr_gener ou des-compl-seq-tab)*/
     FIELD PostingItemDate AS date INITIAL ?  /*Data do item do lanáamento. (dat_lancto_ctbl)*/
     FIELD PostingItemExchangeDate AS date INITIAL ?  /*Data da cotaá∆o (dat-cotac-moed)*/
     FIELD PostingItemPercentage AS decimal INITIAL ?  /*Percentual do item do lanáamento cont†bil (val_perc)*/
     FIELD PostingItemPresentValue AS DECIMAL INITIAL ?  /*Valor presente do item do item (val-pres-tit) */
     FIELD PostingItemQuantity AS decimal INITIAL ?  /*N£mero de lanáamentos (qtd_unid_lancto_ctbl)*/
     FIELD PostingItemSequenceNumber AS integer INITIAL ?  /*Sequencial do item do lanáamento cont†bil (num_seq_lancto_ctbl ou num-seq)*/
     FIELD PostingItemTypeCode AS CHARACTER INITIAL ?  /*Tipo do lanáamento cont†bil (cod_tip_lancto_ctbl)*/
     FIELD PostingItemValue AS decimal INITIAL ?  /*Valor do lanáamento cont†bil (val_lancto_ctbl ou val-lancto-ctbl)*/
     FIELD PostingItemValueCMCAC AS DECIMAL INITIAL ?  /*Valor do Item para CMCAC (val-cmi)*/
     FIELD PostingItemValueFASB AS DECIMAL INITIAL ?  /*Valor do item do lanáamento cont†bil FASB (val-fasb) */
     FIELD PostingNature AS integer INITIAL ?  /*Identifica o tipo do lanáamento cont†bil (ind_natur_lancto_ctbl ou cdn-trans. Valores Possiveis: 1 - Debito, 2 - Credito, 3 - Partida Dobrada)*/
     FIELD ReducedAccountCode AS integer INITIAL ?  /*C¢digo da conta Reduzida (Uso interno: campo = cnd-cta-reduz)*/
     FIELD ReducedAccountCode_00 AS integer INITIAL ?  /*C¢digo da conta Reduzida (Uso interno: campo = cnd-cta-reduz)*/
     FIELD ScenarioCode AS CHARACTER INITIAL ?  /*C¢digo do Cen†rio Cont†bil (cod_cenar_ctbl)*/
     FIELD ScenarioDescription AS CHARACTER INITIAL ?  /*Descriá∆o do Cen†rio cont†bil (des_cenar_ctbl)*/
     FIELD StandardHistoryCode AS CHARACTER INITIAL ?  /*C¢digo do historico padr∆o (cod_histor_padr ou cnd-histor-padr)*/
     FIELD StandardHistoryDescription AS CHARACTER INITIAL ?  /*Descriá∆o do hist¢rico padr∆o (des_histor_padr ou des-descr-gener)*/
     FIELD SubAccountCode AS CHARACTER INITIAL ?  /*C¢digo da subconta cont†bil (Uso interno: campo = cod-subconta-ctbl ou sc-codigo)*/
     FIELD SubAccountCode_00 AS CHARACTER INITIAL ?  /*C¢digo da subconta cont†bil (Uso interno: campo = cod-subconta-ctbl ou sc-codigo)*/
     FIELD ttPostingID AS INTEGER INITIAL ?
     FIELD ttPostingItemID AS INTEGER INITIAL ?
     FIELD UserCode AS CHARACTER INITIAL ?  /*C¢digo do usu†rio (Uso interno: campo = cod_user)*/
     FIELD UserName AS CHARACTER INITIAL ?  /*Nome do usu†rio (Uso interno: campo = nom_user)*/
     FIELD ValidityEnd AS date INITIAL ?  /*Data de Fim de Validade (emsuni.ccusto.dat_fim_valid)*/
     FIELD ValidityStart AS date INITIAL ?  /*Data de In°cio da Validade (emsuni.ccusto.dat_inic_valid)*/
     INDEX ixttPostingItemID IS PRIMARY UNIQUE ttPostingItemID ASCENDING
.


DEFINE TEMP-TABLE ttPostingItem_00 NO-UNDO
     FIELD PostingItemSequenceNumber AS integer INITIAL ?  /*Sequencial do item do lanáamento cont†bil (num_seq_lancto_ctbl ou num-seq)*/
     FIELD ttPosting_00ID AS INTEGER INITIAL ?
     FIELD ttPostingItem_00ID AS INTEGER INITIAL ?
     INDEX ixttPostingItem_00ID IS PRIMARY UNIQUE ttPostingItem_00ID ASCENDING
.


DEFINE TEMP-TABLE ttSecurityInformation NO-UNDO
     FIELD ttPostingItemID AS INTEGER INITIAL ?
     FIELD ttSecurityInformationID AS INTEGER INITIAL ?
     FIELD UserGroupCode AS CHARACTER INITIAL ?  /*C¢digo do grupo usu†rio (Uso interno: campo = emsuni.grp_usuar.cod_grp_usuar)*/
     FIELD UserGroupDescription AS CHARACTER INITIAL ?  /*Descriá∆o do Grupo de Usu†rios (Uso interno: campo = emsuni.grp_usuar.des_grp_usuar)*/
.

/*LOCAL VARIABLES - END*/

/*PARAMETERS - BEGIN*/
/*PARAMETERS - END*/




{adapters\xml\ct5\axrct025ExtraDeclarations.i}




/* DEF. VARIµVEIS USADAS EM xmlLoadMessageHandlerRec.i */
{xmlinc/xmlLoadMessageHandlerRecDef.i}

/* DEFINE AS VARAIVEIS PARA USO DO xmlLoadGenXmlRec.i */
{xmlinc/xmlLoadGenXmlRecDef.i}


/* DEFINE AS VARIAVEIS PARA USO DO xmlgettranssubsinfo */
{xmlinc/xmlgettranssubsinfo.i}

DEFINE TEMP-TABLE ttStack NO-UNDO
     FIELD ttID AS INTEGER
     FIELD ttPos AS INTEGER
     INDEX tt_id IS PRIMARY UNIQUE
           ttID  ASCENDING.


FUNCTION addStack RETURN INTEGER (INPUT val AS INTEGER).
     DEFINE VAR id AS INTEGER INITIAL 1 NO-UNDO.
     FIND LAST ttStack NO-ERROR.
     IF AVAIL(ttStack) THEN
          id = ttStack.ttID + 1.

     CREATE ttStack.
     ASSIGN ttStack.ttID = id.
     ASSIGN ttStack.ttPos = val.
END FUNCTION.


FUNCTION delStack RETURN INTEGER.
     FIND LAST ttStack NO-ERROR.
     IF AVAIL(ttStack) THEN
          DELETE ttStack.

     FIND LAST ttStack NO-ERROR.
END FUNCTION.


FUNCTION getStack RETURN INTEGER.
     IF AVAIL(ttStack) THEN
          RETURN ttStack.ttPos.
     ELSE
          RETURN 0.
END FUNCTION.




/* Begin_Include: i_version_extract */
def new global shared var v_cod_arq as char format 'x(60)' no-undo.
def new global shared var v_cod_tip_prog as character format 'x(8)' no-undo.
def stream s-arq.

if  v_cod_arq <> '' and v_cod_arq <> ?
then do:
     run pi_version_extract ('FGLTransactionEMS5Receiver', 'adapters\xml\ct5\axrct025.p', '506.001', 'pro').
end /* if */.
/* End_Include: i_version_extract */


/****** INTERNAL PROCEDURES - BEGIN*/
PROCEDURE pi_version_extract:

/*PARAMETERS - BEGIN*/
/*PARAMETERS - END*/


/*LOCAL VARIABLES - BEGIN*/
/*LOCAL VARIABLES - END*/


/* ******************************************* */
/* *************** BODY - BEGIN ************** */
/* ******************************************* */

/************************ Parameter Definition Begin ************************/
def Input param p_cod_program as character format "x(8)" no-undo.
def Input param p_cod_program_ext as character format "x(8)" no-undo.
def Input param p_cod_version as character format "x(8)" no-undo.
def Input param p_cod_program_type as character format "x(8)" no-undo.
/************************* Parameter Definition End *************************/
if  can-do(v_cod_tip_prog, p_cod_program_type)
then do:
if p_cod_program_type = 'dic' then 
     assign p_cod_program_ext = replace(p_cod_program_ext, 'database/', '').
     output stream s-arq to value(v_cod_arq) append.

     put stream s-arq unformatted
          p_cod_program            at 1
          p_cod_program_ext        at 43
          p_cod_version            at 69
          today                    at 84
          string(time, 'HH:MM:SS') at 94 skip.

     if  p_cod_program_type = 'pro' then do:
          find prog_dtsul 
               where prog_dtsul.cod_prog_dtsul = p_cod_program 
               no-lock no-error.

          if  avail prog_dtsul
          then do:
                    if  prog_dtsul.nom_prog_dpc <> '' then
                         put stream s-arq 'DPC : ' at 5 prog_dtsul.nom_prog_dpc  at 15 skip.

               if  prog_dtsul.nom_prog_appc <> '' then
                    put stream s-arq 'APPC: ' at 5 prog_dtsul.nom_prog_appc at 15 skip.
               if  prog_dtsul.nom_prog_upc <> '' then
                    put stream s-arq 'UPC : ' at 5 prog_dtsul.nom_prog_upc  at 15 skip.
          end /* if */.
     end.



     output stream s-arq close.

end /* if */.

/* ******************************************* */
/* *************** BODY - END   ************** */
/* ******************************************* */

END PROCEDURE.


PROCEDURE PIDelete:

/*PARAMETERS - BEGIN*/
/*PARAMETERS - END*/


/*LOCAL VARIABLES - BEGIN*/
DEFINE VAR iId AS INTEGER INITIAL ? NO-UNDO.
/*LOCAL VARIABLES - END*/


/* ******************************************* */
/* *************** BODY - BEGIN ************** */
/* ******************************************* */


     /* OBTEM A PARTE DA MENSAGEM QUE ESTÊ ABAIXO DO ELEMENTO BusinessContent */
     RUN getBusinessContent IN hMessageHandler (OUTPUT hBusinessContent).

     /* LIMPA AS TEMP-TABLES INTERNAS DA API XML */
     RUN reset IN hGenXml.

     /* CARREGA A ESTRUTURA FILHA DE BusinessContent */
     RUN loadXml IN hGenXml (hBusinessContent).

     /* ELIMINA A MENSAGEM OBTIDA NO MêTODO getBusinessContent */
     DELETE OBJECT hBusinessContent NO-ERROR.

     /* ********* LEITURA DA MENSAGEM - BEGIN ********* */
     addStack(1).
          RUN searchTag IN hGenXml (INPUT "ListOfGLBatchInformation", INPUT getStack(), OUTPUT iId).
          if (iId <> ?) THEN DO:
               addStack(iId).

                    RUN getFirstSonId IN hGenXml (INPUT getStack(), OUTPUT iId).

                    DO WHILE iId <> ?:
                    addStack(iId).

                         /*Criacao de valores para manter as relacoes*/
                         CREATE ttGLBatchInformation_00.
                         ASSIGN ttGLBatchInformation_00.ttGLBatchInformation_00ID = iId.

                         RUN getSonDec IN hGenXml (INPUT getStack(), INPUT "GLBatchNumber", OUTPUT ttGLBatchInformation_00.GLBatchNumber).
                         RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "GLBatchDescription", OUTPUT ttGLBatchInformation_00.GLBatchDescription).
                         RUN searchTag IN hGenXml (INPUT "ModuleInformation", INPUT getStack(), OUTPUT iId).
                         if (iId <> ?) THEN DO:
                              addStack(iId).

                                   RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "ModuleCode", OUTPUT ttGLBatchInformation_00.ModuleCode).
                                   RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "ModuleDescription", OUTPUT ttGLBatchInformation_00.ModuleDescription).
                              delStack().
                         END.

                         RUN getSonDate IN hGenXml (INPUT getStack(), INPUT "GLBatchDate", OUTPUT ttGLBatchInformation_00.GLBatchDate).
                         RUN searchTag IN hGenXml (INPUT "ListOfPosting", INPUT getStack(), OUTPUT iId).
                         if (iId <> ?) THEN DO:
                              addStack(iId).

                                   RUN getFirstSonId IN hGenXml (INPUT getStack(), OUTPUT iId).

                                   DO WHILE iId <> ?:
                                   addStack(iId).

                                        /*Criacao de valores para manter as relacoes*/
                                        CREATE ttPosting_00.
                                        ASSIGN ttPosting_00.ttPosting_00ID = iId.
                                        ASSIGN ttPosting_00.ttGLBatchInformation_00ID = ttGLBatchInformation_00.ttGLBatchInformation_00ID.

                                        RUN getSonDec IN hGenXml (INPUT getStack(), INPUT "PostingNumber", OUTPUT ttPosting_00.PostingNumber).
                                        RUN getSonDate IN hGenXml (INPUT getStack(), INPUT "PostingDate", OUTPUT ttPosting_00.PostingDate).
                                        RUN searchTag IN hGenXml (INPUT "ListOfPostingItem", INPUT getStack(), OUTPUT iId).
                                        if (iId <> ?) THEN DO:
                                             addStack(iId).

                                                  RUN getFirstSonId IN hGenXml (INPUT getStack(), OUTPUT iId).

                                                  DO WHILE iId <> ?:
                                                  addStack(iId).

                                                       /*Criacao de valores para manter as relacoes*/
                                                       CREATE ttPostingItem_00.
                                                       ASSIGN ttPostingItem_00.ttPostingItem_00ID = iId.
                                                       ASSIGN ttPostingItem_00.ttPosting_00ID = ttPosting_00.ttPosting_00ID.

                                                       RUN getSonDec IN hGenXml (INPUT getStack(), INPUT "PostingItemSequenceNumber", OUTPUT ttPostingItem_00.PostingItemSequenceNumber).
                                                       RUN searchTag IN hGenXml (INPUT "ListOfPostingAppropriation", INPUT getStack(), OUTPUT iId).
                                                       if (iId <> ?) THEN DO:
                                                            addStack(iId).

                                                                 RUN getFirstSonId IN hGenXml (INPUT getStack(), OUTPUT iId).

                                                                 DO WHILE iId <> ?:
                                                                 addStack(iId).

                                                                      /*Criacao de valores para manter as relacoes*/
                                                                      CREATE ttPostingAppropriation_00.
                                                                      ASSIGN ttPostingAppropriation_00.ttPostingAppropriation_00ID = iId.
                                                                      ASSIGN ttPostingAppropriation_00.ttPostingItem_00ID = ttPostingItem_00.ttPostingItem_00ID.

                                                                      RUN getSonDec IN hGenXml (INPUT getStack(), INPUT "PostingAppropriationSequence", OUTPUT ttPostingAppropriation_00.PostingAppropriationSequence).
                                                                      ASSIGN iId = getStack().
                                                                      delStack().
                                                                      RUN getNextSonId IN hGenXml (INPUT getStack(), INPUT iId, OUTPUT iId).
                                                                 END.

                                                            delStack().
                                                       END.

                                                       ASSIGN iId = getStack().
                                                       delStack().
                                                       RUN getNextSonId IN hGenXml (INPUT getStack(), INPUT iId, OUTPUT iId).
                                                  END.

                                             delStack().
                                        END.

                                        ASSIGN iId = getStack().
                                        delStack().
                                        RUN getNextSonId IN hGenXml (INPUT getStack(), INPUT iId, OUTPUT iId).
                                   END.

                              delStack().
                         END.

                         ASSIGN iId = getStack().
                         delStack().
                         RUN getNextSonId IN hGenXml (INPUT getStack(), INPUT iId, OUTPUT iId).
                    END.

               delStack().
          END.

     delStack().
     /* ********* LEITURA DA MENSAGEM - END   ********* */


     /* ********* EFETIVAÄ«O - BEGIN ********* */



{adapters\xml\ct5\axrct025Delete.i}


     /* ********* EFETIVAÄ«O - END   ********* */

/* ******************************************* */
/* *************** BODY - END   ************** */
/* ******************************************* */

END PROCEDURE.


PROCEDURE PIUpsert:

/*PARAMETERS - BEGIN*/
/*PARAMETERS - END*/


/*LOCAL VARIABLES - BEGIN*/
DEFINE VAR iId AS INTEGER INITIAL ? NO-UNDO.
/*LOCAL VARIABLES - END*/


/* ******************************************* */
/* *************** BODY - BEGIN ************** */
/* ******************************************* */


     /* OBTEM A PARTE DA MENSAGEM QUE ESTÊ ABAIXO DO ELEMENTO BusinessContent */
     RUN getBusinessContent IN hMessageHandler (OUTPUT hBusinessContent).

     /* LIMPA AS TEMP-TABLES INTERNAS DA API XML */
     RUN reset IN hGenXml.

     /* CARREGA A ESTRUTURA FILHA DE BusinessContent */
     RUN loadXml IN hGenXml (hBusinessContent).

     /* ELIMINA A MENSAGEM OBTIDA NO MêTODO getBusinessContent */
     DELETE OBJECT hBusinessContent NO-ERROR.

     /* ********* LEITURA DA MENSAGEM - BEGIN ********* */
     addStack(1).
          RUN searchTag IN hGenXml (INPUT "ListOfGLBatchInformation", INPUT getStack(), OUTPUT iId).
          if (iId <> ?) THEN DO:
               addStack(iId).

                    RUN getFirstSonId IN hGenXml (INPUT getStack(), OUTPUT iId).

                    DO WHILE iId <> ?:
                    addStack(iId).

                         /*Criacao de valores para manter as relacoes*/
                         CREATE ttGLBatchInformation.
                         ASSIGN ttGLBatchInformation.ttGLBatchInformationID = iId.

                         RUN getSonDec IN hGenXml (INPUT getStack(), INPUT "GLBatchNumber", OUTPUT ttGLBatchInformation.GLBatchNumber).
                         RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "GLBatchDescription", OUTPUT ttGLBatchInformation.GLBatchDescription).
                         RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "Translation", OUTPUT ttGLBatchInformation.Translation).
                         RUN searchTag IN hGenXml (INPUT "CompanyInformation", INPUT getStack(), OUTPUT iId).
                         if (iId <> ?) THEN DO:
                              addStack(iId).

                                   RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "CompanyCode", OUTPUT ttGLBatchInformation.CompanyCode).
                                   RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "CompanyDescription", OUTPUT ttGLBatchInformation.CompanyDescription).
                                   RUN searchTag IN hGenXml (INPUT "CompanyIdentification", INPUT getStack(), OUTPUT iId).
                                   if (iId <> ?) THEN DO:
                                        addStack(iId).

                                             RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "Domain", OUTPUT ttGLBatchInformation.Domain).
                                             RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "CompanyID", OUTPUT ttGLBatchInformation.CompanyID).
                                        delStack().
                                   END.

                              delStack().
                         END.

                         RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "Reference", OUTPUT ttGLBatchInformation.Reference).
                         RUN getSonDate IN hGenXml (INPUT getStack(), INPUT "GLBatchDate", OUTPUT ttGLBatchInformation.GLBatchDate).
                         RUN searchTag IN hGenXml (INPUT "LastUpdateInformation", INPUT getStack(), OUTPUT iId).
                         if (iId <> ?) THEN DO:
                              addStack(iId).

                                   RUN searchTag IN hGenXml (INPUT "UserInformation", INPUT getStack(), OUTPUT iId).
                                   if (iId <> ?) THEN DO:
                                        addStack(iId).

                                             RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "UserCode", OUTPUT ttGLBatchInformation.UserCode).
                                             RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "UserName", OUTPUT ttGLBatchInformation.UserName).
                                        delStack().
                                   END.

                                   RUN getSonDate IN hGenXml (INPUT getStack(), INPUT "LastUpdateDate", OUTPUT ttGLBatchInformation.LastUpdateDate).
                                   RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "LastUpdateTime", OUTPUT ttGLBatchInformation.LastUpdateTime).
                              delStack().
                         END.

                         RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "GLBatchStatus", OUTPUT ttGLBatchInformation.GLBatchStatus).
                         RUN getSonLog IN hGenXml (INPUT getStack(), INPUT "IsCancelled", OUTPUT ttGLBatchInformation.IsCancelled).
                         RUN getSonDate IN hGenXml (INPUT getStack(), INPUT "CancelledDate", OUTPUT ttGLBatchInformation.CancelledDate).
                         RUN getSonLog IN hGenXml (INPUT getStack(), INPUT "IsOnlineAccounting", OUTPUT ttGLBatchInformation.IsOnlineAccounting).
                         RUN searchTag IN hGenXml (INPUT "OriginGLBatch", INPUT getStack(), OUTPUT iId).
                         if (iId <> ?) THEN DO:
                              addStack(iId).

                                   RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "ModuleCode", OUTPUT ttGLBatchInformation.ModuleCode).
                                   RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "ModuleDescription", OUTPUT ttGLBatchInformation.ModuleDescription).
                              delStack().
                         END.

                         RUN searchTag IN hGenXml (INPUT "StandardHistoryBatchInformation", INPUT getStack(), OUTPUT iId).
                         if (iId <> ?) THEN DO:
                              addStack(iId).

                                   RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "StandardHistoryCode", OUTPUT ttGLBatchInformation.StandardHistoryCode).
                                   RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "StandardHistoryDescription", OUTPUT ttGLBatchInformation.StandardHistoryDescription).
                              delStack().
                         END.

                         RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "BatchComplementaryDescription", OUTPUT ttGLBatchInformation.BatchComplementaryDescription).
                         RUN getSonDec IN hGenXml (INPUT getStack(), INPUT "BatchValue", OUTPUT ttGLBatchInformation.BatchValue).
                         RUN getSonDate IN hGenXml (INPUT getStack(), INPUT "BatchExchangeDate", OUTPUT ttGLBatchInformation.BatchExchangeDate).
                         RUN searchTag IN hGenXml (INPUT "ListOfPosting", INPUT getStack(), OUTPUT iId).
                         if (iId <> ?) THEN DO:
                              addStack(iId).

                                   RUN getFirstSonId IN hGenXml (INPUT getStack(), OUTPUT iId).

                                   DO WHILE iId <> ?:
                                   addStack(iId).

                                        /*Criacao de valores para manter as relacoes*/
                                        CREATE ttPosting.
                                        ASSIGN ttPosting.ttPostingID = iId.
                                        ASSIGN ttPosting.ttGLBatchInformationID = ttGLBatchInformation.ttGLBatchInformationID.

                                        RUN getSonDec IN hGenXml (INPUT getStack(), INPUT "PostingNumber", OUTPUT ttPosting.PostingNumber).
                                        RUN getSonDate IN hGenXml (INPUT getStack(), INPUT "PostingDate", OUTPUT ttPosting.PostingDate).
                                        RUN searchTag IN hGenXml (INPUT "GLScenarioInformation", INPUT getStack(), OUTPUT iId).
                                        if (iId <> ?) THEN DO:
                                             addStack(iId).

                                                  RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "ScenarioCode", OUTPUT ttPosting.ScenarioCode).
                                                  RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "ScenarioDescription", OUTPUT ttPosting.ScenarioDescription).
                                             delStack().
                                        END.

                                        RUN getSonLog IN hGenXml (INPUT getStack(), INPUT "IsUpdatedBalanceBatch", OUTPUT ttPosting.IsUpdatedBalanceBatch).
                                        RUN getSonLog IN hGenXml (INPUT getStack(), INPUT "IsConversionPosting", OUTPUT ttPosting.IsConversionPosting).
                                        RUN getSonLog IN hGenXml (INPUT getStack(), INPUT "IsResultVariancePosting", OUTPUT ttPosting.IsResultVariancePosting).
                                        RUN searchTag IN hGenXml (INPUT "StandardPostingInformation", INPUT getStack(), OUTPUT iId).
                                        if (iId <> ?) THEN DO:
                                             addStack(iId).

                                                  RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "StandardPostingCode", OUTPUT ttPosting.StandardPostingCode).
                                                  RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "StandardPostingDescription", OUTPUT ttPosting.StandardPostingDescription).
                                             delStack().
                                        END.

                                        RUN searchTag IN hGenXml (INPUT "GLProRataCode", INPUT getStack(), OUTPUT iId).
                                        if (iId <> ?) THEN DO:
                                             addStack(iId).

                                                  RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "ProRataCode", OUTPUT ttPosting.ProRataCode).
                                                  RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "ProRataDescription", OUTPUT ttPosting.ProRataDescription).
                                             delStack().
                                        END.

                                        RUN searchTag IN hGenXml (INPUT "StandardHistoryInformation", INPUT getStack(), OUTPUT iId).
                                        if (iId <> ?) THEN DO:
                                             addStack(iId).

                                                  RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "StandardHistoryCode", OUTPUT ttPosting.StandardHistoryCode).
                                                  RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "StandardHistoryDescription", OUTPUT ttPosting.StandardHistoryDescription).
                                             delStack().
                                        END.

                                        RUN getSonDec IN hGenXml (INPUT getStack(), INPUT "OriginBatchNumber", OUTPUT ttPosting.OriginBatchNumber).
                                        RUN getSonDec IN hGenXml (INPUT getStack(), INPUT "OriginPostingNumber", OUTPUT ttPosting.OriginPostingNumber).
                                        RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "PostingType", OUTPUT ttPosting.PostingType).
                                        RUN getSonDec IN hGenXml (INPUT getStack(), INPUT "CancelledBatchNumber", OUTPUT ttPosting.CancelledBatchNumber).
                                        RUN getSonDec IN hGenXml (INPUT getStack(), INPUT "CancelledPostingNumber", OUTPUT ttPosting.CancelledPostingNumber).
                                        RUN searchTag IN hGenXml (INPUT "ListOfPostingItem", INPUT getStack(), OUTPUT iId).
                                        if (iId <> ?) THEN DO:
                                             addStack(iId).

                                                  RUN getFirstSonId IN hGenXml (INPUT getStack(), OUTPUT iId).

                                                  DO WHILE iId <> ?:
                                                  addStack(iId).

                                                       /*Criacao de valores para manter as relacoes*/
                                                       CREATE ttPostingItem.
                                                       ASSIGN ttPostingItem.ttPostingItemID = iId.
                                                       ASSIGN ttPostingItem.ttPostingID = ttPosting.ttPostingID.

                                                       RUN getSonDec IN hGenXml (INPUT getStack(), INPUT "PostingItemSequenceNumber", OUTPUT ttPostingItem.PostingItemSequenceNumber).
                                                       RUN getSonDec IN hGenXml (INPUT getStack(), INPUT "PostingNature", OUTPUT ttPostingItem.PostingNature).
                                                       RUN searchTag IN hGenXml (INPUT "BranchInformation", INPUT getStack(), OUTPUT iId).
                                                       if (iId <> ?) THEN DO:
                                                            addStack(iId).

                                                                 RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "BranchCode", OUTPUT ttPostingItem.BranchCode).
                                                                 RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "BranchDescription", OUTPUT ttPostingItem.BranchDescription).
                                                            delStack().
                                                       END.

                                                       RUN searchTag IN hGenXml (INPUT "AccountInformation", INPUT getStack(), OUTPUT iId).
                                                       if (iId <> ?) THEN DO:
                                                            addStack(iId).

                                                                 RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "AccountPlanCode", OUTPUT ttPostingItem.AccountPlanCode).
                                                                 RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "AccountPlanDescription", OUTPUT ttPostingItem.AccountPlanDescription).
                                                                 RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "AccountCode", OUTPUT ttPostingItem.AccountCode).
                                                                 RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "SubAccountCode", OUTPUT ttPostingItem.SubAccountCode).
                                                                 RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "AccountDescription", OUTPUT ttPostingItem.AccountDescription).
                                                                 RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "AlternateAccountCode", OUTPUT ttPostingItem.AlternateAccountCode).
                                                                 RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "InternationalStandardAccountCode", OUTPUT ttPostingItem.InternationalStandardAccountCode).
                                                                 RUN getSonDec IN hGenXml (INPUT getStack(), INPUT "ReducedAccountCode", OUTPUT ttPostingItem.ReducedAccountCode).
                                                            delStack().
                                                       END.

                                                       RUN searchTag IN hGenXml (INPUT "ContraparterAccountInformation", INPUT getStack(), OUTPUT iId).
                                                       if (iId <> ?) THEN DO:
                                                            addStack(iId).

                                                                 RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "AccountPlanCode", OUTPUT ttPostingItem.AccountPlanCode_00).
                                                                 RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "AccountPlanDescription", OUTPUT ttPostingItem.AccountPlanDescription_00).
                                                                 RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "AccountCode", OUTPUT ttPostingItem.AccountCode_00).
                                                                 RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "SubAccountCode", OUTPUT ttPostingItem.SubAccountCode_00).
                                                                 RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "AccountDescription", OUTPUT ttPostingItem.AccountDescription_00).
                                                                 RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "AlternateAccountCode", OUTPUT ttPostingItem.AlternateAccountCode_00).
                                                                 RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "InternationalStandardAccountCode", OUTPUT ttPostingItem.InternationalStandardAccountC_00).
                                                                 RUN getSonDec IN hGenXml (INPUT getStack(), INPUT "ReducedAccountCode", OUTPUT ttPostingItem.ReducedAccountCode_00).
                                                            delStack().
                                                       END.

                                                       RUN searchTag IN hGenXml (INPUT "CostCenterInformation", INPUT getStack(), OUTPUT iId).
                                                       if (iId <> ?) THEN DO:
                                                            addStack(iId).

                                                                 RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "CostCenterPlanCode", OUTPUT ttPostingItem.CostCenterPlanCode).
                                                                 RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "CostCenterPlanDescription", OUTPUT ttPostingItem.CostCenterPlanDescription).
                                                                 RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "CostCenterCode", OUTPUT ttPostingItem.CostCenterCode).
                                                                 RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "CostCenterDescription", OUTPUT ttPostingItem.CostCenterDescription).
                                                                 RUN searchTag IN hGenXml (INPUT "UserInformation", INPUT getStack(), OUTPUT iId).
                                                                 if (iId <> ?) THEN DO:
                                                                      addStack(iId).

                                                                           RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "UserCode", OUTPUT ttPostingItem.UserCode).
                                                                           RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "UserName", OUTPUT ttPostingItem.UserName).
                                                                      delStack().
                                                                 END.

                                                                 RUN getSonDate IN hGenXml (INPUT getStack(), INPUT "ValidityStart", OUTPUT ttPostingItem.ValidityStart).
                                                                 RUN getSonDate IN hGenXml (INPUT getStack(), INPUT "ValidityEnd", OUTPUT ttPostingItem.ValidityEnd).
                                                                 RUN searchTag IN hGenXml (INPUT "ListOfBranchRestrictionInformation", INPUT getStack(), OUTPUT iId).
                                                                 if (iId <> ?) THEN DO:
                                                                      addStack(iId).

                                                                           RUN getFirstSonId IN hGenXml (INPUT getStack(), OUTPUT iId).

                                                                           DO WHILE iId <> ?:
                                                                           addStack(iId).

                                                                                /*Criacao de valores para manter as relacoes*/
                                                                                CREATE ttBranchRestrictionInform_00.
                                                                                ASSIGN ttBranchRestrictionInform_00.ttBranchRestrictionInform_00ID = iId.
                                                                                ASSIGN ttBranchRestrictionInform_00.ttPostingItemID = ttPostingItem.ttPostingItemID.

                                                                                RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "BranchCode", OUTPUT ttBranchRestrictionInform_00.BranchCode).
                                                                                RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "BranchDescription", OUTPUT ttBranchRestrictionInform_00.BranchDescription).
                                                                                ASSIGN iId = getStack().
                                                                                delStack().
                                                                                RUN getNextSonId IN hGenXml (INPUT getStack(), INPUT iId, OUTPUT iId).
                                                                           END.

                                                                      delStack().
                                                                 END.

                                                                 RUN searchTag IN hGenXml (INPUT "ListOfBusinessUnitUseInformation", INPUT getStack(), OUTPUT iId).
                                                                 if (iId <> ?) THEN DO:
                                                                      addStack(iId).

                                                                           RUN getFirstSonId IN hGenXml (INPUT getStack(), OUTPUT iId).

                                                                           DO WHILE iId <> ?:
                                                                           addStack(iId).

                                                                                /*Criacao de valores para manter as relacoes*/
                                                                                CREATE ttBusinessUnitUseInformation.
                                                                                ASSIGN ttBusinessUnitUseInformation.ttBusinessUnitUseInformationID = iId.
                                                                                ASSIGN ttBusinessUnitUseInformation.ttPostingItemID = ttPostingItem.ttPostingItemID.

                                                                                RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "BusinessUnitCode", OUTPUT ttBusinessUnitUseInformation.BusinessUnitCode).
                                                                                RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "BusinessUnitDescription", OUTPUT ttBusinessUnitUseInformation.BusinessUnitDescription).
                                                                                RUN getSonDec IN hGenXml (INPUT getStack(), INPUT "BusinessUnitId", OUTPUT ttBusinessUnitUseInformation.BusinessUnitId).
                                                                                ASSIGN iId = getStack().
                                                                                delStack().
                                                                                RUN getNextSonId IN hGenXml (INPUT getStack(), INPUT iId, OUTPUT iId).
                                                                           END.

                                                                      delStack().
                                                                 END.

                                                                 RUN searchTag IN hGenXml (INPUT "ListOfSecurityInformation", INPUT getStack(), OUTPUT iId).
                                                                 if (iId <> ?) THEN DO:
                                                                      addStack(iId).

                                                                           RUN getFirstSonId IN hGenXml (INPUT getStack(), OUTPUT iId).

                                                                           DO WHILE iId <> ?:
                                                                           addStack(iId).

                                                                                /*Criacao de valores para manter as relacoes*/
                                                                                CREATE ttSecurityInformation.
                                                                                ASSIGN ttSecurityInformation.ttSecurityInformationID = iId.
                                                                                ASSIGN ttSecurityInformation.ttPostingItemID = ttPostingItem.ttPostingItemID.

                                                                                RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "UserGroupCode", OUTPUT ttSecurityInformation.UserGroupCode).
                                                                                RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "UserGroupDescription", OUTPUT ttSecurityInformation.UserGroupDescription).
                                                                                ASSIGN iId = getStack().
                                                                                delStack().
                                                                                RUN getNextSonId IN hGenXml (INPUT getStack(), INPUT iId, OUTPUT iId).
                                                                           END.

                                                                      delStack().
                                                                 END.

                                                            delStack().
                                                       END.

                                                       RUN searchTag IN hGenXml (INPUT "BusinessUnitInformation", INPUT getStack(), OUTPUT iId).
                                                       if (iId <> ?) THEN DO:
                                                            addStack(iId).

                                                                 RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "BusinessUnitCode", OUTPUT ttPostingItem.BusinessUnitCode).
                                                                 RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "BusinessUnitDescription", OUTPUT ttPostingItem.BusinessUnitDescription).
                                                                 RUN getSonDec IN hGenXml (INPUT getStack(), INPUT "BusinessUnitId", OUTPUT ttPostingItem.BusinessUnitId).
                                                            delStack().
                                                       END.

                                                       RUN searchTag IN hGenXml (INPUT "FinancialProjectInformation", INPUT getStack(), OUTPUT iId).
                                                       if (iId <> ?) THEN DO:
                                                            addStack(iId).

                                                                 RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "FinancialProjectCode", OUTPUT ttPostingItem.FinancialProjectCode).
                                                                 RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "FinancialProjectDescription", OUTPUT ttPostingItem.FinancialProjectDescription).
                                                                 RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "FinancialProjectExternalCode", OUTPUT ttPostingItem.FinancialProjectExternalCode).
                                                            delStack().
                                                       END.

                                                       RUN searchTag IN hGenXml (INPUT "StandardHistoryInformation", INPUT getStack(), OUTPUT iId).
                                                       if (iId <> ?) THEN DO:
                                                            addStack(iId).

                                                                 RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "StandardHistoryCode", OUTPUT ttPostingItem.StandardHistoryCode).
                                                                 RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "StandardHistoryDescription", OUTPUT ttPostingItem.StandardHistoryDescription).
                                                            delStack().
                                                       END.

                                                       RUN searchTag IN hGenXml (INPUT "DocumentInformation", INPUT getStack(), OUTPUT iId).
                                                       if (iId <> ?) THEN DO:
                                                            addStack(iId).

                                                                 RUN searchTag IN hGenXml (INPUT "DocumentClassInformation", INPUT getStack(), OUTPUT iId).
                                                                 if (iId <> ?) THEN DO:
                                                                      addStack(iId).

                                                                           RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "DocumentClassCode", OUTPUT ttPostingItem.DocumentClassCode).
                                                                           RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "DocumentClassDescription", OUTPUT ttPostingItem.DocumentClassDescription).
                                                                      delStack().
                                                                 END.

                                                                 RUN getSonDate IN hGenXml (INPUT getStack(), INPUT "DocumentDate", OUTPUT ttPostingItem.DocumentDate).
                                                                 RUN searchTag IN hGenXml (INPUT "ImageInformation", INPUT getStack(), OUTPUT iId).
                                                                 if (iId <> ?) THEN DO:
                                                                      addStack(iId).

                                                                           RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "ImageCode", OUTPUT ttPostingItem.ImageCode).
                                                                           RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "ImageDescription", OUTPUT ttPostingItem.ImageDescription).
                                                                      delStack().
                                                                 END.

                                                                 RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "DocumentNumber", OUTPUT ttPostingItem.DocumentNumber).
                                                            delStack().
                                                       END.

                                                       RUN searchTag IN hGenXml (INPUT "CurrencyInformation", INPUT getStack(), OUTPUT iId).
                                                       if (iId <> ?) THEN DO:
                                                            addStack(iId).

                                                                 RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "CurrencyCode", OUTPUT ttPostingItem.CurrencyCode).
                                                                 RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "CurrencyDescription", OUTPUT ttPostingItem.CurrencyDescription).
                                                            delStack().
                                                       END.

                                                       RUN getSonDate IN hGenXml (INPUT getStack(), INPUT "PostingItemDate", OUTPUT ttPostingItem.PostingItemDate).
                                                       RUN getSonDec IN hGenXml (INPUT getStack(), INPUT "PostingItemQuantity", OUTPUT ttPostingItem.PostingItemQuantity).
                                                       RUN getSonDec IN hGenXml (INPUT getStack(), INPUT "PostingItemPercentage", OUTPUT ttPostingItem.PostingItemPercentage).
                                                       RUN getSonDec IN hGenXml (INPUT getStack(), INPUT "PostingItemValue", OUTPUT ttPostingItem.PostingItemValue).
                                                       RUN getSonDec IN hGenXml (INPUT getStack(), INPUT "PostingItemValueFASB", OUTPUT ttPostingItem.PostingItemValueFASB).
                                                       RUN getSonDec IN hGenXml (INPUT getStack(), INPUT "PostingItemValueCMCAC", OUTPUT ttPostingItem.PostingItemValueCMCAC).
                                                       RUN getSonDec IN hGenXml (INPUT getStack(), INPUT "PostingItemPresentValue", OUTPUT ttPostingItem.PostingItemPresentValue).
                                                       RUN getSonDate IN hGenXml (INPUT getStack(), INPUT "PostingItemExchangeDate", OUTPUT ttPostingItem.PostingItemExchangeDate).
                                                       RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "PostingDetail", OUTPUT ttPostingItem.PostingDetail).
                                                       RUN getSonDec IN hGenXml (INPUT getStack(), INPUT "ContraparterPostingSequenceNumber", OUTPUT ttPostingItem.ContraparterPostingSequenceNu_00).
                                                       RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "PostingItemTypeCode", OUTPUT ttPostingItem.PostingItemTypeCode).
                                                       RUN searchTag IN hGenXml (INPUT "GLScenarioInformation", INPUT getStack(), OUTPUT iId).
                                                       if (iId <> ?) THEN DO:
                                                            addStack(iId).

                                                                 RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "ScenarioCode", OUTPUT ttPostingItem.ScenarioCode).
                                                                 RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "ScenarioDescription", OUTPUT ttPostingItem.ScenarioDescription).
                                                            delStack().
                                                       END.

                                                       RUN getSonLog IN hGenXml (INPUT getStack(), INPUT "IsResultRaisePosting", OUTPUT ttPostingItem.IsResultRaisePosting).
                                                       RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "EntryNumber", OUTPUT ttPostingItem.EntryNumber).
                                                       RUN searchTag IN hGenXml (INPUT "ListOfPostingAppropriation", INPUT getStack(), OUTPUT iId).
                                                       if (iId <> ?) THEN DO:
                                                            addStack(iId).

                                                                 RUN getFirstSonId IN hGenXml (INPUT getStack(), OUTPUT iId).

                                                                 DO WHILE iId <> ?:
                                                                 addStack(iId).

                                                                      /*Criacao de valores para manter as relacoes*/
                                                                      CREATE ttPostingAppropriation.
                                                                      ASSIGN ttPostingAppropriation.ttPostingAppropriationID = iId.
                                                                      ASSIGN ttPostingAppropriation.ttPostingItemID = ttPostingItem.ttPostingItemID.

                                                                      RUN getSonDec IN hGenXml (INPUT getStack(), INPUT "PostingAppropriationSequence", OUTPUT ttPostingAppropriation.PostingAppropriationSequence).
                                                                      RUN searchTag IN hGenXml (INPUT "CurrencyInformation", INPUT getStack(), OUTPUT iId).
                                                                      if (iId <> ?) THEN DO:
                                                                           addStack(iId).

                                                                                RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "CurrencyCode", OUTPUT ttPostingAppropriation.CurrencyCode).
                                                                                RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "CurrencyDescription", OUTPUT ttPostingAppropriation.CurrencyDescription).
                                                                           delStack().
                                                                      END.

                                                                      RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "OriginValuePosting", OUTPUT ttPostingAppropriation.OriginValuePosting).
                                                                      RUN getSonDec IN hGenXml (INPUT getStack(), INPUT "PostingAppropriationValue", OUTPUT ttPostingAppropriation.PostingAppropriationValue).
                                                                      RUN searchTag IN hGenXml (INPUT "ExchangeInformation", INPUT getStack(), OUTPUT iId).
                                                                      if (iId <> ?) THEN DO:
                                                                           addStack(iId).

                                                                                RUN getSonDate IN hGenXml (INPUT getStack(), INPUT "ExchangeDate", OUTPUT ttPostingAppropriation.ExchangeDate).
                                                                                RUN getSonDec IN hGenXml (INPUT getStack(), INPUT "ExchangeValue", OUTPUT ttPostingAppropriation.ExchangeValue).
                                                                           delStack().
                                                                      END.

                                                                      ASSIGN iId = getStack().
                                                                      delStack().
                                                                      RUN getNextSonId IN hGenXml (INPUT getStack(), INPUT iId, OUTPUT iId).
                                                                 END.

                                                            delStack().
                                                       END.

                                                       ASSIGN iId = getStack().
                                                       delStack().
                                                       RUN getNextSonId IN hGenXml (INPUT getStack(), INPUT iId, OUTPUT iId).
                                                  END.

                                             delStack().
                                        END.

                                        ASSIGN iId = getStack().
                                        delStack().
                                        RUN getNextSonId IN hGenXml (INPUT getStack(), INPUT iId, OUTPUT iId).
                                   END.

                              delStack().
                         END.

                         ASSIGN iId = getStack().
                         delStack().
                         RUN getNextSonId IN hGenXml (INPUT getStack(), INPUT iId, OUTPUT iId).
                    END.

               delStack().
          END.

     delStack().
     /* ********* LEITURA DA MENSAGEM - END   ********* */


     /* ********* EFETIVAÄ«O - BEGIN ********* */



{adapters\xml\ct5\axrct025Upsert.i}


     /* ********* EFETIVAÄ«O - END   ********* */

/* ******************************************* */
/* *************** BODY - END   ************** */
/* ******************************************* */

END PROCEDURE.


PROCEDURE receiveMessage:

/*PARAMETERS - BEGIN*/
DEFINE INPUT PARAM hInputXML AS HANDLE NO-UNDO.
DEFINE OUTPUT PARAM hOutputXML AS HANDLE NO-UNDO.
/*PARAMETERS - END*/


/*LOCAL VARIABLES - BEGIN*/
/*LOCAL VARIABLES - END*/


/* ******************************************* */
/* *************** BODY - BEGIN ************** */
/* ******************************************* */

     /* VERIFICA SE MessageHandler.p ESTA NA MEMORIA */
     {xmlinc/xmlLoadMessageHandlerRec.i &MessageHandler="hMessageHandler" &MHReturnValue="cReturnValue" &MHReturnError="hOutputXML"}

     IF cReturnValue <> "OK" THEN DO:
          RETURN cReturnValue.
     END.

     /* INTERPRETA, ARMAZENA E VALIDA A MENSAGEM QUE RECEBE */
     RUN parseMessage IN hMessageHandler (
          INPUT  hInputXml, INPUT "{&XmlTranName}", 
          INPUT "{&XmlMaxTranVersion}", 
          INPUT "{&XmlMinTranVersion}", 
          INPUT "{&XmlListOfEvents}",
          OUTPUT lSuccessProcess,
          OUTPUT cTranAction, 
          OUTPUT cTranEvent,
          OUTPUT cTranVersion,
          OUTPUT hOutputXML ).

     /* SE N«O PROCESSOU CORRETAMENTE RETORNA ERRO */
     IF NOT lSuccessProcess OR RETURN-VALUE <> "OK" THEN 
     /* DAR TRATAMENTO CONVENIENTE ANTES DE RETORNAR */
          RETURN RETURN-VALUE.

     /* VERIFICA SE APIXML ESTA NA MEMORIA */
     {xmlinc/xmlloadgenxmlrec.i &GenXml="hGenXml" &GXReturnValue="cReturnValue" &GXReturnError="hOutputXML"}

     /* VERIFICA SE O ut-genxml FOI INICIADO CORRETAMENTE */
     IF cReturnValue <> "OK"
     THEN DO:
          /* ELIMINA A MENSAGEM OBTIDA NO M?TODO getBusinessContent */
          DELETE OBJECT hBusinessContent NO-ERROR.

          RETURN cReturnValue.
     END.



{adapters\xml\ct5\axrct025VersionControl.i}



/* ******************************************* */
/* *************** BODY - END   ************** */
/* ******************************************* */

END PROCEDURE.


/****** INTERNAL PROCEDURES - END*/

/***************************************************************************** 
**  Procedure Interna: pi_messages 
**  Descricao........: Mostra Mensagem com Ajuda 
*****************************************************************************/ 
PROCEDURE pi_messages: 

    def input param c_action    as char    no-undo. 
    def input param i_msg       as integer no-undo. 
    def input param c_param     as char    no-undo. 

    def var c_prg_msg           as char    no-undo. 

    assign c_prg_msg = "messages/" 
                     + string(trunc(i_msg / 1000,0),"99") 
                     + "/msg" 
                     + string(i_msg, "99999"). 

    if search(c_prg_msg + ".r") = ? and search(c_prg_msg + ".p") = ? then do: 
        message "Mensagem nr. " i_msg "!!!" skip 
                "Programa Mensagem" c_prg_msg "n∆o encontrado." 
                view-as alert-box error. 
        return error. 
    end. 

    run value(c_prg_msg + ".p") (input c_action, input c_param). 
    return return-value. 
END PROCEDURE.  /* pi_messages */ 
/*************************  End of fnc_view_message *************************/ 
