
/*IMPLEMENTATION FOR ADAPTERS PROGRESS API: 
 *
 *THIS CODE WAS GENERATED BY
 *  -Datasul Finance Adapters Generator - v0.09
 *  -28/10/2008 - 15:11
 *
 *DO NOT MODIFY THIS SOURCE CODE. IT IS MAINTAINED BY THE ADAPTERS MODEL
 *
 **/





{include/i_dbinst.i}
{include/i_dbtype.i}


/* DEFINICAO DE PRE-PROCESSADORES - BEGIN */
&GLOBAL-DEFINE XmlApp            FI5
&GLOBAL-DEFINE XmlMod            CMG
&GLOBAL-DEFINE XmlProdName       EMS5
&GLOBAL-DEFINE XmlProdVersion    505
&GLOBAL-DEFINE XmlTranName       CashBank
&GLOBAL-DEFINE XmlMinTranVersion 001
&GLOBAL-DEFINE XmlMaxTranVersion 999
&GLOBAL-DEFINE XmlListOfAction   upd

/* DEFINICAO DE PRE-PROCESSADORES - END */

/*LOCAL VARIABLES - BEGIN*/
DEFINE VAR cReturnValue AS CHARACTER INITIAL ? NO-UNDO.
DEFINE VAR cTranAction AS CHARACTER INITIAL ? NO-UNDO.
DEFINE VAR cTranEvent AS CHARACTER INITIAL ? NO-UNDO.
DEFINE VAR cTranVersion AS CHARACTER INITIAL ? NO-UNDO.
DEFINE VAR hBusinessContent AS HANDLE NO-UNDO.
DEFINE VAR hGenXml AS HANDLE NO-UNDO.
DEFINE VAR hMessageHandler AS HANDLE NO-UNDO.
DEFINE VAR lSuccessProcess AS LOGICAL INITIAL ? NO-UNDO.

DEFINE TEMP-TABLE tt_log_erro NO-UNDO
     FIELD ttv_num_cod_erro AS integer INITIAL ?
     FIELD ttv_des_msg_ajuda AS character INITIAL ?
     FIELD ttv_des_msg_erro AS character INITIAL ?
.


DEFINE TEMP-TABLE ttAppropriationInformation NO-UNDO
     FIELD AccountCode AS CHARACTER INITIAL ?  /*C¢digo da conta cont†bil (Uso interno: cod_cta_ctbl)*/
     FIELD AccountPlanCode AS CHARACTER INITIAL ?  /*C¢digo do Plano de Conta cont†bil (Uso interno: cod_plan_cta_ctbl)*/
     FIELD AppropriationValue AS decimal INITIAL ?  /*Valor da Aproprriaá∆o (Uso interno: val_movto_cta_corren)*/
     FIELD BranchCode AS CHARACTER INITIAL ?  /*C¢digo dao estabelecimento (Uso interno: cod_estabel)*/
     FIELD BusinessUnitCode AS CHARACTER INITIAL ?  /*C¢digo da unidade de neg¢cio (Uso interno: cod_unid_negoc)*/
     FIELD ChargeNature AS CHARACTER INITIAL ?  /*Naturezaa do lanáamento cont†bil (Uso interno: ind_natur_lancto_ctbl DB = DÇbito, CR = CrÇdito)*/
     FIELD CostCenterCode AS CHARACTER INITIAL ?  /*C¢digo do Centro de Custo (Uso interno: cod_ccusto)*/
     FIELD CostCenterPlanCode AS CHARACTER INITIAL ?  /*C¢digo do Plano de Centro de Custo (Uso interno: cod_plano_ccusto)*/
     FIELD ttAppropriationInformationID AS INTEGER INITIAL ?
     FIELD ttMovementID AS INTEGER INITIAL ?
     INDEX ixttAppropriationInformationID IS PRIMARY UNIQUE ttAppropriationInformationID ASCENDING
.


DEFINE TEMP-TABLE ttFinancialShareInformation NO-UNDO
     FIELD BranchCode AS CHARACTER INITIAL ?  /*C¢digo do estabelecimento (Uso interno: cod_estabel)*/
     FIELD BusinessUnitCode AS CHARACTER INITIAL ?  /*C¢digo da unidade de neg¢cio (Uso interno: cod_unid_negoc)*/
     FIELD FinancialFluxType AS CHARACTER INITIAL ?  /*C¢digo do Tipo de Fluxo Financeiro (Uso interno: cod_tip_fluxo_financ)*/
     FIELD FinancialShareValue AS decimal INITIAL ?  /*Valor do rateio financeiro (Uso interno: val_movto_cta_corren)*/
     FIELD ttFinancialShareInformationID AS INTEGER INITIAL ?
     FIELD ttMovementID AS INTEGER INITIAL ?
.


DEFINE TEMP-TABLE ttMovement NO-UNDO
     FIELD BankDocumentReference AS CHARACTER INITIAL ?  /*Documento do Banco que possa ser utilizado como referància para o movimento a ser criado (Uso interno: cod_docto_movto_cta_bco )*/
     FIELD CurrentAccountCode AS CHARACTER INITIAL ?  /*C¢digo da conta corrente (Uso interno: cod_cta_corren)*/
     FIELD ModuleCode AS CHARACTER INITIAL ?  /*C¢digo do M¢dulo (Uso interno: cod_modul_dtsul)*/
     FIELD MovementDate AS date INITIAL ?  /*Data do Movimento (Uso interno: dat_movto_cta_corren)*/
     FIELD MovementFluxType AS CHARACTER INITIAL ?  /*Fluxo do Movimento (Uso interno: ind_flux_movto_cta_corren ENT = Entrada, SAI  = Sa°da)*/
     FIELD MovementType AS CHARACTER INITIAL ?  /*Tipo de Movimento (Uso interno: ind_tip_movto_cta_corren RE = Realizado, NR = N∆o Realizado)*/
     FIELD MovementValue AS decimal INITIAL ?  /*Valor do movimento da conta corrente (Uso interno: val_movto_cta_corren)*/
     FIELD Scenario AS CHARACTER INITIAL ?  /*Cen†rio Cont†bil (Uso interno: od_cenar_ctbl)*/
     FIELD StandardHistoryCode AS CHARACTER INITIAL ?  /*C¢digo do historico padr∆o (cod_histor_padr ou cnd-histor-padr)*/
     FIELD StandardHistoryDescription AS CHARACTER INITIAL ?  /*Descriá∆o do hist¢rico padr∆o (des_histor_padr ou des-descr-gener)*/
     FIELD TransactionCashType AS CHARACTER INITIAL ?  /*Tipo de Transaá∆o de Caixa (Uso interno: cod_tip_trans_cx)*/
     FIELD ttMovementID AS INTEGER INITIAL ?
     INDEX ixttMovementID IS PRIMARY UNIQUE ttMovementID ASCENDING
.


DEFINE TEMP-TABLE ttValue NO-UNDO
     FIELD EconomicPurposeCode AS CHARACTER INITIAL ?  /*C¢digo da Finalidade Economica (Uso interno: cod_finalid_econ)*/
     FIELD EconomicPurposeValue AS decimal INITIAL ?  /*Valor na moeda da finalidade econìmica (Uso interno: val_movto_cta_corren)*/
     FIELD QuotationDate AS date INITIAL ?  /*Data da cotaá∆o (Uso interno: dat_cotac_indic_econ)*/
     FIELD QuotationValue AS decimal INITIAL ?  /*Valor da cotaá∆o (Uso interno: val_cotac_indic_econ)*/
     FIELD ttAppropriationInformationID AS INTEGER INITIAL ?
     FIELD ttValueID AS INTEGER INITIAL ?
.

/*LOCAL VARIABLES - END*/

/*PARAMETERS - BEGIN*/
/*PARAMETERS - END*/




{adapters\xml\fi5\axrfi022ExtraDeclarations.i}




/* DEF. VARIµVEIS USADAS EM xmlLoadMessageHandlerRec.i */
{xmlinc/xmlLoadMessageHandlerRecDef.i}

/* DEFINE AS VARAIVEIS PARA USO DO xmlLoadGenXmlRec.i */
{xmlinc/xmlLoadGenXmlRecDef.i}


/* DEFINE AS VARIAVEIS PARA USO DO xmlgettranssubsinfo */
{xmlinc/xmlgettranssubsinfo.i}

DEFINE TEMP-TABLE ttStack NO-UNDO
     FIELD ttID AS INTEGER
     FIELD ttPos AS INTEGER
     INDEX tt_id IS PRIMARY UNIQUE
           ttID  ASCENDING.


FUNCTION addStack RETURN INTEGER (INPUT val AS INTEGER).
     DEFINE VAR id AS INTEGER INITIAL 1 NO-UNDO.
     FIND LAST ttStack NO-ERROR.
     IF AVAIL(ttStack) THEN
          id = ttStack.ttID + 1.

     CREATE ttStack.
     ASSIGN ttStack.ttID = id.
     ASSIGN ttStack.ttPos = val.
END FUNCTION.


FUNCTION delStack RETURN INTEGER.
     FIND LAST ttStack NO-ERROR.
     IF AVAIL(ttStack) THEN
          DELETE ttStack.

     FIND LAST ttStack NO-ERROR.
END FUNCTION.


FUNCTION getStack RETURN INTEGER.
     IF AVAIL(ttStack) THEN
          RETURN ttStack.ttPos.
     ELSE
          RETURN 0.
END FUNCTION.




/* Begin_Include: i_version_extract */
def new global shared var v_cod_arq as char format 'x(60)' no-undo.
def new global shared var v_cod_tip_prog as character format 'x(8)' no-undo.
def stream s-arq.

if  v_cod_arq <> '' and v_cod_arq <> ?
then do:
     run pi_version_extract ('CashBankReceiver', 'adapters\xml\fi5\axrfi022.p', '001', 'pro').
end /* if */.
/* End_Include: i_version_extract */


/****** INTERNAL PROCEDURES - BEGIN*/
PROCEDURE pi_version_extract:

/*PARAMETERS - BEGIN*/
/*PARAMETERS - END*/


/*LOCAL VARIABLES - BEGIN*/
/*LOCAL VARIABLES - END*/


/* ******************************************* */
/* *************** BODY - BEGIN ************** */
/* ******************************************* */

/************************ Parameter Definition Begin ************************/
def Input param p_cod_program as character format "x(8)" no-undo.
def Input param p_cod_program_ext as character format "x(8)" no-undo.
def Input param p_cod_version as character format "x(8)" no-undo.
def Input param p_cod_program_type as character format "x(8)" no-undo.
/************************* Parameter Definition End *************************/
if  can-do(v_cod_tip_prog, p_cod_program_type)
then do:
if p_cod_program_type = 'dic' then 
     assign p_cod_program_ext = replace(p_cod_program_ext, 'database/', '').
     output stream s-arq to value(v_cod_arq) append.

     put stream s-arq unformatted
          p_cod_program            at 1
          p_cod_program_ext        at 43
          p_cod_version            at 69
          today                    at 84
          string(time, 'HH:MM:SS') at 94 skip.

     if  p_cod_program_type = 'pro' then do:
          find prog_dtsul 
               where prog_dtsul.cod_prog_dtsul = p_cod_program 
               no-lock no-error.

          if  avail prog_dtsul
          then do:
                    if  prog_dtsul.nom_prog_dpc <> '' then
                         put stream s-arq 'DPC : ' at 5 prog_dtsul.nom_prog_dpc  at 15 skip.

               if  prog_dtsul.nom_prog_appc <> '' then
                    put stream s-arq 'APPC: ' at 5 prog_dtsul.nom_prog_appc at 15 skip.
               if  prog_dtsul.nom_prog_upc <> '' then
                    put stream s-arq 'UPC : ' at 5 prog_dtsul.nom_prog_upc  at 15 skip.
          end /* if */.
     end.



     output stream s-arq close.

end /* if */.

/* ******************************************* */
/* *************** BODY - END   ************** */
/* ******************************************* */

END PROCEDURE.


PROCEDURE PIUpsert:

/*PARAMETERS - BEGIN*/
/*PARAMETERS - END*/


/*LOCAL VARIABLES - BEGIN*/
DEFINE VAR iId AS INTEGER INITIAL ? NO-UNDO.
/*LOCAL VARIABLES - END*/


/* ******************************************* */
/* *************** BODY - BEGIN ************** */
/* ******************************************* */


     /* OBTEM A PARTE DA MENSAGEM QUE ESTÊ ABAIXO DO ELEMENTO BusinessContent */
     RUN getBusinessContent IN hMessageHandler (OUTPUT hBusinessContent).

     /* LIMPA AS TEMP-TABLES INTERNAS DA API XML */
     RUN reset IN hGenXml.

     /* CARREGA A ESTRUTURA FILHA DE BusinessContent */
     RUN loadXml IN hGenXml (hBusinessContent).

     /* ELIMINA A MENSAGEM OBTIDA NO MêTODO getBusinessContent */
     DELETE OBJECT hBusinessContent NO-ERROR.

     /* ********* LEITURA DA MENSAGEM - BEGIN ********* */
     addStack(1).
          RUN searchTag IN hGenXml (INPUT "RecordInformation", INPUT getStack(), OUTPUT iId).
          if (iId <> ?) THEN DO:
               addStack(iId).

                    RUN searchTag IN hGenXml (INPUT "ListOfMovement", INPUT getStack(), OUTPUT iId).
                    if (iId <> ?) THEN DO:
                         addStack(iId).

                              RUN getFirstSonId IN hGenXml (INPUT getStack(), OUTPUT iId).

                              DO WHILE iId <> ?:
                              addStack(iId).

                                   /*Criacao de valores para manter as relacoes*/
                                   CREATE ttMovement.
                                   ASSIGN ttMovement.ttMovementID = iId.

                                   RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "CurrentAccountCode", OUTPUT ttMovement.CurrentAccountCode).
                                   RUN getSonDate IN hGenXml (INPUT getStack(), INPUT "MovementDate", OUTPUT ttMovement.MovementDate).
                                   RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "MovementType", OUTPUT ttMovement.MovementType).
                                   RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "TransactionCashType", OUTPUT ttMovement.TransactionCashType).
                                   RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "MovementFluxType", OUTPUT ttMovement.MovementFluxType).
                                   RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "Scenario", OUTPUT ttMovement.Scenario).
                                   RUN searchTag IN hGenXml (INPUT "StandardHistoryInformation", INPUT getStack(), OUTPUT iId).
                                   if (iId <> ?) THEN DO:
                                        addStack(iId).

                                             RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "StandardHistoryCode", OUTPUT ttMovement.StandardHistoryCode).
                                             RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "StandardHistoryDescription", OUTPUT ttMovement.StandardHistoryDescription).
                                        delStack().
                                   END.

                                   RUN getSonDec IN hGenXml (INPUT getStack(), INPUT "MovementValue", OUTPUT ttMovement.MovementValue).
                                   RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "BankDocumentReference", OUTPUT ttMovement.BankDocumentReference).
                                   RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "ModuleCode", OUTPUT ttMovement.ModuleCode).
                                   RUN searchTag IN hGenXml (INPUT "ListOfAppropriation", INPUT getStack(), OUTPUT iId).
                                   if (iId <> ?) THEN DO:
                                        addStack(iId).

                                             RUN getFirstSonId IN hGenXml (INPUT getStack(), OUTPUT iId).

                                             DO WHILE iId <> ?:
                                             addStack(iId).

                                                  /*Criacao de valores para manter as relacoes*/
                                                  CREATE ttAppropriationInformation.
                                                  ASSIGN ttAppropriationInformation.ttAppropriationInformationID = iId.
                                                  ASSIGN ttAppropriationInformation.ttMovementID = ttMovement.ttMovementID.

                                                  RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "ChargeNature", OUTPUT ttAppropriationInformation.ChargeNature).
                                                  RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "BranchCode", OUTPUT ttAppropriationInformation.BranchCode).
                                                  RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "AccountPlanCode", OUTPUT ttAppropriationInformation.AccountPlanCode).
                                                  RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "AccountCode", OUTPUT ttAppropriationInformation.AccountCode).
                                                  RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "BusinessUnitCode", OUTPUT ttAppropriationInformation.BusinessUnitCode).
                                                  RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "CostCenterPlanCode", OUTPUT ttAppropriationInformation.CostCenterPlanCode).
                                                  RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "CostCenterCode", OUTPUT ttAppropriationInformation.CostCenterCode).
                                                  RUN getSonDec IN hGenXml (INPUT getStack(), INPUT "AppropriationValue", OUTPUT ttAppropriationInformation.AppropriationValue).
                                                  RUN searchTag IN hGenXml (INPUT "ListOfValue", INPUT getStack(), OUTPUT iId).
                                                  if (iId <> ?) THEN DO:
                                                       addStack(iId).

                                                            RUN getFirstSonId IN hGenXml (INPUT getStack(), OUTPUT iId).

                                                            DO WHILE iId <> ?:
                                                            addStack(iId).

                                                                 /*Criacao de valores para manter as relacoes*/
                                                                 CREATE ttValue.
                                                                 ASSIGN ttValue.ttValueID = iId.
                                                                 ASSIGN ttValue.ttAppropriationInformationID = ttAppropriationInformation.ttAppropriationInformationID.

                                                                 RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "EconomicPurposeCode", OUTPUT ttValue.EconomicPurposeCode).
                                                                 RUN getSonDate IN hGenXml (INPUT getStack(), INPUT "QuotationDate", OUTPUT ttValue.QuotationDate).
                                                                 RUN getSonDec IN hGenXml (INPUT getStack(), INPUT "QuotationValue", OUTPUT ttValue.QuotationValue).
                                                                 RUN getSonDec IN hGenXml (INPUT getStack(), INPUT "EconomicPurposeValue", OUTPUT ttValue.EconomicPurposeValue).
                                                                 ASSIGN iId = getStack().
                                                                 delStack().
                                                                 RUN getNextSonId IN hGenXml (INPUT getStack(), INPUT iId, OUTPUT iId).
                                                            END.

                                                       delStack().
                                                  END.

                                                  ASSIGN iId = getStack().
                                                  delStack().
                                                  RUN getNextSonId IN hGenXml (INPUT getStack(), INPUT iId, OUTPUT iId).
                                             END.

                                        delStack().
                                   END.

                                   RUN searchTag IN hGenXml (INPUT "ListOfFinancialShare", INPUT getStack(), OUTPUT iId).
                                   if (iId <> ?) THEN DO:
                                        addStack(iId).

                                             RUN getFirstSonId IN hGenXml (INPUT getStack(), OUTPUT iId).

                                             DO WHILE iId <> ?:
                                             addStack(iId).

                                                  /*Criacao de valores para manter as relacoes*/
                                                  CREATE ttFinancialShareInformation.
                                                  ASSIGN ttFinancialShareInformation.ttFinancialShareInformationID = iId.
                                                  ASSIGN ttFinancialShareInformation.ttMovementID = ttMovement.ttMovementID.

                                                  RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "BranchCode", OUTPUT ttFinancialShareInformation.BranchCode).
                                                  RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "BusinessUnitCode", OUTPUT ttFinancialShareInformation.BusinessUnitCode).
                                                  RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "FinancialFluxType", OUTPUT ttFinancialShareInformation.FinancialFluxType).
                                                  RUN getSonDec IN hGenXml (INPUT getStack(), INPUT "FinancialShareValue", OUTPUT ttFinancialShareInformation.FinancialShareValue).
                                                  ASSIGN iId = getStack().
                                                  delStack().
                                                  RUN getNextSonId IN hGenXml (INPUT getStack(), INPUT iId, OUTPUT iId).
                                             END.

                                        delStack().
                                   END.

                                   ASSIGN iId = getStack().
                                   delStack().
                                   RUN getNextSonId IN hGenXml (INPUT getStack(), INPUT iId, OUTPUT iId).
                              END.

                         delStack().
                    END.

               delStack().
          END.

     delStack().
     /* ********* LEITURA DA MENSAGEM - END   ********* */


     /* ********* EFETIVAÄ«O - BEGIN ********* */



{adapters\xml\fi5\axrfi022Upsert.i}


     /* ********* EFETIVAÄ«O - END   ********* */

/* ******************************************* */
/* *************** BODY - END   ************** */
/* ******************************************* */

END PROCEDURE.


PROCEDURE receiveMessage:

/*PARAMETERS - BEGIN*/
DEFINE INPUT PARAM hInputXML AS HANDLE NO-UNDO.
DEFINE OUTPUT PARAM hOutputXML AS HANDLE NO-UNDO.
/*PARAMETERS - END*/


/*LOCAL VARIABLES - BEGIN*/
/*LOCAL VARIABLES - END*/


/* ******************************************* */
/* *************** BODY - BEGIN ************** */
/* ******************************************* */

     /* VERIFICA SE MessageHandler.p ESTA NA MEMORIA */
     {xmlinc/xmlLoadMessageHandlerRec.i &MessageHandler="hMessageHandler" &MHReturnValue="cReturnValue" &MHReturnError="hOutputXML"}

     IF cReturnValue <> "OK" THEN DO:
          RETURN cReturnValue.
     END.

     /* INTERPRETA, ARMAZENA E VALIDA A MENSAGEM QUE RECEBE */
     RUN parseMessage IN hMessageHandler (
          INPUT  hInputXml, INPUT "{&XmlTranName}", 
          INPUT "{&XmlMaxTranVersion}", 
          INPUT "{&XmlMinTranVersion}", 
          INPUT "{&XmlListOfEvents}",
          OUTPUT lSuccessProcess,
          OUTPUT cTranAction, 
          OUTPUT cTranEvent,
          OUTPUT cTranVersion,
          OUTPUT hOutputXML ).

     /* SE N«O PROCESSOU CORRETAMENTE RETORNA ERRO */
     IF NOT lSuccessProcess OR RETURN-VALUE <> "OK" THEN 
     /* DAR TRATAMENTO CONVENIENTE ANTES DE RETORNAR */
          RETURN RETURN-VALUE.

     /* VERIFICA SE APIXML ESTA NA MEMORIA */
     {xmlinc/xmlloadgenxmlrec.i &GenXml="hGenXml" &GXReturnValue="cReturnValue" &GXReturnError="hOutputXML"}

     /* VERIFICA SE O ut-genxml FOI INICIADO CORRETAMENTE */
     IF cReturnValue <> "OK"
     THEN DO:
          /* ELIMINA A MENSAGEM OBTIDA NO M?TODO getBusinessContent */
          DELETE OBJECT hBusinessContent NO-ERROR.

          RETURN cReturnValue.
     END.



{adapters\xml\fi5\axrfi022VersionControl.i}



/* ******************************************* */
/* *************** BODY - END   ************** */
/* ******************************************* */

END PROCEDURE.


/****** INTERNAL PROCEDURES - END*/



