
/*IMPLEMENTATION FOR ADAPTERS PROGRESS API: 
 *
 *THIS CODE WAS GENERATED BY
 *  -Datasul Finance Adapters Generator - v0.09
 *  -24/10/2008 - 14:08
 *
 *DO NOT MODIFY THIS SOURCE CODE. IT IS MAINTAINED BY THE ADAPTERS MODEL
 *
 **/





{include/i_dbinst.i}
{include/i_dbtype.i}

/* DEFINICAO DE PRE-PROCESSADORES - BEGIN */
&GLOBAL-DEFINE XmlApp            FI5
&GLOBAL-DEFINE XmlMod            APB
&GLOBAL-DEFINE XmlProdName       EMS5
&GLOBAL-DEFINE XmlProdVersion    506
&GLOBAL-DEFINE XmlTranName       ReplacementAccountPayableDocumentEspecific_506_000
&GLOBAL-DEFINE XmlMinTranVersion 001
&GLOBAL-DEFINE XmlMaxTranVersion 999
&GLOBAL-DEFINE XmlListOfAction   add,upd,del

/* DEFINICAO DE PRE-PROCESSADORES - END */

/*LOCAL VARIABLES - BEGIN*/
DEFINE VAR BranchCode AS CHARACTER INITIAL ? NO-UNDO.  /*C¢digo dao estabelecimento (cod_estabel ou cdn-estabe)*/
DEFINE VAR BranchCode_00 AS CHARACTER INITIAL ? NO-UNDO.  /*C¢digo dao estabelecimento (cod_estabel ou cdn-estabe)*/
DEFINE VAR BranchDescription AS CHARACTER INITIAL ? NO-UNDO.  /*Raz∆o Social do estabelecimento (des_empresa)*/
DEFINE VAR BranchDescription_00 AS CHARACTER INITIAL ? NO-UNDO.  /*Raz∆o Social do estabelecimento (des_empresa)*/
DEFINE VAR CompanyCode AS CHARACTER INITIAL ? NO-UNDO.  /*C¢digo da empresa (cod_empresa ou cdn-empresa)*/
DEFINE VAR CompanyCode_00 AS CHARACTER INITIAL ? NO-UNDO.  /*C¢digo da empresa (cod_empresa ou cdn-empresa)*/
DEFINE VAR CompanyDescription AS CHARACTER INITIAL ? NO-UNDO.  /*Raz∆o Social da Empresa (des_empresa)*/
DEFINE VAR CompanyDescription_00 AS CHARACTER INITIAL ? NO-UNDO.  /*Raz∆o Social da Empresa (des_empresa)*/
DEFINE VAR CompanyID AS CHARACTER INITIAL ? NO-UNDO.  /*Identificaá∆o de Empresa*/
DEFINE VAR CompanyID_00 AS CHARACTER INITIAL ? NO-UNDO.  /*Identificaá∆o de Empresa*/
DEFINE VAR cReturnValue AS CHARACTER INITIAL ? NO-UNDO.
DEFINE VAR cTranAction AS CHARACTER INITIAL ? NO-UNDO.
DEFINE VAR cTranEvent AS CHARACTER INITIAL ? NO-UNDO.
DEFINE VAR cTranVersion AS CHARACTER INITIAL ? NO-UNDO.
DEFINE VAR CurrencyCode AS CHARACTER INITIAL ? NO-UNDO.  /*C¢digo do indicador econìmido ou moeda*/
DEFINE VAR CurrencyDescription AS CHARACTER INITIAL ? NO-UNDO.  /*Descriá∆o do indicador econìmico ou moeda.*/
DEFINE VAR DocumentClassCode AS CHARACTER INITIAL ? NO-UNDO.  /*C¢digo da espÇcie de documento*/
DEFINE VAR DocumentClassDescription AS CHARACTER INITIAL ? NO-UNDO.  /*Descriá∆o da espÇcie do documento*/
DEFINE VAR Domain AS CHARACTER INITIAL ? NO-UNDO.  /*Descriá∆o do tipo de identificaá∆o da empresa*/
DEFINE VAR Domain_00 AS CHARACTER INITIAL ? NO-UNDO.  /*Descriá∆o do tipo de identificaá∆o da empresa*/
DEFINE VAR EconomicPurposeCode AS CHARACTER INITIAL ? NO-UNDO.  /*C¢digo da Finalidade Economica (cod_finalid_econ)*/
DEFINE VAR EconomicPurposeDescription AS CHARACTER INITIAL ? NO-UNDO.  /*Descriá∆o da Finalidade Economica (des_finalid_econ)*/
DEFINE VAR EntityCode AS integer INITIAL ? NO-UNDO.  /*C¢digo da Pessoa (num_pessoa)*/
DEFINE VAR ExternalOrganizationTranslati_00 AS CHARACTER INITIAL ? NO-UNDO.  /*C¢digo da Matriz de Traduá∆o de Organizaá∆o Externa (cod_matriz_trad_org_ext)*/
DEFINE VAR GenerealIdentification AS CHARACTER INITIAL ? NO-UNDO.  /*Identificaá∆o CNPJ ou CPF (cod_id_feder)*/
DEFINE VAR hBusinessContent AS HANDLE NO-UNDO.
DEFINE VAR hGenXml AS HANDLE NO-UNDO.
DEFINE VAR hMessageHandler AS HANDLE NO-UNDO.
DEFINE VAR InvoiceNumber AS integer INITIAL ? NO-UNDO.  /*N£mero da Fatura (num_fatur_ap)*/
DEFINE VAR lSuccessProcess AS LOGICAL INITIAL ? NO-UNDO.
DEFINE VAR QuantityParcel AS integer INITIAL ? NO-UNDO.  /*Quantidade de Parcelas (qtd_parcela)*/
DEFINE VAR Reference AS CHARACTER INITIAL ? NO-UNDO.  /*Referància (cod_refer)*/
DEFINE VAR StandardHistoryCode AS CHARACTER INITIAL ? NO-UNDO.  /*C¢digo do historico padr∆o (cod_histor_padr ou cnd-histor-padr)*/
DEFINE VAR StandartHistoryDescription AS CHARACTER INITIAL ? NO-UNDO.  /*Descriá∆o do hist¢rico padr∆o (des_histor_padr ou des-descr-gener)*/
DEFINE VAR SupplierCode AS CHARACTER INITIAL ? NO-UNDO.  /*C¢digo do Fornecedor (cod_fornec)*/
DEFINE VAR SupplierGroupCode AS CHARACTER INITIAL ? NO-UNDO.  /*C¢digo do Grupo de Fornecedores (cod_grp_fornec)*/
DEFINE VAR SupplierGroupDescription AS CHARACTER INITIAL ? NO-UNDO.  /*Descriá∆o do Grupo de Fornecedores (des_grp_fornec)*/
DEFINE VAR SupplierMatrix AS CHARACTER INITIAL ? NO-UNDO.  /*Matriz Fornecedor (ind_matriz_fornec)*/
DEFINE VAR SupplierName AS CHARACTER INITIAL ? NO-UNDO.  /*Nome do Fornecedor (nom_pessoa)*/
DEFINE VAR SupplierShortName AS CHARACTER INITIAL ? NO-UNDO.  /*Nome Abreviado (nom_abrev)*/
DEFINE VAR TransactionDate AS date INITIAL ? NO-UNDO.  /*Data da transaá∆o (dat_transacao)*/
DEFINE VAR TransactionTotalValue AS decimal INITIAL ? NO-UNDO.  /*Valor Total da Transaá∆o (val_tot_lote_impl_tit_ap)*/

DEFINE TEMP-TABLE tt_log_erro NO-UNDO
     FIELD ttv_num_cod_erro AS integer INITIAL ?
     FIELD ttv_des_msg_ajuda AS character INITIAL ?
     FIELD ttv_des_msg_erro AS character INITIAL ?
.


DEFINE TEMP-TABLE ttAccountPayableDocumentI_00 NO-UNDO
     FIELD AlternativePaymentMethodCode AS CHARACTER INITIAL ?  /*C¢digo da Forma de Pagamento Alternativa (cod_forma_pagto_altern)*/
     FIELD CollectorCode AS CHARACTER INITIAL ?  /*C¢digo do Portador (cod_portador)*/
     FIELD CollectorCode_00 AS CHARACTER INITIAL ?  /*C¢digo do Portador (cod_portador)*/
     FIELD CollectorDescription AS CHARACTER INITIAL ?  /*Nome do Portador (nom_pessoa)*/
     FIELD CollectorDescription_00 AS CHARACTER INITIAL ?  /*Nome do Portador (nom_pessoa)*/
     FIELD CurrencyCode AS CHARACTER INITIAL ?  /*C¢digo do indicador econìmido ou moeda*/
     FIELD CurrencyDescription AS CHARACTER INITIAL ?  /*Descriá∆o do indicador econìmico ou moeda.*/
     FIELD DayLateInterestPercentage AS decimal INITIAL ?  /*Percentual de Juros Di†rios (val_perc_juros_dias_atraso)*/
     FIELD Days AS integer INITIAL ?  /*N£mero de Dias (num_dias)*/
     FIELD DaysLate AS integer INITIAL ?  /*Dias de atraso (num_dias_atraso)*/
     FIELD DaysLateInterest AS decimal INITIAL ?  /*Juros Di†rios (val_juros_dias_atraso)*/
     FIELD DiscountDate AS date INITIAL ?  /*Data do Desconto (dat_desconto)*/
     FIELD DiscountPercentage AS decimal INITIAL ?  /*Percentual de Desconto (val_perc_desc)*/
     FIELD DiscountValue AS decimal INITIAL ?  /*Valor do Desconto (val_desconto)*/
     FIELD DocumentClassCode AS CHARACTER INITIAL ?  /*C¢digo da espÇcie de documento*/
     FIELD DocumentClassDescription AS CHARACTER INITIAL ?  /*Descriá∆o da espÇcie do documento*/
     FIELD DocumentNumber AS CHARACTER INITIAL ?  /*N£mero do Documento (cod_tit_ap)*/
     FIELD DocumentParcelNumber AS CHARACTER INITIAL ?  /*Parcela (cod_parcela)*/
     FIELD DocumentSerieCode AS CHARACTER INITIAL ?  /*SÇrie do Documento (cod_ser_docto)*/
     FIELD DocumentValue AS decimal INITIAL ?  /*Valor do T°tulo (val_tit_ap)*/
     FIELD DueDate AS date INITIAL ?  /*Data de Vencimento (dat_vencto_tit_ap)*/
     FIELD DueForecastType AS integer INITIAL ?  /*Tipo de Previs∆o de Vencimento. Valores: 1 Dia, 2 Mes. (ind_vencto_previs)*/
     FIELD EconomicPurposeCode AS CHARACTER INITIAL ?  /*C¢digo da Finalidade Economica (cod_finalid_econ)*/
     FIELD EconomicPurposeDescription AS CHARACTER INITIAL ?  /*Descriá∆o da Finalidade Economica (des_finalid_econ)*/
     FIELD EntityCode AS integer INITIAL ?  /*C¢digo da Pessoa (num_pessoa)*/
     FIELD ExternalModalityCode AS CHARACTER INITIAL ?  /*Modadlidade Externa (cod_modalidade_ext)*/
     FIELD ExternalModalityCode_00 AS CHARACTER INITIAL ?  /*Modadlidade Externa (cod_modalidade_ext)*/
     FIELD GenerealIdentification AS CHARACTER INITIAL ?  /*Identificaá∆o CNPJ ou CPF (cod_id_feder)*/
     FIELD InsurancePolicyNumber AS CHARACTER INITIAL ?  /*Ap¢lice (cod_apol_seguro)*/
     FIELD InsurerCode AS CHARACTER INITIAL ?  /*Seguradora (cod_seguradora)*/
     FIELD InvestmentOrder AS integer INITIAL ?  /*Ordem de Investimento (num_ord_invest)*/
     FIELD LeasingContractNumber AS CHARACTER INITIAL ?  /*Contrato de Leasing (cod_contrat_leas)*/
     FIELD LessorCode AS CHARACTER INITIAL ?  /*Arrendador (cod_arrendador)*/
     FIELD ParcelQuantity AS integer INITIAL ?  /*Quantidade de Parcelas (qtd_parc_tit_ap)*/
     FIELD PaymentForecastDate AS date INITIAL ?  /*Data Prevista de Pagamento (dat_prev_pagto)*/
     FIELD PaymentMethodCode AS CHARACTER INITIAL ?  /*C¢digo da Forma de Pagamento (cod_forma_pagto)*/
     FIELD PaymentMethodDescription AS CHARACTER INITIAL ?  /*Descriá∆o da Forma de Pagamento (des_forma_pagto)*/
     FIELD Penalty AS decimal INITIAL ?  /*Multa (val_perc_multa)*/
     FIELD PortfolioCode AS CHARACTER INITIAL ?  /*C¢digo da Carteira (cod_cart_bcia)*/
     FIELD PortfolioCode_00 AS CHARACTER INITIAL ?  /*C¢digo da Carteira (cod_cart_bcia)*/
     FIELD PortfolioDescription AS CHARACTER INITIAL ?  /*Descriá∆o da Carteira (des_cart_bcia)*/
     FIELD PortfolioDescription_00 AS CHARACTER INITIAL ?  /*Descriá∆o da Carteira (des_cart_bcia)*/
     FIELD PrintDate AS date INITIAL ?  /*Data Emissao (dat_emis_docto)*/
     FIELD QuotationValue AS decimal INITIAL ?  /*Valor da Cotaá∆o (val_cota_indic_econ)*/
     FIELD Sequence AS integer INITIAL ?  /*Sequencia (num_seq_refer)*/
     FIELD StandardHistoryCode AS CHARACTER INITIAL ?  /*C¢digo do historico padr∆o (cod_histor_padr ou cnd-histor-padr)*/
     FIELD StandartHistoryDescription AS CHARACTER INITIAL ?  /*Descriá∆o do hist¢rico padr∆o (des_histor_padr ou des-descr-gener)*/
     FIELD SupplierCode AS CHARACTER INITIAL ?  /*C¢digo do Fornecedor (cod_fornec)*/
     FIELD SupplierGroupCode AS CHARACTER INITIAL ?  /*C¢digo do Grupo de Fornecedores (cod_grp_fornec)*/
     FIELD SupplierGroupDescription AS CHARACTER INITIAL ?  /*Descriá∆o do Grupo de Fornecedores (des_grp_fornec)*/
     FIELD SupplierName AS CHARACTER INITIAL ?  /*Nome do Fornecedor (nom_pessoa)*/
     FIELD SupplierShortName AS CHARACTER INITIAL ?  /*Nome Abreviado (nom_abrev)*/
     FIELD TaxIdentNumber AS CHARACTER INITIAL ?  /*Identificaá∆o do Imposto (cod_tax_ident_number)*/
     FIELD TenNineNineTransactionType AS integer INITIAL ?  /*Tipo Transaá∆o 1099. Valores: 1 Rents, 2 Royalties, 3 Other Income, 4 Fishing and boat proceeds, 5 Medical and health care payments, 6 Nonemployee compensation, 7 Substitute payments, 8 Crop insurance proceeds (ind_tip_trans_1099)*/
     FIELD TenNineNineValue AS decimal INITIAL ?  /*Valor 1099 (val_1099)*/
     FIELD ttAccountPayableDocumentI_00ID AS INTEGER INITIAL ?
     INDEX ixttAccountPayableDocumentI_00ID IS PRIMARY UNIQUE ttAccountPayableDocumentI_00ID ASCENDING
.


DEFINE TEMP-TABLE ttPendentTaxInformation NO-UNDO
     FIELD AccountCode AS CHARACTER INITIAL ?  /*C¢digo da conta cont†bil (cod_cta_ctbl ou cod-conta)*/
     FIELD AccountCode_00 AS CHARACTER INITIAL ?  /*C¢digo da conta cont†bil (cod_cta_ctbl ou cod-conta)*/
     FIELD AccountDescription AS CHARACTER INITIAL ?  /*Descriá∆o da conta cont†bil (des_cta_ctbl)*/
     FIELD AccountDescription_00 AS CHARACTER INITIAL ?  /*Descriá∆o da conta cont†bil (des_cta_ctbl)*/
     FIELD AccountPlanCode AS CHARACTER INITIAL ?  /*C¢digo do Plano de Conta cont†bil (cod_plan_cta_ctbl)*/
     FIELD AccountPlanCode_00 AS CHARACTER INITIAL ?  /*C¢digo do Plano de Conta cont†bil (cod_plan_cta_ctbl)*/
     FIELD AccountPlanDescription AS CHARACTER INITIAL ?  /*Descriá∆o do plano de contas cont†bil (des_plan_cta_ctbl)*/
     FIELD AccountPlanDescription_00 AS CHARACTER INITIAL ?  /*Descriá∆o do plano de contas cont†bil (des_plan_cta_ctbl)*/
     FIELD AlternateAccountCode AS CHARACTER INITIAL ?  /*C¢digo da conta alternativa*/
     FIELD AlternateAccountCode_00 AS CHARACTER INITIAL ?  /*C¢digo da conta alternativa*/
     FIELD CountryCode AS CHARACTER INITIAL ?  /*C¢digo do Pa°s (cod_pais)*/
     FIELD CountryCode_00 AS CHARACTER INITIAL ?  /*C¢digo do Pa°s (cod_pais)*/
     FIELD CountryName AS CHARACTER INITIAL ?  /*Nome do Pa°s (nom_pais)*/
     FIELD CountryName_00 AS CHARACTER INITIAL ?  /*Nome do Pa°s (nom_pais)*/
     FIELD CurrencyCode AS CHARACTER INITIAL ?  /*C¢digo do indicador econìmido ou moeda*/
     FIELD CurrencyDescription AS CHARACTER INITIAL ?  /*Descriá∆o do indicador econìmico ou moeda.*/
     FIELD DeductionValue AS decimal INITIAL ?  /*Valor da Deduá∆o (val_deduc_faixa_impto)*/
     FIELD DependentDeduction AS decimal INITIAL ?  /*Deduá‰es Dependentes (val_deduc_depend)*/
     FIELD DocumentClassCode AS CHARACTER INITIAL ?  /*C¢digo da espÇcie de documento*/
     FIELD DocumentClassDescription AS CHARACTER INITIAL ?  /*Descriá∆o da espÇcie do documento*/
     FIELD DocumentNumber AS CHARACTER INITIAL ?  /*N£mero do Documento (cod_tit_ap)*/
     FIELD DocumentParcelNumber AS CHARACTER INITIAL ?  /*Parcela (cod_parcela)*/
     FIELD DocumentSerieCode AS CHARACTER INITIAL ?  /*SÇrie do Documento (cod_ser_docto)*/
     FIELD DueDate AS date INITIAL ?  /*Data de Vencimento (dat_vencto_tit_ap)*/
     FIELD EconomicPurposeValue AS decimal INITIAL ?  /*Valor do Imposto na Finalidade Economica (val_impto_indic_econ_impto)*/
     FIELD EntityCode AS integer INITIAL ?  /*C¢digo da Pessoa (num_pessoa)*/
     FIELD FinancialFlowTypeCode AS CHARACTER INITIAL ?  /*C¢digo do Tipo de Fluxo Financeiro (cod_tip_fluxo_financ)*/
     FIELD FinancialFlowTypeDescription AS CHARACTER INITIAL ?  /*Descriá∆o do Tipo de Fluxo Financeiro (des_tip_fluxo_financ)*/
     FIELD GenerealIdentification AS CHARACTER INITIAL ?  /*Identificaá∆o CNPJ ou CPF (cod_id_feder)*/
     FIELD INSSDeduction AS decimal INITIAL ?  /*Deduá∆o INSS (val_deduc_inss)*/
     FIELD InternationalStandardAccountC_00 AS CHARACTER INITIAL ?  /*C¢digo Internacional da conta cont†bil*/
     FIELD InternationalStandardAccountCode AS CHARACTER INITIAL ?  /*C¢digo Internacional da conta cont†bil*/
     FIELD OtherDeductions AS decimal INITIAL ?  /*Outras Deduá‰es (val_outras_deduc_impto)*/
     FIELD PaidTax AS decimal INITIAL ?  /*Imposto J† Recolhido (val_impto_ja_recolhid)*/
     FIELD PensionDeduction AS decimal INITIAL ?  /*Deduá∆o Pens∆o (val_deduc_pensao)*/
     FIELD ReducedAccountCode AS integer INITIAL ?  /*C¢digo da conta Reduzida (cnd-cta-reduz)*/
     FIELD ReducedAccountCode_00 AS integer INITIAL ?  /*C¢digo da conta Reduzida (cnd-cta-reduz)*/
     FIELD RevenueTax AS decimal INITIAL ?  /*Rendimento Tribut†vel (val_rendto_tribut)*/
     FIELD StandardHistoryCode AS CHARACTER INITIAL ?  /*C¢digo do historico padr∆o (cod_histor_padr ou cnd-histor-padr)*/
     FIELD StandartHistoryDescription AS CHARACTER INITIAL ?  /*Descriá∆o do hist¢rico padr∆o (des_histor_padr ou des-descr-gener)*/
     FIELD StateCode AS CHARACTER INITIAL ?  /*C¢digo do Unidade da Federaá∆o (cod_unid_federac)*/
     FIELD StateCode_00 AS CHARACTER INITIAL ?  /*C¢digo do Unidade da Federaá∆o (cod_unid_federac)*/
     FIELD StateName AS CHARACTER INITIAL ?  /*Nome da Unidade da Federaá∆o (nom_unid_federac)*/
     FIELD StateName_00 AS CHARACTER INITIAL ?  /*Nome da Unidade da Federaá∆o (nom_unid_federac)*/
     FIELD SubAccountCode AS CHARACTER INITIAL ?  /*C¢digo da subconta cont†bil (cod-subconta-ctbl)*/
     FIELD SubAccountCode_00 AS CHARACTER INITIAL ?  /*C¢digo da subconta cont†bil (cod-subconta-ctbl)*/
     FIELD SupplierCode AS CHARACTER INITIAL ?  /*C¢digo do Fornecedor (cod_fornec)*/
     FIELD SupplierGroupCode AS CHARACTER INITIAL ?  /*C¢digo do Grupo de Fornecedores (cod_grp_fornec)*/
     FIELD SupplierGroupDescription AS CHARACTER INITIAL ?  /*Descriá∆o do Grupo de Fornecedores (des_grp_fornec)*/
     FIELD SupplierName AS CHARACTER INITIAL ?  /*Nome do Fornecedor (nom_pessoa)*/
     FIELD SupplierShortName AS CHARACTER INITIAL ?  /*Nome Abreviado (nom_abrev)*/
     FIELD TaxBaseValue AS decimal INITIAL ?  /*Base Liquida Imposto (val_base_liq_impto)*/
     FIELD TaxClassification AS CHARACTER INITIAL ?  /*Classificaá∆o do Imposto (ind_class_impto)*/
     FIELD TaxCode AS CHARACTER INITIAL ?  /*C¢digo do Imposto (cod_imposto)*/
     FIELD TaxDescription AS CHARACTER INITIAL ?  /*Descriá∆o do Imposto (des_imposto)*/
     FIELD TaxPercentage AS decimal INITIAL ?  /*Al°quota Imposto (val_aliq_impto)*/
     FIELD TaxType AS CHARACTER INITIAL ?  /*Tipo do imposto (ind_tip_impto)*/
     FIELD TaxValue AS decimal INITIAL ?  /*Valor do Imposto (val_imposto)*/
     FIELD ttAccountPayableDocumentI_00ID AS INTEGER INITIAL ?
     FIELD ttPendentTaxInformationID AS INTEGER INITIAL ?
.


DEFINE TEMP-TABLE ttRelactoAccountPayableDo_00 NO-UNDO
     FIELD BranchCode AS CHARACTER INITIAL ?  /*C¢digo dao estabelecimento (cod_estabel ou cdn-estabe)*/
     FIELD BranchDescription AS CHARACTER INITIAL ?  /*Raz∆o Social do estabelecimento (des_empresa)*/
     FIELD CorrectValueReason AS CHARACTER INITIAL ?  /*Motivo Acerto valor (ind_motiv_acerto_val)*/
     FIELD DocumentClassCode AS CHARACTER INITIAL ?  /*C¢digo da espÇcie de documento*/
     FIELD DocumentClassDescription AS CHARACTER INITIAL ?  /*Descriá∆o da espÇcie do documento*/
     FIELD DocumentNumber AS CHARACTER INITIAL ?  /*N£mero do Documento (cod_tit_ap)*/
     FIELD DocumentParcelNumber AS CHARACTER INITIAL ?  /*Parcela (cod_parcela)*/
     FIELD DocumentSerieCode AS CHARACTER INITIAL ?  /*SÇrie do Documento (cod_ser_docto)*/
     FIELD EntityCode AS integer INITIAL ?  /*C¢digo da Pessoa (num_pessoa)*/
     FIELD GenerealIdentification AS CHARACTER INITIAL ?  /*Identificaá∆o CNPJ ou CPF (cod_id_feder)*/
     FIELD SupplierCode AS CHARACTER INITIAL ?  /*C¢digo do Fornecedor (cod_fornec)*/
     FIELD SupplierGroupCode AS CHARACTER INITIAL ?  /*C¢digo do Grupo de Fornecedores (cod_grp_fornec)*/
     FIELD SupplierGroupDescription AS CHARACTER INITIAL ?  /*Descriá∆o do Grupo de Fornecedores (des_grp_fornec)*/
     FIELD SupplierName AS CHARACTER INITIAL ?  /*Nome do Fornecedor (nom_pessoa)*/
     FIELD SupplierShortName AS CHARACTER INITIAL ?  /*Nome Abreviado (nom_abrev)*/
     FIELD ttRelactoAccountPayableDo_00ID AS INTEGER INITIAL ?
     INDEX ixttRelactoAccountPayableDo_00ID IS PRIMARY UNIQUE ttRelactoAccountPayableDo_00ID ASCENDING
.

/*LOCAL VARIABLES - END*/

/*PARAMETERS - BEGIN*/
/*PARAMETERS - END*/




{adapters\xml\fi5\axrfi005ExtraDeclarations.i}




/* DEF. VARIµVEIS USADAS EM xmlLoadMessageHandlerRec.i */
{xmlinc/xmlLoadMessageHandlerRecDef.i}

/* DEFINE AS VARAIVEIS PARA USO DO xmlLoadGenXmlRec.i */
{xmlinc/xmlLoadGenXmlRecDef.i}


/* DEFINE AS VARIAVEIS PARA USO DO xmlgettranssubsinfo */
{xmlinc/xmlgettranssubsinfo.i}

DEFINE TEMP-TABLE ttStack NO-UNDO
     FIELD ttID AS INTEGER
     FIELD ttPos AS INTEGER
     INDEX tt_id IS PRIMARY UNIQUE
           ttID  ASCENDING.


FUNCTION addStack RETURN INTEGER (INPUT val AS INTEGER).
     DEFINE VAR id AS INTEGER INITIAL 1 NO-UNDO.
     FIND LAST ttStack NO-ERROR.
     IF AVAIL(ttStack) THEN
          id = ttStack.ttID + 1.

     CREATE ttStack.
     ASSIGN ttStack.ttID = id.
     ASSIGN ttStack.ttPos = val.
END FUNCTION.


FUNCTION delStack RETURN INTEGER.
     FIND LAST ttStack NO-ERROR.
     IF AVAIL(ttStack) THEN
          DELETE ttStack.

     FIND LAST ttStack NO-ERROR.
END FUNCTION.


FUNCTION getStack RETURN INTEGER.
     IF AVAIL(ttStack) THEN
          RETURN ttStack.ttPos.
     ELSE
          RETURN 0.
END FUNCTION.




/* Begin_Include: i_version_extract */
def new global shared var v_cod_arq as char format 'x(60)' no-undo.
def new global shared var v_cod_tip_prog as character format 'x(8)' no-undo.
def stream s-arq.

if  v_cod_arq <> '' and v_cod_arq <> ?
then do:
     run pi_version_extract ('ReplacementAccountPayableDocumentEspecific_506_000Receiver', 'adapters\xml\fi5\axrfi005.p', '001', 'pro').
end /* if */.
/* End_Include: i_version_extract */


/****** INTERNAL PROCEDURES - BEGIN*/
PROCEDURE pi_version_extract:

/*PARAMETERS - BEGIN*/
/*PARAMETERS - END*/


/*LOCAL VARIABLES - BEGIN*/
/*LOCAL VARIABLES - END*/


/* ******************************************* */
/* *************** BODY - BEGIN ************** */
/* ******************************************* */

/************************ Parameter Definition Begin ************************/
def Input param p_cod_program as character format "x(8)" no-undo.
def Input param p_cod_program_ext as character format "x(8)" no-undo.
def Input param p_cod_version as character format "x(8)" no-undo.
def Input param p_cod_program_type as character format "x(8)" no-undo.
/************************* Parameter Definition End *************************/
if  can-do(v_cod_tip_prog, p_cod_program_type)
then do:
if p_cod_program_type = 'dic' then 
     assign p_cod_program_ext = replace(p_cod_program_ext, 'database/', '').
     output stream s-arq to value(v_cod_arq) append.

     put stream s-arq unformatted
          p_cod_program            at 1
          p_cod_program_ext        at 43
          p_cod_version            at 69
          today                    at 84
          string(time, 'HH:MM:SS') at 94 skip.

     if  p_cod_program_type = 'pro' then do:
          find prog_dtsul 
               where prog_dtsul.cod_prog_dtsul = p_cod_program 
               no-lock no-error.

          if  avail prog_dtsul
          then do:
                    if  prog_dtsul.nom_prog_dpc <> '' then
                         put stream s-arq 'DPC : ' at 5 prog_dtsul.nom_prog_dpc  at 15 skip.

               if  prog_dtsul.nom_prog_appc <> '' then
                    put stream s-arq 'APPC: ' at 5 prog_dtsul.nom_prog_appc at 15 skip.
               if  prog_dtsul.nom_prog_upc <> '' then
                    put stream s-arq 'UPC : ' at 5 prog_dtsul.nom_prog_upc  at 15 skip.
          end /* if */.
     end.



     output stream s-arq close.

end /* if */.

/* ******************************************* */
/* *************** BODY - END   ************** */
/* ******************************************* */

END PROCEDURE.


PROCEDURE PIUpsert:

/*PARAMETERS - BEGIN*/
/*PARAMETERS - END*/


/*LOCAL VARIABLES - BEGIN*/
DEFINE VAR iId AS INTEGER INITIAL ? NO-UNDO.
/*LOCAL VARIABLES - END*/


/* ******************************************* */
/* *************** BODY - BEGIN ************** */
/* ******************************************* */


     /* OBTEM A PARTE DA MENSAGEM QUE ESTÊ ABAIXO DO ELEMENTO BusinessContent */
     RUN getBusinessContent IN hMessageHandler (OUTPUT hBusinessContent).

     /* LIMPA AS TEMP-TABLES INTERNAS DA API XML */
     RUN reset IN hGenXml.

     /* CARREGA A ESTRUTURA FILHA DE BusinessContent */
     RUN loadXml IN hGenXml (hBusinessContent).

     /* ELIMINA A MENSAGEM OBTIDA NO MêTODO getBusinessContent */
     DELETE OBJECT hBusinessContent NO-ERROR.

     /* ********* LEITURA DA MENSAGEM - BEGIN ********* */
     addStack(1).
          RUN searchTag IN hGenXml (INPUT "RecordInformation", INPUT getStack(), OUTPUT iId).
          if (iId <> ?) THEN DO:
               addStack(iId).

                    RUN searchTag IN hGenXml (INPUT "AccountPayableBatchInformation", INPUT getStack(), OUTPUT iId).
                    if (iId <> ?) THEN DO:
                         addStack(iId).

                              RUN searchTag IN hGenXml (INPUT "BranchInformation", INPUT getStack(), OUTPUT iId).
                              if (iId <> ?) THEN DO:
                                   addStack(iId).

                                        RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "BranchCode", OUTPUT BranchCode).
                                        RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "BranchDescription", OUTPUT BranchDescription).
                                   delStack().
                              END.

                              RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "Reference", OUTPUT Reference).
                              RUN searchTag IN hGenXml (INPUT "DocumentClassInformation", INPUT getStack(), OUTPUT iId).
                              if (iId <> ?) THEN DO:
                                   addStack(iId).

                                        RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "DocumentClassCode", OUTPUT DocumentClassCode).
                                        RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "DocumentClassDescription", OUTPUT DocumentClassDescription).
                                   delStack().
                              END.

                              RUN getSonDec IN hGenXml (INPUT getStack(), INPUT "QuantityParcel", OUTPUT QuantityParcel).
                              RUN searchTag IN hGenXml (INPUT "StandardHistoryInformation", INPUT getStack(), OUTPUT iId).
                              if (iId <> ?) THEN DO:
                                   addStack(iId).

                                        RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "StandardHistoryCode", OUTPUT StandardHistoryCode).
                                        RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "StandartHistoryDescription", OUTPUT StandartHistoryDescription).
                                   delStack().
                              END.

                              RUN getSonDec IN hGenXml (INPUT getStack(), INPUT "InvoiceNumber", OUTPUT InvoiceNumber).
                              RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "SupplierMatrix", OUTPUT SupplierMatrix).
                              RUN searchTag IN hGenXml (INPUT "SupplierInformation", INPUT getStack(), OUTPUT iId).
                              if (iId <> ?) THEN DO:
                                   addStack(iId).

                                        RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "SupplierCode", OUTPUT SupplierCode).
                                        RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "SupplierName", OUTPUT SupplierName).
                                        RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "SupplierShortName", OUTPUT SupplierShortName).
                                        RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "GenerealIdentification", OUTPUT GenerealIdentification).
                                        RUN getSonDec IN hGenXml (INPUT getStack(), INPUT "EntityCode", OUTPUT EntityCode).
                                        RUN searchTag IN hGenXml (INPUT "SupplierGroupInformation", INPUT getStack(), OUTPUT iId).
                                        if (iId <> ?) THEN DO:
                                             addStack(iId).

                                                  RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "SupplierGroupCode", OUTPUT SupplierGroupCode).
                                                  RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "SupplierGroupDescription", OUTPUT SupplierGroupDescription).
                                             delStack().
                                        END.

                                   delStack().
                              END.

                              RUN getSonDate IN hGenXml (INPUT getStack(), INPUT "TransactionDate", OUTPUT TransactionDate).
                              RUN searchTag IN hGenXml (INPUT "ExternalBranchInformation", INPUT getStack(), OUTPUT iId).
                              if (iId <> ?) THEN DO:
                                   addStack(iId).

                                        RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "BranchCode", OUTPUT BranchCode_00).
                                        RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "BranchDescription", OUTPUT BranchDescription_00).
                                   delStack().
                              END.

                              RUN getSonDec IN hGenXml (INPUT getStack(), INPUT "TransactionTotalValue", OUTPUT TransactionTotalValue).
                              RUN searchTag IN hGenXml (INPUT "CompanyInformation", INPUT getStack(), OUTPUT iId).
                              if (iId <> ?) THEN DO:
                                   addStack(iId).

                                        RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "CompanyCode", OUTPUT CompanyCode).
                                        RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "CompanyDescription", OUTPUT CompanyDescription).
                                        RUN searchTag IN hGenXml (INPUT "CompanyIdentification", INPUT getStack(), OUTPUT iId).
                                        if (iId <> ?) THEN DO:
                                             addStack(iId).

                                                  RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "Domain", OUTPUT Domain).
                                                  RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "CompanyID", OUTPUT CompanyID).
                                             delStack().
                                        END.

                                   delStack().
                              END.

                              RUN searchTag IN hGenXml (INPUT "ExternalCompanyInformation", INPUT getStack(), OUTPUT iId).
                              if (iId <> ?) THEN DO:
                                   addStack(iId).

                                        RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "CompanyCode", OUTPUT CompanyCode_00).
                                        RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "CompanyDescription", OUTPUT CompanyDescription_00).
                                        RUN searchTag IN hGenXml (INPUT "CompanyIdentification", INPUT getStack(), OUTPUT iId).
                                        if (iId <> ?) THEN DO:
                                             addStack(iId).

                                                  RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "Domain", OUTPUT Domain_00).
                                                  RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "CompanyID", OUTPUT CompanyID_00).
                                             delStack().
                                        END.

                                   delStack().
                              END.

                              RUN searchTag IN hGenXml (INPUT "ExternalEconomicPurposeInformation", INPUT getStack(), OUTPUT iId).
                              if (iId <> ?) THEN DO:
                                   addStack(iId).

                                        RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "EconomicPurposeCode", OUTPUT EconomicPurposeCode).
                                        RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "EconomicPurposeDescription", OUTPUT EconomicPurposeDescription).
                                   delStack().
                              END.

                              RUN searchTag IN hGenXml (INPUT "CurrencyInformation", INPUT getStack(), OUTPUT iId).
                              if (iId <> ?) THEN DO:
                                   addStack(iId).

                                        RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "CurrencyCode", OUTPUT CurrencyCode).
                                        RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "CurrencyDescription", OUTPUT CurrencyDescription).
                                   delStack().
                              END.

                              RUN searchTag IN hGenXml (INPUT "ListOfAccountPayableDocument", INPUT getStack(), OUTPUT iId).
                              if (iId <> ?) THEN DO:
                                   addStack(iId).

                                        RUN getFirstSonId IN hGenXml (INPUT getStack(), OUTPUT iId).

                                        DO WHILE iId <> ?:
                                        addStack(iId).

                                             /*Criacao de valores para manter as relacoes*/
                                             CREATE ttAccountPayableDocumentI_00.
                                             ASSIGN ttAccountPayableDocumentI_00.ttAccountPayableDocumentI_00ID = iId.

                                             RUN getSonDec IN hGenXml (INPUT getStack(), INPUT "Sequence", OUTPUT ttAccountPayableDocumentI_00.Sequence).
                                             RUN searchTag IN hGenXml (INPUT "SupplierInformation", INPUT getStack(), OUTPUT iId).
                                             if (iId <> ?) THEN DO:
                                                  addStack(iId).

                                                       RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "SupplierCode", OUTPUT ttAccountPayableDocumentI_00.SupplierCode).
                                                       RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "SupplierName", OUTPUT ttAccountPayableDocumentI_00.SupplierName).
                                                       RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "SupplierShortName", OUTPUT ttAccountPayableDocumentI_00.SupplierShortName).
                                                       RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "GenerealIdentification", OUTPUT ttAccountPayableDocumentI_00.GenerealIdentification).
                                                       RUN getSonDec IN hGenXml (INPUT getStack(), INPUT "EntityCode", OUTPUT ttAccountPayableDocumentI_00.EntityCode).
                                                       RUN searchTag IN hGenXml (INPUT "SupplierGroupInformation", INPUT getStack(), OUTPUT iId).
                                                       if (iId <> ?) THEN DO:
                                                            addStack(iId).

                                                                 RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "SupplierGroupCode", OUTPUT ttAccountPayableDocumentI_00.SupplierGroupCode).
                                                                 RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "SupplierGroupDescription", OUTPUT ttAccountPayableDocumentI_00.SupplierGroupDescription).
                                                            delStack().
                                                       END.

                                                  delStack().
                                             END.

                                             RUN searchTag IN hGenXml (INPUT "DocumentClassInformation", INPUT getStack(), OUTPUT iId).
                                             if (iId <> ?) THEN DO:
                                                  addStack(iId).

                                                       RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "DocumentClassCode", OUTPUT ttAccountPayableDocumentI_00.DocumentClassCode).
                                                       RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "DocumentClassDescription", OUTPUT ttAccountPayableDocumentI_00.DocumentClassDescription).
                                                  delStack().
                                             END.

                                             RUN searchTag IN hGenXml (INPUT "DocumentInformation", INPUT getStack(), OUTPUT iId).
                                             if (iId <> ?) THEN DO:
                                                  addStack(iId).

                                                       RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "DocumentSerieCode", OUTPUT ttAccountPayableDocumentI_00.DocumentSerieCode).
                                                       RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "DocumentNumber", OUTPUT ttAccountPayableDocumentI_00.DocumentNumber).
                                                       RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "DocumentParcelNumber", OUTPUT ttAccountPayableDocumentI_00.DocumentParcelNumber).
                                                  delStack().
                                             END.

                                             RUN getSonDate IN hGenXml (INPUT getStack(), INPUT "PrintDate", OUTPUT ttAccountPayableDocumentI_00.PrintDate).
                                             RUN getSonDate IN hGenXml (INPUT getStack(), INPUT "DueDate", OUTPUT ttAccountPayableDocumentI_00.DueDate).
                                             RUN getSonDate IN hGenXml (INPUT getStack(), INPUT "PaymentForecastDate", OUTPUT ttAccountPayableDocumentI_00.PaymentForecastDate).
                                             RUN getSonDate IN hGenXml (INPUT getStack(), INPUT "DiscountDate", OUTPUT ttAccountPayableDocumentI_00.DiscountDate).
                                             RUN searchTag IN hGenXml (INPUT "CurrencyInformation", INPUT getStack(), OUTPUT iId).
                                             if (iId <> ?) THEN DO:
                                                  addStack(iId).

                                                       RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "CurrencyCode", OUTPUT ttAccountPayableDocumentI_00.CurrencyCode).
                                                       RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "CurrencyDescription", OUTPUT ttAccountPayableDocumentI_00.CurrencyDescription).
                                                  delStack().
                                             END.

                                             RUN getSonDec IN hGenXml (INPUT getStack(), INPUT "QuotationValue", OUTPUT ttAccountPayableDocumentI_00.QuotationValue).
                                             RUN getSonDec IN hGenXml (INPUT getStack(), INPUT "DocumentValue", OUTPUT ttAccountPayableDocumentI_00.DocumentValue).
                                             RUN searchTag IN hGenXml (INPUT "DiscountInformation", INPUT getStack(), OUTPUT iId).
                                             if (iId <> ?) THEN DO:
                                                  addStack(iId).

                                                       RUN getSonDec IN hGenXml (INPUT getStack(), INPUT "DiscountValue", OUTPUT ttAccountPayableDocumentI_00.DiscountValue).
                                                       RUN getSonDec IN hGenXml (INPUT getStack(), INPUT "DiscountPercentage", OUTPUT ttAccountPayableDocumentI_00.DiscountPercentage).
                                                  delStack().
                                             END.

                                             RUN searchTag IN hGenXml (INPUT "InterestInformation", INPUT getStack(), OUTPUT iId).
                                             if (iId <> ?) THEN DO:
                                                  addStack(iId).

                                                       RUN getSonDec IN hGenXml (INPUT getStack(), INPUT "DaysLate", OUTPUT ttAccountPayableDocumentI_00.DaysLate).
                                                       RUN getSonDec IN hGenXml (INPUT getStack(), INPUT "DaysLateInterest", OUTPUT ttAccountPayableDocumentI_00.DaysLateInterest).
                                                       RUN getSonDec IN hGenXml (INPUT getStack(), INPUT "DayLateInterestPercentage", OUTPUT ttAccountPayableDocumentI_00.DayLateInterestPercentage).
                                                       RUN getSonDec IN hGenXml (INPUT getStack(), INPUT "Penalty", OUTPUT ttAccountPayableDocumentI_00.Penalty).
                                                  delStack().
                                             END.

                                             RUN searchTag IN hGenXml (INPUT "CollectorInformation", INPUT getStack(), OUTPUT iId).
                                             if (iId <> ?) THEN DO:
                                                  addStack(iId).

                                                       RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "CollectorCode", OUTPUT ttAccountPayableDocumentI_00.CollectorCode).
                                                       RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "CollectorDescription", OUTPUT ttAccountPayableDocumentI_00.CollectorDescription).
                                                       RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "ExternalModalityCode", OUTPUT ttAccountPayableDocumentI_00.ExternalModalityCode).
                                                       RUN searchTag IN hGenXml (INPUT "PortfolioInformation", INPUT getStack(), OUTPUT iId).
                                                       if (iId <> ?) THEN DO:
                                                            addStack(iId).

                                                                 RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "PortfolioCode", OUTPUT ttAccountPayableDocumentI_00.PortfolioCode).
                                                                 RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "PortfolioDescription", OUTPUT ttAccountPayableDocumentI_00.PortfolioDescription).
                                                            delStack().
                                                       END.

                                                  delStack().
                                             END.

                                             RUN searchTag IN hGenXml (INPUT "InsuranceInformation", INPUT getStack(), OUTPUT iId).
                                             if (iId <> ?) THEN DO:
                                                  addStack(iId).

                                                       RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "InsurerCode", OUTPUT ttAccountPayableDocumentI_00.InsurerCode).
                                                       RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "InsurancePolicyNumber", OUTPUT ttAccountPayableDocumentI_00.InsurancePolicyNumber).
                                                  delStack().
                                             END.

                                             RUN searchTag IN hGenXml (INPUT "LeasingInformation", INPUT getStack(), OUTPUT iId).
                                             if (iId <> ?) THEN DO:
                                                  addStack(iId).

                                                       RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "LessorCode", OUTPUT ttAccountPayableDocumentI_00.LessorCode).
                                                       RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "LeasingContractNumber", OUTPUT ttAccountPayableDocumentI_00.LeasingContractNumber).
                                                  delStack().
                                             END.

                                             RUN searchTag IN hGenXml (INPUT "StandardHistoryInformation", INPUT getStack(), OUTPUT iId).
                                             if (iId <> ?) THEN DO:
                                                  addStack(iId).

                                                       RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "StandardHistoryCode", OUTPUT ttAccountPayableDocumentI_00.StandardHistoryCode).
                                                       RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "StandartHistoryDescription", OUTPUT ttAccountPayableDocumentI_00.StandartHistoryDescription).
                                                  delStack().
                                             END.

                                             RUN getSonDec IN hGenXml (INPUT getStack(), INPUT "ParcelQuantity", OUTPUT ttAccountPayableDocumentI_00.ParcelQuantity).
                                             RUN getSonDec IN hGenXml (INPUT getStack(), INPUT "Days", OUTPUT ttAccountPayableDocumentI_00.Days).
                                             RUN getSonDec IN hGenXml (INPUT getStack(), INPUT "DueForecastType", OUTPUT ttAccountPayableDocumentI_00.DueForecastType).
                                             RUN searchTag IN hGenXml (INPUT "ExternalCollectorInformation", INPUT getStack(), OUTPUT iId).
                                             if (iId <> ?) THEN DO:
                                                  addStack(iId).

                                                       RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "CollectorCode", OUTPUT ttAccountPayableDocumentI_00.CollectorCode_00).
                                                       RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "CollectorDescription", OUTPUT ttAccountPayableDocumentI_00.CollectorDescription_00).
                                                       RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "ExternalModalityCode", OUTPUT ttAccountPayableDocumentI_00.ExternalModalityCode_00).
                                                       RUN searchTag IN hGenXml (INPUT "PortfolioInformation", INPUT getStack(), OUTPUT iId).
                                                       if (iId <> ?) THEN DO:
                                                            addStack(iId).

                                                                 RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "PortfolioCode", OUTPUT ttAccountPayableDocumentI_00.PortfolioCode_00).
                                                                 RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "PortfolioDescription", OUTPUT ttAccountPayableDocumentI_00.PortfolioDescription_00).
                                                            delStack().
                                                       END.

                                                  delStack().
                                             END.

                                             RUN searchTag IN hGenXml (INPUT "PaymentMethodInformation", INPUT getStack(), OUTPUT iId).
                                             if (iId <> ?) THEN DO:
                                                  addStack(iId).

                                                       RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "PaymentMethodCode", OUTPUT ttAccountPayableDocumentI_00.PaymentMethodCode).
                                                       RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "PaymentMethodDescription", OUTPUT ttAccountPayableDocumentI_00.PaymentMethodDescription).
                                                       RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "AlternativePaymentMethodCode", OUTPUT ttAccountPayableDocumentI_00.AlternativePaymentMethodCode).
                                                  delStack().
                                             END.

                                             RUN getSonDec IN hGenXml (INPUT getStack(), INPUT "InvestmentOrder", OUTPUT ttAccountPayableDocumentI_00.InvestmentOrder).
                                             RUN getSonDec IN hGenXml (INPUT getStack(), INPUT "TenNineNineValue", OUTPUT ttAccountPayableDocumentI_00.TenNineNineValue).
                                             RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "TaxIdentNumber", OUTPUT ttAccountPayableDocumentI_00.TaxIdentNumber).
                                             RUN getSonDec IN hGenXml (INPUT getStack(), INPUT "TenNineNineTransactionType", OUTPUT ttAccountPayableDocumentI_00.TenNineNineTransactionType).
                                             RUN searchTag IN hGenXml (INPUT "ListOfPendentTax", INPUT getStack(), OUTPUT iId).
                                             if (iId <> ?) THEN DO:
                                                  addStack(iId).

                                                       RUN getFirstSonId IN hGenXml (INPUT getStack(), OUTPUT iId).

                                                       DO WHILE iId <> ?:
                                                       addStack(iId).

                                                            /*Criacao de valores para manter as relacoes*/
                                                            CREATE ttPendentTaxInformation.
                                                            ASSIGN ttPendentTaxInformation.ttPendentTaxInformationID = iId.
                                                            ASSIGN ttPendentTaxInformation.ttAccountPayableDocumentI_00ID = ttAccountPayableDocumentI_00.ttAccountPayableDocumentI_00ID.

                                                            RUN searchTag IN hGenXml (INPUT "LocationInformation", INPUT getStack(), OUTPUT iId).
                                                            if (iId <> ?) THEN DO:
                                                                 addStack(iId).

                                                                      RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "CountryCode", OUTPUT ttPendentTaxInformation.CountryCode).
                                                                      RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "CountryName", OUTPUT ttPendentTaxInformation.CountryName).
                                                                      RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "StateCode", OUTPUT ttPendentTaxInformation.StateCode).
                                                                      RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "StateName", OUTPUT ttPendentTaxInformation.StateName).
                                                                 delStack().
                                                            END.

                                                            RUN searchTag IN hGenXml (INPUT "TaxInformation", INPUT getStack(), OUTPUT iId).
                                                            if (iId <> ?) THEN DO:
                                                                 addStack(iId).

                                                                      RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "TaxCode", OUTPUT ttPendentTaxInformation.TaxCode).
                                                                      RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "TaxDescription", OUTPUT ttPendentTaxInformation.TaxDescription).
                                                                      RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "TaxType", OUTPUT ttPendentTaxInformation.TaxType).
                                                                      RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "TaxClassification", OUTPUT ttPendentTaxInformation.TaxClassification).
                                                                 delStack().
                                                            END.

                                                            RUN searchTag IN hGenXml (INPUT "AccountInformation", INPUT getStack(), OUTPUT iId).
                                                            if (iId <> ?) THEN DO:
                                                                 addStack(iId).

                                                                      RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "AccountPlanCode", OUTPUT ttPendentTaxInformation.AccountPlanCode).
                                                                      RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "AccountPlanDescription", OUTPUT ttPendentTaxInformation.AccountPlanDescription).
                                                                      RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "AccountCode", OUTPUT ttPendentTaxInformation.AccountCode).
                                                                      RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "SubAccountCode", OUTPUT ttPendentTaxInformation.SubAccountCode).
                                                                      RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "AccountDescription", OUTPUT ttPendentTaxInformation.AccountDescription).
                                                                      RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "AlternateAccountCode", OUTPUT ttPendentTaxInformation.AlternateAccountCode).
                                                                      RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "InternationalStandardAccountCode", OUTPUT ttPendentTaxInformation.InternationalStandardAccountCode).
                                                                      RUN getSonDec IN hGenXml (INPUT getStack(), INPUT "ReducedAccountCode", OUTPUT ttPendentTaxInformation.ReducedAccountCode).
                                                                 delStack().
                                                            END.

                                                            RUN searchTag IN hGenXml (INPUT "DocumentClassInformation", INPUT getStack(), OUTPUT iId).
                                                            if (iId <> ?) THEN DO:
                                                                 addStack(iId).

                                                                      RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "DocumentClassCode", OUTPUT ttPendentTaxInformation.DocumentClassCode).
                                                                      RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "DocumentClassDescription", OUTPUT ttPendentTaxInformation.DocumentClassDescription).
                                                                 delStack().
                                                            END.

                                                            RUN searchTag IN hGenXml (INPUT "DocumentInformation", INPUT getStack(), OUTPUT iId).
                                                            if (iId <> ?) THEN DO:
                                                                 addStack(iId).

                                                                      RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "DocumentSerieCode", OUTPUT ttPendentTaxInformation.DocumentSerieCode).
                                                                      RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "DocumentNumber", OUTPUT ttPendentTaxInformation.DocumentNumber).
                                                                      RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "DocumentParcelNumber", OUTPUT ttPendentTaxInformation.DocumentParcelNumber).
                                                                 delStack().
                                                            END.

                                                            RUN searchTag IN hGenXml (INPUT "StandardHistoryInformation", INPUT getStack(), OUTPUT iId).
                                                            if (iId <> ?) THEN DO:
                                                                 addStack(iId).

                                                                      RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "StandardHistoryCode", OUTPUT ttPendentTaxInformation.StandardHistoryCode).
                                                                      RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "StandartHistoryDescription", OUTPUT ttPendentTaxInformation.StandartHistoryDescription).
                                                                 delStack().
                                                            END.

                                                            RUN getSonDec IN hGenXml (INPUT getStack(), INPUT "RevenueTax", OUTPUT ttPendentTaxInformation.RevenueTax).
                                                            RUN getSonDec IN hGenXml (INPUT getStack(), INPUT "INSSDeduction", OUTPUT ttPendentTaxInformation.INSSDeduction).
                                                            RUN getSonDec IN hGenXml (INPUT getStack(), INPUT "DependentDeduction", OUTPUT ttPendentTaxInformation.DependentDeduction).
                                                            RUN getSonDec IN hGenXml (INPUT getStack(), INPUT "PensionDeduction", OUTPUT ttPendentTaxInformation.PensionDeduction).
                                                            RUN getSonDec IN hGenXml (INPUT getStack(), INPUT "OtherDeductions", OUTPUT ttPendentTaxInformation.OtherDeductions).
                                                            RUN getSonDec IN hGenXml (INPUT getStack(), INPUT "TaxBaseValue", OUTPUT ttPendentTaxInformation.TaxBaseValue).
                                                            RUN getSonDec IN hGenXml (INPUT getStack(), INPUT "TaxPercentage", OUTPUT ttPendentTaxInformation.TaxPercentage).
                                                            RUN getSonDec IN hGenXml (INPUT getStack(), INPUT "PaidTax", OUTPUT ttPendentTaxInformation.PaidTax).
                                                            RUN getSonDec IN hGenXml (INPUT getStack(), INPUT "TaxValue", OUTPUT ttPendentTaxInformation.TaxValue).
                                                            RUN getSonDate IN hGenXml (INPUT getStack(), INPUT "DueDate", OUTPUT ttPendentTaxInformation.DueDate).
                                                            RUN searchTag IN hGenXml (INPUT "CurrencyInformation", INPUT getStack(), OUTPUT iId).
                                                            if (iId <> ?) THEN DO:
                                                                 addStack(iId).

                                                                      RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "CurrencyCode", OUTPUT ttPendentTaxInformation.CurrencyCode).
                                                                      RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "CurrencyDescription", OUTPUT ttPendentTaxInformation.CurrencyDescription).
                                                                 delStack().
                                                            END.

                                                            RUN getSonDec IN hGenXml (INPUT getStack(), INPUT "EconomicPurposeValue", OUTPUT ttPendentTaxInformation.EconomicPurposeValue).
                                                            RUN searchTag IN hGenXml (INPUT "SupplierInformation", INPUT getStack(), OUTPUT iId).
                                                            if (iId <> ?) THEN DO:
                                                                 addStack(iId).

                                                                      RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "SupplierCode", OUTPUT ttPendentTaxInformation.SupplierCode).
                                                                      RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "SupplierName", OUTPUT ttPendentTaxInformation.SupplierName).
                                                                      RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "SupplierShortName", OUTPUT ttPendentTaxInformation.SupplierShortName).
                                                                      RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "GenerealIdentification", OUTPUT ttPendentTaxInformation.GenerealIdentification).
                                                                      RUN getSonDec IN hGenXml (INPUT getStack(), INPUT "EntityCode", OUTPUT ttPendentTaxInformation.EntityCode).
                                                                      RUN searchTag IN hGenXml (INPUT "SupplierGroupInformation", INPUT getStack(), OUTPUT iId).
                                                                      if (iId <> ?) THEN DO:
                                                                           addStack(iId).

                                                                                RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "SupplierGroupCode", OUTPUT ttPendentTaxInformation.SupplierGroupCode).
                                                                                RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "SupplierGroupDescription", OUTPUT ttPendentTaxInformation.SupplierGroupDescription).
                                                                           delStack().
                                                                      END.

                                                                 delStack().
                                                            END.

                                                            RUN getSonDec IN hGenXml (INPUT getStack(), INPUT "DeductionValue", OUTPUT ttPendentTaxInformation.DeductionValue).
                                                            RUN searchTag IN hGenXml (INPUT "ExternalLocationInformation", INPUT getStack(), OUTPUT iId).
                                                            if (iId <> ?) THEN DO:
                                                                 addStack(iId).

                                                                      RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "CountryCode", OUTPUT ttPendentTaxInformation.CountryCode_00).
                                                                      RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "CountryName", OUTPUT ttPendentTaxInformation.CountryName_00).
                                                                      RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "StateCode", OUTPUT ttPendentTaxInformation.StateCode_00).
                                                                      RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "StateName", OUTPUT ttPendentTaxInformation.StateName_00).
                                                                 delStack().
                                                            END.

                                                            RUN searchTag IN hGenXml (INPUT "ExternalAccountInformation", INPUT getStack(), OUTPUT iId).
                                                            if (iId <> ?) THEN DO:
                                                                 addStack(iId).

                                                                      RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "AccountPlanCode", OUTPUT ttPendentTaxInformation.AccountPlanCode_00).
                                                                      RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "AccountPlanDescription", OUTPUT ttPendentTaxInformation.AccountPlanDescription_00).
                                                                      RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "AccountCode", OUTPUT ttPendentTaxInformation.AccountCode_00).
                                                                      RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "SubAccountCode", OUTPUT ttPendentTaxInformation.SubAccountCode_00).
                                                                      RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "AccountDescription", OUTPUT ttPendentTaxInformation.AccountDescription_00).
                                                                      RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "AlternateAccountCode", OUTPUT ttPendentTaxInformation.AlternateAccountCode_00).
                                                                      RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "InternationalStandardAccountCode", OUTPUT ttPendentTaxInformation.InternationalStandardAccountC_00).
                                                                      RUN getSonDec IN hGenXml (INPUT getStack(), INPUT "ReducedAccountCode", OUTPUT ttPendentTaxInformation.ReducedAccountCode_00).
                                                                 delStack().
                                                            END.

                                                            RUN searchTag IN hGenXml (INPUT "ExternalFinancialFlowType", INPUT getStack(), OUTPUT iId).
                                                            if (iId <> ?) THEN DO:
                                                                 addStack(iId).

                                                                      RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "FinancialFlowTypeCode", OUTPUT ttPendentTaxInformation.FinancialFlowTypeCode).
                                                                      RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "FinancialFlowTypeDescription", OUTPUT ttPendentTaxInformation.FinancialFlowTypeDescription).
                                                                 delStack().
                                                            END.

                                                            ASSIGN iId = getStack().
                                                            delStack().
                                                            RUN getNextSonId IN hGenXml (INPUT getStack(), INPUT iId, OUTPUT iId).
                                                       END.

                                                  delStack().
                                             END.

                                             RUN searchTag IN hGenXml (INPUT "ExternalEconomicPurposeInformation", INPUT getStack(), OUTPUT iId).
                                             if (iId <> ?) THEN DO:
                                                  addStack(iId).

                                                       RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "EconomicPurposeCode", OUTPUT ttAccountPayableDocumentI_00.EconomicPurposeCode).
                                                       RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "EconomicPurposeDescription", OUTPUT ttAccountPayableDocumentI_00.EconomicPurposeDescription).
                                                  delStack().
                                             END.

                                             ASSIGN iId = getStack().
                                             delStack().
                                             RUN getNextSonId IN hGenXml (INPUT getStack(), INPUT iId, OUTPUT iId).
                                        END.

                                   delStack().
                              END.

                              RUN searchTag IN hGenXml (INPUT "ListOfRelactoAccountPayableDocument", INPUT getStack(), OUTPUT iId).
                              if (iId <> ?) THEN DO:
                                   addStack(iId).

                                        RUN getFirstSonId IN hGenXml (INPUT getStack(), OUTPUT iId).

                                        DO WHILE iId <> ?:
                                        addStack(iId).

                                             /*Criacao de valores para manter as relacoes*/
                                             CREATE ttRelactoAccountPayableDo_00.
                                             ASSIGN ttRelactoAccountPayableDo_00.ttRelactoAccountPayableDo_00ID = iId.

                                             RUN searchTag IN hGenXml (INPUT "SupplierInformation", INPUT getStack(), OUTPUT iId).
                                             if (iId <> ?) THEN DO:
                                                  addStack(iId).

                                                       RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "SupplierCode", OUTPUT ttRelactoAccountPayableDo_00.SupplierCode).
                                                       RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "SupplierName", OUTPUT ttRelactoAccountPayableDo_00.SupplierName).
                                                       RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "SupplierShortName", OUTPUT ttRelactoAccountPayableDo_00.SupplierShortName).
                                                       RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "GenerealIdentification", OUTPUT ttRelactoAccountPayableDo_00.GenerealIdentification).
                                                       RUN getSonDec IN hGenXml (INPUT getStack(), INPUT "EntityCode", OUTPUT ttRelactoAccountPayableDo_00.EntityCode).
                                                       RUN searchTag IN hGenXml (INPUT "SupplierGroupInformation", INPUT getStack(), OUTPUT iId).
                                                       if (iId <> ?) THEN DO:
                                                            addStack(iId).

                                                                 RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "SupplierGroupCode", OUTPUT ttRelactoAccountPayableDo_00.SupplierGroupCode).
                                                                 RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "SupplierGroupDescription", OUTPUT ttRelactoAccountPayableDo_00.SupplierGroupDescription).
                                                            delStack().
                                                       END.

                                                  delStack().
                                             END.

                                             RUN searchTag IN hGenXml (INPUT "DocumentClassInformation", INPUT getStack(), OUTPUT iId).
                                             if (iId <> ?) THEN DO:
                                                  addStack(iId).

                                                       RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "DocumentClassCode", OUTPUT ttRelactoAccountPayableDo_00.DocumentClassCode).
                                                       RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "DocumentClassDescription", OUTPUT ttRelactoAccountPayableDo_00.DocumentClassDescription).
                                                  delStack().
                                             END.

                                             RUN searchTag IN hGenXml (INPUT "DocumentInformation", INPUT getStack(), OUTPUT iId).
                                             if (iId <> ?) THEN DO:
                                                  addStack(iId).

                                                       RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "DocumentSerieCode", OUTPUT ttRelactoAccountPayableDo_00.DocumentSerieCode).
                                                       RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "DocumentNumber", OUTPUT ttRelactoAccountPayableDo_00.DocumentNumber).
                                                       RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "DocumentParcelNumber", OUTPUT ttRelactoAccountPayableDo_00.DocumentParcelNumber).
                                                  delStack().
                                             END.

                                             RUN searchTag IN hGenXml (INPUT "BranchInformation", INPUT getStack(), OUTPUT iId).
                                             if (iId <> ?) THEN DO:
                                                  addStack(iId).

                                                       RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "BranchCode", OUTPUT ttRelactoAccountPayableDo_00.BranchCode).
                                                       RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "BranchDescription", OUTPUT ttRelactoAccountPayableDo_00.BranchDescription).
                                                  delStack().
                                             END.

                                             RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "CorrectValueReason", OUTPUT ttRelactoAccountPayableDo_00.CorrectValueReason).
                                             ASSIGN iId = getStack().
                                             delStack().
                                             RUN getNextSonId IN hGenXml (INPUT getStack(), INPUT iId, OUTPUT iId).
                                        END.

                                   delStack().
                              END.

                         delStack().
                    END.

                    RUN getSonVal IN hGenXml (INPUT getStack(), INPUT "ExternalOrganizationTranslationMatrixCode", OUTPUT ExternalOrganizationTranslati_00).
               delStack().
          END.

     delStack().
     /* ********* LEITURA DA MENSAGEM - END   ********* */


     /* ********* EFETIVAÄ«O - BEGIN ********* */



{adapters\xml\fi5\axrfi005Upsert.i}


     /* ********* EFETIVAÄ«O - END   ********* */

/* ******************************************* */
/* *************** BODY - END   ************** */
/* ******************************************* */

END PROCEDURE.


PROCEDURE receiveMessage:

/*PARAMETERS - BEGIN*/
DEFINE INPUT PARAM hInputXML AS HANDLE NO-UNDO.
DEFINE OUTPUT PARAM hOutputXML AS HANDLE NO-UNDO.
/*PARAMETERS - END*/


/*LOCAL VARIABLES - BEGIN*/
/*LOCAL VARIABLES - END*/


/* ******************************************* */
/* *************** BODY - BEGIN ************** */
/* ******************************************* */

     /* VERIFICA SE MessageHandler.p ESTA NA MEMORIA */
     {xmlinc/xmlLoadMessageHandlerRec.i &MessageHandler="hMessageHandler" &MHReturnValue="cReturnValue" &MHReturnError="hOutputXML"}

     IF cReturnValue <> "OK" THEN DO:
          RETURN cReturnValue.
     END.

     /* INTERPRETA, ARMAZENA E VALIDA A MENSAGEM QUE RECEBE */
     RUN parseMessage IN hMessageHandler (
          INPUT  hInputXml, INPUT "{&XmlTranName}", 
          INPUT "{&XmlMaxTranVersion}", 
          INPUT "{&XmlMinTranVersion}", 
          INPUT "{&XmlListOfEvents}",
          OUTPUT lSuccessProcess,
          OUTPUT cTranAction, 
          OUTPUT cTranEvent,
          OUTPUT cTranVersion,
          OUTPUT hOutputXML ).

     /* SE N«O PROCESSOU CORRETAMENTE RETORNA ERRO */
     IF NOT lSuccessProcess OR RETURN-VALUE <> "OK" THEN 
     /* DAR TRATAMENTO CONVENIENTE ANTES DE RETORNAR */
          RETURN RETURN-VALUE.

     /* VERIFICA SE APIXML ESTA NA MEMORIA */
     {xmlinc/xmlloadgenxmlrec.i &GenXml="hGenXml" &GXReturnValue="cReturnValue" &GXReturnError="hOutputXML"}

     /* VERIFICA SE O ut-genxml FOI INICIADO CORRETAMENTE */
     IF cReturnValue <> "OK"
     THEN DO:
          /* ELIMINA A MENSAGEM OBTIDA NO M?TODO getBusinessContent */
          DELETE OBJECT hBusinessContent NO-ERROR.

          RETURN cReturnValue.
     END.



{adapters\xml\fi5\axrfi005VersionControl.i}



/* ******************************************* */
/* *************** BODY - END   ************** */
/* ******************************************* */

END PROCEDURE.


/****** INTERNAL PROCEDURES - END*/

